import { useState, type ReactNode } from 'react'
import { Calculator, Check, Lightbulb, Search, Sparkles, Target, TriangleAlert } from 'lucide-react'
import { MathExpression } from '../components/MathExpression'
import { BidiText } from '../components/BidiText'
import { LessonShell } from '../components/lesson/LessonShell'
import { SourceCard } from '../components/lesson/SourceCard'
import type { LessonStep } from '../components/lesson/types'
import { finalAssessment3 } from '../teacher/lesson3'

function Guided({ id, prompt, answer, hint }: { id: string; prompt: ReactNode; answer: string; hint: string }) { const [value,setValue]=useState(''); const [checked,setChecked]=useState(false); const ok=value.trim().replace(/,/g,'')===answer.replace(/,/g,''); return <label className="test-question"><strong>{prompt}</strong><div className="answer-row" style={{justifyContent:'flex-start'}}><input aria-label={id} value={value} onChange={e=>{setValue(e.target.value);setChecked(false)}}/><button type="button" onClick={()=>setChecked(true)}>تحقق</button></div>{checked&&<p className={ok?'gentle-feedback good':'gentle-feedback'}>{ok?'أحسنت. اقرأ الخانات من اليمين وتأكد بالجمع العكسي.':hint}</p>}</label> }
function PlaceTable(){return <div className="book-table-wrap"><table className="book-table"><thead><tr>{['الملايين','مئات الألوف','عشرات الألوف','آحاد الألوف','المئات','العشرات','الآحاد'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody><tr>{['2','4','1','3','1','5','5'].map((x,i)=><td key={i}><MathExpression>{x}</MathExpression></td>)}</tr><tr>{['2,000,000','400,000','10,000','3,000','100','50','5'].map((x,i)=><td key={i}><MathExpression>{x}</MathExpression></td>)}</tr></tbody></table></div>}
function Intro(){return <div className="lesson-intro"><div className="lesson-hero-icon"><Calculator size={30}/></div><div className="lesson-goals"><strong>سنتعلّم</strong><span>✓ قراءة الأعداد الطبيعية وكتابتها وتحليلها إلى قيم منازل</span><span>✓ التعامل مع الصفر في الخانات</span></div><SourceCard label="من الكتاب — ص 10"><p>عند طباعة العملات الورقية يعطى لكل ورقة نقدية نمرة (عدد) خاصة بها، وتلك النمرة بها لا تتكرر أبداً على أي ورقة نقدية أخرى.</p></SourceCard><div className="support-tip"><Lightbulb size={20}/><span><strong>فكرة البداية:</strong> العدد ليس مجموعة أرقام متجاورة فقط؛ مكان الرقم هو الذي يحدد قيمته. فالرقم 5 في الآحاد يساوي 5، وفي الملايين يساوي 5,000,000.</span></div></div>}
function Explore(){const [choice,setChoice]=useState<string|null>(null);return <div><div className="step-banner"><Sparkles size={20}/><span>انطلاقة نشطة — جرّب قبل القاعدة</span></div><SourceCard label="من الكتاب — ص 10"><p>اختر الإجابة الصحيحة:</p><div className="choice-list">{['4000 = أربعة آلاف','4000 = أربعون ألفاً','7000 + 400 + 2 = 7402','7000 + 400 + 2 = 7042'].map(x=><button key={x} className={choice===x?'selected-choice':''} onClick={()=>setChoice(x)}>{x}</button>)}</div>{choice&&<div className="explanation-box"><Check size={18}/>{choice==='4000 = أربعة آلاف'||choice==='7000 + 400 + 2 = 7402'?'صحيح. في الصيغة اللفظية نقرأ المنزلة، وفي الصيغة التفصيلية نحافظ على قيمة كل خانة.':'تأمل عدد الأصفار ومكان الرقم 4؛ أعد تجميع العدد قبل تثبيت الإجابة.'}</div>}</SourceCard><SourceCard label="من الكتاب — ص 10"><p>العدد <MathExpression>2,413,155</MathExpression> يُقرأ: مليونان وأربعمئة وثلاثة عشر ألفاً ومئة وخمسة وخمسون.</p><Guided id="nn-p10-place" prompt="ما قيمة الرقم 4 في العدد 2,413,155؟" answer="400000" hint="الرقم 4 يقع في خانة مئات الألوف، لا في خانة الآحاد."/></SourceCard></div>}
function Concept(){return <div><SourceCard label="تعلّم — ص 10"><p>نضع الأعداد في خاناتها، ونسمّي كل ثلاث خانات مجموعة: مجموعة الوحدات، مجموعة الألوف، مجموعة الملايين. قيمة الرقم تتغير بحسب منزلته.</p><PlaceTable/><p>الصيغة التفصيلية للعدد <MathExpression>2,413,155</MathExpression> هي <MathExpression>2,000,000 + 400,000 + 10,000 + 3,000 + 100 + 50 + 5</MathExpression>.</p></SourceCard><div className="support-tip"><Target size={20}/><span><strong>طريقة تفكير ثابتة:</strong> ابدأ من اليمين، سمِّ الخانة، اكتب قيمتها، ثم انتقل خانة واحدة إلى اليسار. بعد ذلك اجمع القيم للتحقق.</span></div></div>}
function Examples(){return <div><SourceCard label="مثال محلول — ص 11"><p>نقرأ العدد <MathExpression>2,415,155</MathExpression>: مليونان وأربعمئة وخمسة عشر ألفاً ومئة وخمسة وخمسون.</p><p>ونكتبه تفصيلياً: <MathExpression>2,000,000 + 400,000 + 10,000 + 5,000 + 100 + 50 + 5</MathExpression>.</p></SourceCard><SourceCard label="مثال آخر وملاحظة — ص 11"><p><MathExpression>2,605,173</MathExpression> = مليونان وستمئة وخمسة آلاف ومئة وثلاثة وسبعون.</p><p>إذا وُجد الصفر في خانة، فإن قيمته صفر ولا نكتبه حداً في الصيغة التفصيلية، لكننا لا نحذفه من العدد: <MathExpression>1,206,079 = 1,000,000 + 200,000 + 6,000 + 70 + 9</MathExpression>.</p></SourceCard><div className="common-mistakes"><h3>خطأ شائع</h3><p>كتابة 1,206,079 على صورة 1,267,9 أو حذف الصفر من الوسط. الصفر يحفظ مكان الخانات، ثم نتركه فقط عند جمع القيم غير الصفرية.</p></div></div>}
function Practice(){return <div><div className="step-banner"><Check size={20}/><span>تحقق من فهمك — ص 12</span></div><SourceCard label="السؤالان 1 و2 — ص 12"><p>اكتب <MathExpression>20,200,002</MathExpression> لفظياً: <strong>عشرون مليوناً ومئتان وألفان.</strong></p><p>أكمل: <MathExpression>2,340,801 = 2,000,000 + 300,000 + 40,000 + 800 + 1</MathExpression>.</p></SourceCard><Guided id="nn-p12-word" prompt="ما قيمة الرقم 3 في العدد 2,340,801؟" answer="300000" hint="الرقم 3 في خانة مئات الألوف، فقيمته 300,000."/><SourceCard label="السؤال 3 — ص 12"><p>حوّل العبارات اللفظية إلى أعداد ثم أعد كتابتها باستعمال جدول الخانات. املأ الخانات من اليمين: الآحاد، العشرات، المئات، آحاد الألوف، عشرات الألوف، مئات الألوف، الملايين.</p></SourceCard></div>}
function Applications(){return <div><SourceCard label="التمارين 1–4 — ص 13"><p>أودع مازن <MathExpression>4,500,000</MathExpression> ليرة سورية، وأودع فؤاد <MathExpression>3,569,700</MathExpression> ليرة. الفرق <MathExpression>930,300</MathExpression> ليرة. ونصف قطر الكرة الأرضية يكتب تقريباً <MathExpression>6,308,000</MathExpression> متراً.</p></SourceCard><SourceCard label="التمرين 5 — ص 13"><p>سبعون مليوناً = <MathExpression>70,000,000</MathExpression> وفيه 7 أصفار. مليونان = <MathExpression>2,000,000</MathExpression> وفيه 6 أصفار. أربعة آلاف ألف = <MathExpression>4,000,000</MathExpression> وفيه 6 أصفار.</p></SourceCard><SourceCard label="التمرين 6 — ص 13"><p><MathExpression>2,436,814 = 2,000,000 + 400,000 + 30,000 + 6,000 + 800 + 10 + 4</MathExpression>.</p><p><MathExpression>1,060,505 = 1,000,000 + 60,000 + 500 + 5</MathExpression>.</p></SourceCard></div>}
function Interactive(){const [n,setN]=useState('5345600'); const digits=n.padStart(7,'0').slice(-7).split(''); return <div className="interaction-card"><span className="section-kicker">نشاط إضافي تفاعلي</span><h3>ابنِ العدد من خاناته</h3><p>غيّر رقماً، ثم راقب قيمة المنزلة والصيغة التفصيلية. الهدف: ملاحظة أن الرقم نفسه يتغير أثره بتغير مكانه.</p><input aria-label="العدد التفاعلي" className="number-builder-input" value={n} onChange={e=>setN(e.target.value.replace(/[^0-9]/g,'').slice(0,7))}/><div className="digit-builder">{digits.map((d,i)=><button key={i} onClick={()=>{const a=digits.slice();a[i]=String((Number(a[i])+1)%10);setN(a.join(''))}}><small>{['الملايين','مئات الألوف','عشرات الألوف','آحاد الألوف','المئات','العشرات','الآحاد'][i]}</small><strong>{d}</strong><span><MathExpression>{Number(d)*10**(6-i)}</MathExpression></span></button>)}</div><div className="explanation-box"><Sparkles size={18}/>مثال التحليل: <MathExpression>{Number(n||0).toLocaleString('en-US')}</MathExpression> = مجموع قيم الخانات غير الصفرية.</div></div>}
function MorePractice(){return <div><SourceCard label="التمارين 7–9 — ص 13"><p>اكتب <MathExpression>5,345,600</MathExpression> بثلاثة أجزاء ثم فككه إلى قيم المنازل، واكتب ثلاثة ملايين ليرة على صورة عدد، واقرأ مسافة القمر بالكيلومترات.</p></SourceCard><SourceCard label="التمرينان 10 و11 — ص 14"><p>سعر السيارة <MathExpression>6,849,500</MathExpression>: <strong>ستة ملايين وثمانمئة وتسعة وأربعون ألفاً وخمسمئة.</strong></p><p>خطأ مراد في <MathExpression>5,305,707</MathExpression> أنه أسقط الآحاد 7؛ الصحيح: خمسة ملايين وثلاثمئة وخمسة آلاف وسبعمئة وسبعة.</p></SourceCard><SourceCard label="التمرينان 12–15 — ص 14"><p>على الشيك نكتب <MathExpression>5,600,000</MathExpression> رقماً ولفظاً متطابقين. وفي الرزم: <MathExpression>100 × 500 = 50,000</MathExpression>، وعشر رزم تساوي <MathExpression>500,000</MathExpression> ليرة.</p><p>في مسألة الخانات، اكتب الشروط في جدول ثم جرّب الاحتمالات وتحقق من مجموع العشرات والآحاد.</p></SourceCard></div>}
function Mistakes(){const [shown,setShown]=useState(false);return <div className="mistake-spot"><div className="step-banner"><TriangleAlert size={20}/><span>اكتشف الخطأ وفكّر</span></div><div className="mistake-scenario"><p>كتب طالب <MathExpression>5,305,707</MathExpression> لفظياً: خمسة ملايين وثلاثمئة وخمسة آلاف وسبعمئة. أين الخطأ؟</p><button className="reveal-button" onClick={()=>setShown(true)}><Search size={17}/> اكشف التحليل</button>{shown&&<div className="explanation-box"><Check size={18}/>أُهمل الرقم 7 في الآحاد. نقسم العدد إلى 5 | 305 | 707، لذلك يجب أن نقول: وسبعمئة وسبعة.</div>}</div></div>}
function Recap(){return <div className="recap-step"><h3>خلاصة الأعداد الطبيعية</h3><ul><li>نقرأ العدد في مجموعات من ثلاثة أرقام: ملايين، ألوف، وحدات.</li><li>قيمة الرقم = الرقم × قيمة منزلته؛ لذلك لا تكفي قراءة الرقم منفرداً.</li><li>الصيغة التفصيلية تجمع قيم المنازل غير الصفرية.</li><li>الصفر يحافظ على مكان الخانة، ولا يظهر كحد في المجموع إذا كانت قيمته صفراً.</li><li>نختبر الحل بإعادة جمع القيم وبالتحقق من عدد الخانات.</li></ul></div>}
function Final(){const [a,setA]=useState<Record<string,string>>({}); const [done,setDone]=useState(false); const score=finalAssessment3.filter(q=>(a[q.id]||'').trim()===q.answer).length; return <div className="final-test"><div className="step-banner"><Check size={20}/><span>اختبار ختامي جديد</span></div><p>أسئلة جديدة تقيس القراءة، القيمة المكانية، التحليل، اكتشاف الخطأ والتطبيق.</p>{finalAssessment3.map((q,i)=><label className="test-question" key={q.id}><strong>{i+1}. {q.text}</strong>{q.type==='input'?<input value={a[q.id]||''} onChange={e=>setA({...a,[q.id]:e.target.value})}/>:<div className="choice-list">{q.options?.map(o=><button type="button" key={o} className={a[q.id]===o?'selected-choice':''} onClick={()=>setA({...a,[q.id]:o})}>{o}</button>)}</div>}</label>)}<button className="primary-button submit-test" onClick={()=>setDone(true)}>عرض النتيجة</button>{done&&<div className="test-result"><strong>نتيجتك: {score} / {finalAssessment3.length}</strong><p>راجع كل خانة أخطأت فيها، ثم أعد بناء العدد من اليمين إلى اليسار.</p></div>}</div>}
export function NaturalNumbersLesson(){const steps:LessonStep[]=[{id:'intro',title:'انطلاقة الدرس',content:<Intro/>},{id:'explore',title:'انطلاقة نشطة',content:<Explore/>},{id:'concept',title:'الفكرة الأساسية',content:<Concept/>},{id:'examples',title:'أمثلة الكتاب',content:<Examples/>},{id:'practice',title:'تحقق من فهمك',content:<Practice/>},{id:'applications',title:'تمارين الكتاب',content:<Applications/>},{id:'interactive',title:'ابنِ العدد',content:<Interactive/>},{id:'more',title:'تطبيقات وتحديات',content:<MorePractice/>},{id:'mistakes',title:'اكتشف الخطأ',content:<Mistakes/>},{id:'recap',title:'الخلاصة',content:<Recap/>},{id:'final',title:'الاختبار الختامي',content:<Final/>}];const [active,setActive]=useState(0);return <LessonShell title="الأعداد الطبيعية" steps={steps} activeStep={active} onStepChange={setActive}/>}
