import { useState } from 'react'
import { Check, Lightbulb, Sparkles } from 'lucide-react'
import { LessonShell } from '../components/lesson/LessonShell'
import { SourceCard } from '../components/lesson/SourceCard'
import { MathExpression } from '../components/MathExpression'
import { finalAssessment4 } from '../teacher/lesson4'
import type { LessonStep } from '../components/lesson/types'

const Rule = () => <div className="definition-box"><strong>قاعدة التقريب</strong><p>نحدد الخانة المطلوبة، ثم ننظر إلى الخانة التي على يمينها: إذا كان الرقم 5 أو أكبر نزيد الخانة المطلوبة واحداً، وإذا كان أصغر من 5 تبقى كما هي. بعد ذلك نكتب أصفاراً في الخانات إلى يمينها.</p></div>
function Intro(){return <div><SourceCard label="الكتاب · ص 15"><h3>تقريب الأعداد الطبيعية</h3><p>هل تعلم أن القمر يبعد عن الأرض حوالي <MathExpression>385920</MathExpression> كيلومتراً؟ وأن أكبر صحراء في العالم هي الصحراء الكبرى ومساحتها تساوي <MathExpression>5628000</MathExpression> كيلومتراً مربعاً؟</p><p>سنستعمل التقريب لتصبح قراءة الأعداد الكبيرة أسهل.</p></SourceCard><Rule/></div>}
function Hundreds(){const [answer,setAnswer]=useState('');const ok=answer.replace(/[, ]/g,'')==='600';return <div><SourceCard label="الكتاب · ص 15"><h3>نشاط على مستقيم الأعداد</h3><p>قرّب العدد <MathExpression>580</MathExpression> لأقرب مئة. ثم قرّب <MathExpression>315</MathExpression> لأقرب مئة.</p><p>على المستقيم: 580 أقرب إلى 600، و315 أقرب إلى 300.</p></SourceCard><div className="interaction-card"><h3>جرّب بنفسك: 580 ≈ ؟</h3><input inputMode="numeric" value={answer} onChange={e=>setAnswer(e.target.value)} aria-label="تقريب 580" placeholder="اكتب العدد"/><button className="primary-button" onClick={()=>setAnswer(answer)}>تحقق</button>{answer&&<p className={ok?'gentle-feedback good':'gentle-feedback'}>{ok?'أحسنت! 580 أبعد عن 500 وأقرب إلى 600.':'تلميح: قارن المسافتين بين 580 و500، وبين 580 و600.'}</p>}</div></div>}
function Place(){const [value,setValue]=useState('');return <div><SourceCard label="الكتاب · ص 16"><h3>مثال: التقريب لأقرب ألف</h3><p>نقرّب <MathExpression>2137</MathExpression> إلى أقرب ألف. رقم المئات هو <MathExpression>1</MathExpression>، وهو أصغر من 5، إذن النتيجة <MathExpression>2000</MathExpression>.</p></SourceCard><SourceCard label="الكتاب · ص 16"><h3>مثال: التقريب لأقرب مئة ألف</h3><p>في <MathExpression>3482137</MathExpression> رقم مئات الألوف هو 4، وعن يمينه 8؛ نزيده إلى 5 ونصفر ما بعده: <MathExpression>3500000</MathExpression>.</p></SourceCard><div className="interaction-card"><h3>ما ناتج تقريب 3482137 إلى أقرب مئة ألف؟</h3><input value={value} onChange={e=>setValue(e.target.value)} aria-label="إجابة التقريب" placeholder="اكتب الناتج"/>{value&&<p className="gentle-feedback good">راجع: الرقم 8 يجعلنا نزيد 4 إلى 5، ثم نضع الأصفار.</p>}</div></div>}
function Million(){return <div><SourceCard label="الكتاب · ص 17"><h3>التقريب إلى أقرب مليون</h3><p>لتقريب <MathExpression>3582137</MathExpression> إلى أقرب مليون ننظر إلى الرقم 5 عن يمين خانة الملايين، فنزيد 3 إلى 4: <MathExpression>4000000</MathExpression>.</p></SourceCard><div className="support-tip"><Lightbulb size={20}/><span>في حالة الرقم 5 نقرّب إلى الأعلى، ثم نحول الخانات التالية إلى أصفار.</span></div></div>}
function Practice(){const [choice,setChoice]=useState('');const opts=['1400','1399','1300'];return <div><SourceCard label="الكتاب · ص 15 و18"><h3>تدريب متنوع</h3><p>العدد <MathExpression>1390</MathExpression> لأقرب مئة هو:</p>{opts.map(o=><button key={o} className={choice===o?'selected-choice':''} onClick={()=>setChoice(o)}><MathExpression>{o}</MathExpression></button>)}{choice&&<p className={choice==='1400'?'gentle-feedback good':'gentle-feedback'}>{choice==='1400'?'صحيح. العشرات 9، لذلك نزيد المئات.':'تذكّر: ننظر إلى العشرات 9، وهي أكبر من 5.'}</p>}<p>تطبيقات الكتاب: <MathExpression>112880≈110000</MathExpression>، <MathExpression>1750000≈2000000</MathExpression>، <MathExpression>6373000≈6000000</MathExpression>.</p></SourceCard></div>}
function Test(){const [a,setA]=useState<Record<string,string>>({});const [done,setDone]=useState(false);const score=finalAssessment4.filter(q=>a[q.id]?.replace(/[, ]/g,'')===q.answer.replace(/[, ]/g,'')).length;return <div className="final-test"><div className="step-banner"><Sparkles size={20}/>اختبار شامل جديد</div>{finalAssessment4.map(q=><label className="test-question" key={q.id}><strong>{q.text}</strong><input value={a[q.id]||''} onChange={e=>setA({...a,[q.id]:e.target.value})}/></label>)}<button className="primary-button" onClick={()=>setDone(true)}>عرض النتيجة <Check size={16}/></button>{done&&<div className="test-result">نتيجتك: {score} / {finalAssessment4.length}. {score===5?'إتقان رائع!':'راجع قاعدة التقريب وحاول مرة أخرى.'}</div>}</div>}
export function RoundingLesson(){const steps:LessonStep[]=[{id:'intro',title:'انطلاقة الدرس',content:<Intro/>},{id:'hundreds',title:'التقريب لأقرب مئة',content:<Hundreds/>},{id:'thousands',title:'التقريب لأقرب ألف ومئة ألف',content:<Place/>},{id:'millions',title:'التقريب لأقرب مليون',content:<Million/>},{id:'practice',title:'تمارين الكتاب وتطبيقاته',content:<Practice/>},{id:'test',title:'الاختبار الختامي',content:<Test/>}];const [active,setActive]=useState(0);return <LessonShell title="تقريب الأعداد الطبيعية" steps={steps} activeStep={active} onStepChange={setActive} theme="lesson-four"/>}
