import { defineLessonTest, lessonQuestion, math, rich, text, textOnly, type LessonQuestionDraft } from '../../lessonTestBuilder'
import type { QuestionDefinition } from '../../types'

const testId = 'lesson-adding-subtracting-natural-numbers-test'
const lessonId = 'adding-subtracting-natural-numbers'
const qid = (number: number) => `${testId}-q${String(number).padStart(2, '0')}`
const q = (number: number, draft: LessonQuestionDraft) =>
  lessonQuestion(testId, lessonId, qid(number), draft)
const option = (id: string, ...runs: Parameters<typeof rich>) => ({ id, label: rich(...runs) })
const optionText = (id: string, value: string) => ({ id, label: textOnly(value) })

const questions: QuestionDefinition[] = [
  q(1, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('في سجلّ مخزن، توجد '), math('13,425'), text(' قطعة في الرف الأول و'), math('8,760'), text(' قطعة في الرف الثاني. إذا طُلب العدد الكلي، فأي عملية تختار؟')),
    concepts: ['addition-and-subtraction-applications'], skills: ['choose-operation-from-goal'], sourceConcepts: ['select-operation-for-application'],
    coverage: { applications: ['combine-quantities'] },
    options: [option('q01-a', math('13,425+8,760')), option('q01-b', math('13,425−8,760')), option('q01-c', math('13,425×8,760')), option('q01-d', math('13,425÷8,760'))],
    answer: 'q01-a',
    solution: { idea: rich(text('العدد الكلي يجمع الكميتين الموجودتين معاً.')), steps: [rich(text('المطلوب هو ضم ما في الرفين، لا معرفة الفرق بينهما.')), rich(text('لذلك نختار عملية الجمع.'))], finalAnswer: rich(math('13,425+8,760')) },
    originalityNote: 'موقف مخزون جديد يطلب اختيار العملية بحسب كلمة «الكلي»؛ لا يعيد سياق أو قيم تطبيق من اختبار الدرس.',
  }),
  q(2, {
    type: 'numeric', difficulty: 'basic',
    prompt: rich(text('عند جمع '), math('38,407'), text(' و'), math('26,958'), text(' عمودياً، كم مرة ينتقل حمل إلى المنزلة التالية؟')),
    concepts: ['addition-algorithm', 'regrouping'], skills: ['count-carries-in-addition'], sourceConcepts: ['column-addition-and-carrying'],
    answer: { expected: '3', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نعدّ كل منزلة يتجاوز مجموعها '), math('9'), text('، بما في ذلك الحمل الوارد إليها.')), steps: [rich(text('الآحاد: '), math('7+8=15'), text('، فيحدث حمل.')), rich(text('المئات: '), math('4+9=13'), text('، فيحدث حمل؛ والعشرات مجموعها '), math('0+5+1=6'), text(' فلا تحمل.')), rich(text('الآلاف: '), math('8+6+1=15'), text('، فيحدث حمل ثالث.'))], finalAnswer: rich(text('ينتقل الحمل ثلاث مرات.')) },
    originalityNote: 'يعدّ انتقالات الحمل في عملية جديدة بدلاً من تكرار صيغة «احسب حاصل الجمع» للسؤال الختامي ذي الحدين.',
  }),
  q(3, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('يمكن التحقق من '), math('6,821−2,475=4,346'), text(' بجمع الفرق مع المطروح، ويجب أن يعود الناتج إلى المطروح منه.')),
    concepts: ['inverse-check', 'subtraction-algorithm'], skills: ['verify-subtraction-by-addition'], sourceConcepts: ['inverse-operations-and-checking'],
    answer: true,
    solution: { idea: rich(text('الجمع والطرح عمليتان عكسيتان؛ مجموع الفرق والمطروح يساوي المطروح منه.')), steps: [rich(math('4,346+2,475=6,821')), rich(text('وهذا يطابق العدد الأصلي المطروح منه.'))], finalAnswer: rich(text('صحيح.')) },
    originalityNote: 'يحكم على قاعدة تحقق عامة مستخدمة مع عملية جديدة، لا ينسخ صيغة التحقق أو أعداد أسئلة الاختبار السابق.',
  }),
  q(4, {
    type: 'matching', difficulty: 'basic',
    prompt: rich(text('طابق الهدف الحسابي مع العملية التي تخدمه.')),
    concepts: ['addition-and-subtraction-applications', 'inverse-check'], skills: ['select-operation-for-task'], sourceConcepts: ['select-operation-for-application', 'inverse-operations-and-checking'],
    left: [optionText('q04-l1', 'إيجاد الكمية الكلية من جزأين'), optionText('q04-l2', 'إيجاد الباقي بعد إزالة كمية من الكل'), optionText('q04-l3', 'التحقق من طرح بإعادة الكل')],
    right: [optionText('q04-r1', 'الجزء الأول + الجزء الثاني'), optionText('q04-r2', 'الكل − الكمية المزالة'), optionText('q04-r3', 'الفرق + المطروح')],
    answer: [{ leftId: 'q04-l1', rightId: 'q04-r1' }, { leftId: 'q04-l2', rightId: 'q04-r2' }, { leftId: 'q04-l3', rightId: 'q04-r3' }],
    solution: { idea: rich(text('نختار العملية من العلاقة بين الكميات لا من شكل الأرقام.')), steps: [rich(text('ضم جزأين يعني الجمع.')), rich(text('إزالة كمية من كل معلوم لإيجاد الباقي تعني الطرح.')), rich(text('الفرق مع المطروح يعيد المطروح منه للتحقق.'))], finalAnswer: rich(text('الكل: جمع؛ الباقي: طرح؛ التحقق: الفرق مع المطروح.')) },
    originalityNote: 'مطابقة ثلاثة أهداف مفاهيمية بعملياتها، لا مسألة عددية من تطبيق كتابي أو الاختبار الختامي.',
  }),
  q(5, {
    type: 'error-analysis', difficulty: 'basic',
    prompt: rich(text('كتب متعلم '), math('46,728+18,596=54,214'), text(' بعد أن جمع كل عمود دون نقل الحمل إلى العمود التالي. اختر التشخيص والتصحيح.')),
    concepts: ['addition-algorithm', 'regrouping'], skills: ['diagnose-missing-carry', 'correct-column-addition'], sourceConcepts: ['column-addition-and-carrying'],
    coverage: { commonErrors: ['omit-carry-in-addition'] },
    studentWork: rich(math('46,728+18,596=54,214')),
    diagnoses: [optionText('q05-d1', 'لم ينقل ما زاد على 9 إلى العمود التالي'), optionText('q05-d2', 'جمع الأعداد بترتيب معكوس')],
    corrections: [option('q05-c1', math('65,324')), option('q05-c2', math('54,214'))],
    answer: { diagnosisId: 'q05-d1', correctionId: 'q05-c1' },
    solution: { idea: rich(text('في كل منزلة نكتب رقم الآحاد من المجموع ونحمل العشرات إلى اليسار.')), steps: [rich(text('مثلاً '), math('8+6=14'), text('، فنكتب '), math('4'), text(' ونحمل '), math('1'), text('.')), rich(text('يستمر النقل في المنازل التالية؛ النتيجة الكاملة '), math('65,324'), text('.'))], finalAnswer: rich(math('46,728+18,596=65,324')), commonError: rich(text('جمع كل منزلة مستقلة وإهمال الحمل المتولد من مجموع أكبر من تسعة.')) },
    originalityNote: 'يشخص إهمال الحمل المتكرر في جمع جديد، لا يعيد مسألة جمع خطأ معروفة أو يغير أرقامها فقط.',
  }),
  q(6, {
    type: 'numeric', difficulty: 'basic',
    prompt: rich(text('أوجد ناتج '), math('90,004−38,679'), text('.')),
    concepts: ['subtraction-algorithm', 'regrouping'], skills: ['subtract-with-borrowing'], sourceConcepts: ['column-subtraction-and-borrowing'],
    answer: { expected: '51325', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نطرح منزلةً منزلة، ونستلف عند الحاجة من المنزلة المناسبة إلى اليسار.')), steps: [rich(text('عند الآحاد لا تكفي '), math('4'), text(' لطرح '), math('9'), text('؛ نعيد التجميع عبر الأصفار.')), rich(text('بعد إتمام الاستلاف في الأعمدة يكون الفرق '), math('51,325'), text('.'))], finalAnswer: rich(math('51,325')) },
    originalityNote: 'طرح عمودي مع استلاف عبر أصفار من عدد جديد؛ لا يعيد مسألة نصف مليون أو عملية الطرح في الاختبار السابق.',
  }),
  q(7, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('احسب الفرق '), math('72,000−38,456'), text('.')),
    concepts: ['subtraction-algorithm', 'regrouping'], skills: ['borrow-across-zeroes', 'subtract-multi-digit-numbers'], sourceConcepts: ['column-subtraction-and-borrowing'],
    answer: { expected: '33544', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('تحتاج منازل الأعداد إلى إعادة تجميع ممتدة لأن المطروح منه ينتهي بأصفار.')), steps: [rich(text('نعيد التجميع من عشرات الآلاف عبر خانة الآلاف إلى المئات والعشرات والآحاد حسب الحاجة.')), rich(text('ثم نطرح كل منزلة بعد الاستلاف الصحيح.')), rich(math('72,000−38,456=33,544'))], finalAnswer: rich(math('33,544')) },
    originalityNote: 'يتطلب استلافاً متتابعاً عبر أصفار في طرح متوسط الطول؛ يختلف عن عملية الطرح المألوفة في الاختبار الختامي.',
  }),
  q(8, {
    type: 'ordering', difficulty: 'medium',
    prompt: rich(text('رتّب خطوات جمع عددين بالطريقة العمودية مع إعادة التجميع.')),
    concepts: ['addition-algorithm', 'regrouping'], skills: ['sequence-column-addition'], sourceConcepts: ['column-addition-and-carrying'],
    items: [optionText('q08-a', 'اجمع كل منزلة مع الحمل القادم إليها'), optionText('q08-b', 'اكتب العددين بمحاذاة المنازل المتناظرة'), optionText('q08-c', 'ابدأ من الآحاد ثم تابع نحو اليسار'), optionText('q08-d', 'انقل كل عشرة إلى المنزلة التالية عند الحاجة')],
    answer: ['q08-b', 'q08-c', 'q08-a', 'q08-d'],
    solution: { idea: rich(text('المحاذاة تسبق الجمع، ثم يبدأ الحساب من اليمين مع تنظيم الحمل.')), steps: [rich(text('نرتب المنازل تحت بعضها.')), rich(text('نبدأ بالآحاد ونتابع لليسار، مع إضافة الحمل في عموده.')), rich(text('إذا تجاوز مجموع منزلة تسعة ننقل عشرة إلى المنزلة التالية.'))], finalAnswer: rich(text('المحاذاة، البدء بالآحاد، إضافة الحمل في كل عمود، ثم نقله عند الحاجة.')) },
    originalityNote: 'يرتب إجراءات الخوارزمية العمودية بدلاً من إعطاء حاصل جمع أو نسخ تسلسل كتابي محدد.',
  }),
  q(9, {
    type: 'matching', difficulty: 'medium',
    prompt: rich(text('طابق عملية الطرح مع معادلة التحقق بالجمع.')),
    concepts: ['inverse-check', 'subtraction-algorithm'], skills: ['form-inverse-check-equation'], sourceConcepts: ['inverse-operations-and-checking'],
    left: [option('q09-l1', math('61,240−18,375=42,865')), option('q09-l2', math('50,603−27,184=23,419')), option('q09-l3', math('73,510−46,925=26,585'))],
    right: [option('q09-r1', math('23,419+27,184=50,603')), option('q09-r2', math('26,585+46,925=73,510')), option('q09-r3', math('42,865+18,375=61,240'))],
    answer: [{ leftId: 'q09-l1', rightId: 'q09-r3' }, { leftId: 'q09-l2', rightId: 'q09-r1' }, { leftId: 'q09-l3', rightId: 'q09-r2' }],
    solution: { idea: rich(text('نضيف الفرق إلى المطروح، ويجب أن نستعيد المطروح منه.')), steps: [rich(math('42,865+18,375=61,240')), rich(math('23,419+27,184=50,603')), rich(math('26,585+46,925=73,510'))], finalAnswer: rich(text('كل عملية تطابق معادلة التحقق التي تستعيد مطروحها منها.')) },
    originalityNote: 'مطابقة ثلاث عمليات مع تحققها العكسي، ما يتطلب الحفاظ على هوية الأعداد لا مجرد اختيار أي جمع.',
  }),
  q(10, {
    type: 'multi-select', difficulty: 'medium',
    prompt: rich(text('إذا كان '), math('84,250−39,680=44,570'), text('، فاختر كل مساواة تصلح للتحقق من الناتج.')),
    concepts: ['inverse-check', 'subtraction-algorithm'], skills: ['verify-subtraction-in-two-ways'], sourceConcepts: ['inverse-operations-and-checking'],
    options: [option('q10-a', math('44,570+39,680=84,250')), option('q10-b', math('84,250−44,570=39,680')), option('q10-c', math('39,680+44,570=74,250')), option('q10-d', math('44,570−39,680=4,890'))],
    answer: ['q10-a', 'q10-b'],
    solution: { idea: rich(text('يمكن استعادة المطروح منه بجمع الفرق والمطروح أو استعادة المطروح بطرح الفرق من المطروح منه.')), steps: [rich(text('الخيار الأول يعيد '), math('84,250'), text(' بالجمع.')), rich(text('والثاني يعيد '), math('39,680'), text(' بطرح الفرق.')), rich(text('الخياران الآخران لا يعيدان أحد العددين المطلوبين.'))], finalAnswer: rich(text('المساواتان الأولى والثانية صحيحتان.')) },
    originalityNote: 'يختار طريقتي التحقق العكسيتين من أربعة علاقات مختلفة حول عملية جديدة، لا من أعداد السؤال الختامي.',
  }),
  q(11, {
    type: 'single-choice', difficulty: 'medium',
    prompt: rich(text('ما العدد الذي يكمل المعادلة '), math('□+18,750=63,200'), text('؟')),
    concepts: ['missing-number', 'addition-and-subtraction-applications'], skills: ['find-missing-addend', 'use-subtraction-inverse'], sourceConcepts: ['missing-digit-and-number-puzzles', 'inverse-operations-and-checking'],
    options: [option('q11-a', math('44,450')), option('q11-b', math('81,950')), option('q11-c', math('45,450')), option('q11-d', math('44,550'))],
    answer: 'q11-a',
    solution: { idea: rich(text('نجد الحد المجهول بطرح الحد المعلوم من المجموع.')), steps: [rich(math('63,200−18,750=44,450')), rich(text('والتحقق: '), math('44,450+18,750=63,200'), text('.'))], finalAnswer: rich(math('44,450')) },
    originalityNote: 'لغز حد مفقود يُحل بعكس الجمع ثم يتحقق بإعادته؛ لا يستخدم العدد المجهول أو الإطار الوارد في الاختبار السابق.',
  }),
  q(12, {
    type: 'error-analysis', difficulty: 'medium',
    prompt: rich(text('طرح طالب '), math('18,479'), text(' من '), math('50,206'), text('، فكتب '), math('48,273'), text(' لأنه طرح الرقم الأصغر من الأكبر في كل عمود دون استلاف. اختر التشخيص والتصحيح.')),
    concepts: ['subtraction-algorithm', 'regrouping'], skills: ['diagnose-no-borrowing-error', 'correct-subtraction-across-zeroes'], sourceConcepts: ['column-subtraction-and-borrowing'],
    coverage: { commonErrors: ['subtract-larger-digit-without-borrowing'] },
    studentWork: rich(math('50,206−18,479=48,273')),
    diagnoses: [optionText('q12-d1', 'عكس الأرقام في الأعمدة التي لا تكفي فيها الخانة ولم يستلف'), optionText('q12-d2', 'جمع المطروح مع المطروح منه')],
    corrections: [option('q12-c1', math('31,727')), option('q12-c2', math('48,273'))],
    answer: { diagnosisId: 'q12-d1', correctionId: 'q12-c1' },
    solution: { idea: rich(text('لا يجوز عكس ترتيب الطرح داخل العمود؛ نعيد التجميع من منزلة أعلى أولاً.')), steps: [rich(text('في الآحاد لا يمكن حساب '), math('6−9'), text(' دون استلاف.')), rich(text('بعد الاستلاف الصحيح عبر الأصفار نطرح المنازل بالترتيب.')), rich(math('50,206−18,479=31,727'))], finalAnswer: rich(math('31,727')), commonError: rich(text('طرح الأصغر من الأكبر في كل عمود على حدة بدلاً من الحفاظ على ترتيب المطروح منه والمطروح.')) },
    originalityNote: 'يشخص قاعدة خاطئة في الاستلاف عبر أصفار ضمن عمود طرح جديد؛ لا يعيد عملية تعويض أو مثالاً مصوراً من الاختبار السابق.',
  }),
  q(13, {
    type: 'true-false', difficulty: 'medium',
    prompt: rich(text('المعادلة '), math('94,000−38,725=55,275'), text(' متحققة، لأن '), math('55,275+38,725=94,000'), text('.')),
    concepts: ['inverse-check', 'subtraction-algorithm'], skills: ['check-subtraction-result'], sourceConcepts: ['inverse-operations-and-checking'],
    answer: true,
    solution: { idea: rich(text('التحقق يعيد العدد الأصلي بعملية الجمع العكسية.')), steps: [rich(math('55,275+38,725=94,000')), rich(text('إذن الفرق المقترح يعيد المطروح منه تماماً.'))], finalAnswer: rich(text('صحيح؛ الطرح متحقق.')) },
    originalityNote: 'يستخدم معادلة تحقق مكتملة في صورة حكم منطقي، لا مسألة حساب مفتوحة من الاختبار النهائي.',
  }),
  q(14, {
    type: 'numeric', difficulty: 'advanced',
    prompt: rich(text('احسب مجموع الحدود الثلاثة '), math('86,007'), text(' و'), math('17,895'), text(' و'), math('42,103'), text('.')),
    concepts: ['addition-algorithm', 'regrouping'], skills: ['add-three-multi-digit-addends', 'verify-addition-by-reordering'], sourceConcepts: ['column-addition-and-carrying', 'inverse-operations-and-checking'],
    answer: { expected: '146005', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نجمع الأعداد الثلاثة في أعمدة واحدة، ونضم الحمل إلى مجموع المنزلة التالية.')), steps: [rich(math('86,007+17,895=103,902')), rich(text('ثم نضيف الحد الثالث: '), math('103,902+42,103=146,005'), text('.')), rich(text('يمكن إعادة الجمع بترتيب آخر للتأكد من ثبات المجموع.'))], finalAnswer: rich(math('146,005')) },
    originalityNote: 'يجمع ثلاثة حدود جديدة في عملية واحدة مع عبور إلى ست خانات؛ يختلف عن جمع الحدين المجرد في الاختبار الختامي.',
  }),
  q(15, {
    type: 'error-analysis', difficulty: 'advanced',
    prompt: rich(text('أوجد طالب '), math('66,708+28,495=85,203'), text('، وقد نسي نقل حمل الآلاف إلى عشرات الآلاف. اختر التشخيص والتصحيح.')),
    concepts: ['addition-algorithm', 'regrouping'], skills: ['diagnose-final-carry-omission', 'correct-large-sum'], sourceConcepts: ['column-addition-and-carrying'],
    coverage: { commonErrors: ['omit-carry-to-leading-place'] },
    studentWork: rich(math('66,708+28,495=85,203')),
    diagnoses: [optionText('q15-d1', 'أهمل الحمل من عمود الآلاف إلى عشرات الآلاف'), optionText('q15-d2', 'أضاف الحمل مرتين في عمود الآحاد')],
    corrections: [option('q15-c1', math('95,203')), option('q15-c2', math('85,203'))],
    answer: { diagnosisId: 'q15-d1', correctionId: 'q15-c1' },
    solution: { idea: rich(text('ينبغي نقل الحمل من كل عمود إلى العمود التالي حتى لو أصبح الناتج أكبر من عدد خانات الحدين.')), steps: [rich(text('في الآلاف ينتج '), math('6+8+1=15'), text(' آلاف؛ نكتب 5 آلاف ونحمل عشرة آلاف.')), rich(text('نضيف الحمل إلى '), math('6+2'), text(' في عشرات الآلاف، فنحصل على 9.'))], finalAnswer: rich(math('95,203')), commonError: rich(text('نسيان آخر حمل قد يخفض المجموعة العليا بمقدار منزلة كاملة.')) },
    originalityNote: 'يركز على حمل أخير يغير خانة عشرات الآلاف في مجموع جديد؛ يختلف عن خطأ إهمال الحمل في كل الأعمدة.',
  }),
  q(16, {
    type: 'numeric', difficulty: 'advanced',
    prompt: rich(text('كان في سجلّ مستودع '), math('246,850'), text(' وحدة، ثم أضيفت '), math('78,645'), text(' وحدة وأُخرجت بعد ذلك '), math('39,870'), text(' وحدة. كم وحدة بقيت؟')),
    concepts: ['addition-and-subtraction-applications', 'addition-algorithm', 'subtraction-algorithm'], skills: ['model-two-step-quantity-change', 'calculate-addition-then-subtraction'], sourceConcepts: ['select-operation-for-application', 'column-addition-and-carrying', 'column-subtraction-and-borrowing'],
    coverage: { applications: ['inventory-change'] },
    answer: { expected: '285625', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نحدّث الرصيد بعد الإضافة أولاً ثم نطرح ما أُخرج.')), steps: [rich(math('246,850+78,645=325,495')), rich(math('325,495−39,870=285,625'))], finalAnswer: rich(math('285,625'), text(' وحدة.')) },
    originalityNote: 'مسألة رصيد ذات تغيرين متتابعين في اتجاهين، بأعداد وسياق جديدين؛ لا تعيد تطبيق المزرعة أو الجمع المنفرد في الاختبار السابق.',
  }),
  q(17, {
    type: 'multi-select', difficulty: 'advanced',
    prompt: rich(text('إذا كان '), math('63,508+28,764=92,272'), text('، فاختر كل معادلة صحيحة يمكن استخدامها للتحقق من الجمع.')),
    concepts: ['addition-algorithm', 'inverse-check'], skills: ['verify-addition-by-subtraction', 'use-commutative-addition'], sourceConcepts: ['column-addition-and-carrying', 'inverse-operations-and-checking'],
    options: [option('q17-a', math('92,272−28,764=63,508')), option('q17-b', math('92,272−63,508=28,764')), option('q17-c', math('63,508−28,764=92,272')), option('q17-d', math('28,764−63,508=92,272'))],
    answer: ['q17-a', 'q17-b'],
    solution: { idea: rich(text('الطرح العكسي يستعيد أحد الحدين عند طرح الحد الآخر من المجموع.')), steps: [rich(text('نطرح الحد الثاني من المجموع فنستعيد الحد الأول: '), math('92,272−28,764=63,508'), text('.')), rich(text('ونطرح الحد الأول من المجموع فنستعيد الحد الثاني: '), math('92,272−63,508=28,764'), text('.')), rich(text('طرح أحد الحدين من الآخر لا يعيد المجموع.'))], finalAnswer: rich(text('المعادلتان الأولى والثانية صحيحتان.')) },
    originalityNote: 'يختار طريقتي التحقق من جمع جديد ذي أعداد مختلفة عن مسائل الحساب المباشر، لا سؤالاً رقمياً مكرراً أو مساواة واحدة معطاة.',
  }),
  q(18, {
    type: 'matching', difficulty: 'thinking',
    prompt: rich(text('طابق كل معادلة ذات حد مجهول مع قيمته بعد استعمال العلاقة العكسية المناسبة.')),
    concepts: ['missing-number', 'inverse-check'], skills: ['solve-missing-addend-and-subtrahend', 'solve-missing-minuend'], sourceConcepts: ['missing-digit-and-number-puzzles', 'inverse-operations-and-checking'],
    coverage: { thinking: ['distinguish-unknown-position'], applications: ['number-puzzle'] },
    left: [option('q18-l1', math('□+12,450=50,000')), option('q18-l2', math('76,300−□=28,450')), option('q18-l3', math('□−18,275=44,100'))],
    right: [option('q18-r1', math('62,375')), option('q18-r2', math('47,850')), option('q18-r3', math('37,550'))],
    answer: [{ leftId: 'q18-l1', rightId: 'q18-r3' }, { leftId: 'q18-l2', rightId: 'q18-r2' }, { leftId: 'q18-l3', rightId: 'q18-r1' }],
    solution: { idea: rich(text('يحدد موضع المجهول العملية العكسية التي تعزل قيمته.')), steps: [rich(math('50,000−12,450=37,550')), rich(math('76,300−28,450=47,850')), rich(math('44,100+18,275=62,375'))], finalAnswer: rich(text('المجهولات بالترتيب: '), math('37,550'), text('، '), math('47,850'), text('، '), math('62,375'), text('.')) },
    originalityNote: 'يجمع ثلاثة مواضع مختلفة للمجهول في إطار لغز مترابط؛ يتطلب اختيار عكس مناسب لكل معادلة لا استبدال رقم في تمرين واحد.',
  }),
  q(19, {
    type: 'error-analysis', difficulty: 'thinking',
    prompt: rich(text('في رف أول '), math('42,600'), text(' كتاباً وفي رف ثانٍ '), math('18,350'), text(' كتاباً. سُئل أمين المكتبة: «كم يزيد عدد الأول على الثاني؟» فجمع العددين. اختر التشخيص والتصحيح.')),
    concepts: ['addition-and-subtraction-applications', 'operation-choice'], skills: ['interpret-comparison-question', 'choose-subtraction-for-difference'], sourceConcepts: ['select-operation-for-application'],
    coverage: { thinking: ['choose-operation-from-comparison'], applications: ['compare-quantities'], commonErrors: ['add-instead-of-find-difference'] },
    studentWork: rich(math('42,600+18,350=60,950')),
    diagnoses: [optionText('q19-d1', 'المطلوب مقدار الزيادة، أي الفرق بين الكميتين'), optionText('q19-d2', 'كلمة «يزيد» تعني دائماً إيجاد المجموع')],
    corrections: [option('q19-c1', math('42,600−18,350=24,250')), option('q19-c2', math('42,600+18,350=60,950'))],
    answer: { diagnosisId: 'q19-d1', correctionId: 'q19-c1' },
    solution: { idea: rich(text('السؤال يطلب الفرق بين الكميتين لا مجموعهما.')), steps: [rich(text('نحدد الأكبر والأصغر ونطرح الأصغر من الأكبر.')), rich(math('42,600−18,350=24,250'))], finalAnswer: rich(text('يزيد عدد الكتب بمقدار '), math('24,250'), text(' كتاباً.')), commonError: rich(text('اختيار الجمع بسبب رؤية كميتين في النص، دون قراءة المطلوب النهائي.')) },
    originalityNote: 'موقف مقارنة جديد يطلب تفسير الغرض الحسابي قبل التنفيذ؛ لا يعيد مسألة متجر أو مزرعة من الاختبار الختامي.',
  }),
  q(20, {
    type: 'error-analysis', difficulty: 'thinking',
    prompt: rich(text('تحقق طالب من '), math('78,340−29,875=48,465'), text(' بحساب '), math('78,340+29,875'), text(' وقال إن هذا الجمع يجب أن يعطي الفرق. اختر التشخيص والتصحيح.')),
    concepts: ['inverse-check', 'subtraction-algorithm'], skills: ['evaluate-inverse-check-setup', 'correct-subtraction-verification'], sourceConcepts: ['inverse-operations-and-checking'],
    coverage: { thinking: ['evaluate-check-structure'], commonErrors: ['add-minuend-and-subtrahend'] },
    studentWork: rich(math('78,340+29,875=48,465')),
    diagnoses: [optionText('q20-d1', 'جمع المطروح منه والمطروح لا يعيد الفرق'), optionText('q20-d2', 'طرح الفرق من المطروح منه طريقة غير صالحة للتحقق')],
    corrections: [option('q20-c1', math('48,465+29,875=78,340')), option('q20-c2', math('78,340+29,875=108,215'))],
    answer: { diagnosisId: 'q20-d1', correctionId: 'q20-c1' },
    solution: { idea: rich(text('نضيف الفرق إلى المطروح، لا المطروح إلى المطروح منه، لاستعادة المطروح منه.')), steps: [rich(text('الجمع الذي كتبه الطالب لا يمكن أن يساوي فرق الطرح بهذه الصورة.')), rich(text('نعيد العلاقة العكسية الصحيحة: '), math('48,465+29,875=78,340'), text('.'))], finalAnswer: rich(text('التشخيص: الجمع كان بين المطروح منه والمطروح؛ والتحقق الصحيح هو '), math('48,465+29,875=78,340'), text('.')), commonError: rich(text('اختيار أعداد التحقق من دون الحفاظ على علاقة الفرق والمطروح والمطروح منه.')) },
    originalityNote: 'ينقد اختيار طرفي معادلة التحقق نفسها لا مهارة الطرح؛ يطلب تصحيح بنية العكس باستخدام أعداد مستقلة عن تدريبات الدرس.',
  }),
]

const definition = defineLessonTest({
  id: testId,
  lessonId,
  title: 'اختبار جمع وطرح الأعداد الطبيعية',
  description: rich(text('يقيس هذا الاختبار الجمع والطرح العمودي مع الحمل والاستلاف، واختيار العملية المناسبة، والتحقق بالعلاقة العكسية وحل المجاهيل.')),
  instructions: rich(text('حافظ على ترتيب المنازل عند الحساب. في مسائل الموقف اقرأ المطلوب أولاً، وفي التحقق أعد تكوين العلاقة بين المجموع أو الفرق والحدود.')),
  questions,
  sourceConcepts: [
    { id: 'column-addition-and-carrying', label: 'جمع الأعداد الطبيعية عمودياً مع إعادة التجميع والحمل', pages: [19, 20] },
    { id: 'column-subtraction-and-borrowing', label: 'طرح الأعداد الطبيعية عمودياً مع إعادة التجميع والاستلاف', pages: [20, 21] },
    { id: 'inverse-operations-and-checking', label: 'العلاقة العكسية بين الجمع والطرح والتحقق من الناتج', pages: [19, 20, 21, 22] },
    { id: 'missing-digit-and-number-puzzles', label: 'حل الأعداد أو الخانات الناقصة في معادلات الجمع والطرح', pages: [21, 22] },
    { id: 'select-operation-for-application', label: 'اختيار الجمع أو الطرح بحسب المطلوب في التطبيق', pages: [19, 21, 22] },
  ],
  conceptLabels: {
    'addition-and-subtraction-applications': 'تطبيق الجمع والطرح على كميات موصوفة',
    'addition-algorithm': 'الجمع العمودي',
    'regrouping': 'إعادة التجميع والحمل أو الاستلاف',
    'inverse-check': 'التحقق باستعمال العملية العكسية',
    'subtraction-algorithm': 'الطرح العمودي',
    'missing-number': 'المجهول في معادلة جمع أو طرح',
    'operation-choice': 'اختيار العملية من مدلول السؤال',
  },
  skillLabels: {
    'choose-operation-from-goal': 'اختيار العملية من المطلوب في المسألة',
    'count-carries-in-addition': 'عدّ انتقالات الحمل عبر أعمدة الجمع',
    'verify-subtraction-by-addition': 'التحقق من الطرح بجمع الفرق والمطروح',
    'select-operation-for-task': 'مطابقة هدف المسألة مع العملية المناسبة',
    'diagnose-missing-carry': 'تشخيص إهمال الحمل في الجمع',
    'correct-column-addition': 'تصحيح ناتج جمع عمودي',
    'subtract-with-borrowing': 'طرح عدد مع إعادة التجميع',
    'borrow-across-zeroes': 'الاستلاف عبر خانات صفرية',
    'subtract-multi-digit-numbers': 'طرح أعداد متعددة المنازل',
    'sequence-column-addition': 'ترتيب إجراءات الجمع العمودي',
    'form-inverse-check-equation': 'كتابة معادلة التحقق العكسية',
    'verify-subtraction-in-two-ways': 'التحقق من الطرح بطريقتين عكسيتين',
    'find-missing-addend': 'إيجاد حد جمع مجهول بالطرح',
    'use-subtraction-inverse': 'استخدام الطرح لعكس الجمع',
    'diagnose-no-borrowing-error': 'كشف طرح الأعمدة دون استلاف صحيح',
    'correct-subtraction-across-zeroes': 'تصحيح الطرح عند وجود أصفار',
    'check-subtraction-result': 'التحقق من عملية طرح معطاة',
    'add-across-place-boundaries': 'الجمع مع انتقال الحمل إلى مجموعة أعلى',
    'add-three-multi-digit-addends': 'جمع ثلاثة أعداد متعددة المنازل مع الحمل',
    'verify-addition-by-reordering': 'إعادة الجمع بترتيب آخر للتحقق',
    'diagnose-final-carry-omission': 'كشف إهمال الحمل في المنزلة العليا',
    'correct-large-sum': 'تصحيح مجموع متعدد المنازل',
    'model-two-step-quantity-change': 'تمثيل تغيرين متتابعين في كمية',
    'calculate-addition-then-subtraction': 'حساب الإضافة ثم الطرح في مسألة واحدة',
    'verify-addition-by-subtraction': 'التحقق من الجمع باستعمال الطرح',
    'use-commutative-addition': 'استعمال تبديل الحدين في الجمع للتحقق',
    'solve-missing-addend-and-subtrahend': 'حل مجهول حد الجمع أو المطروح',
    'solve-missing-minuend': 'إيجاد المطروح منه من الفرق والمطروح',
    'interpret-comparison-question': 'تفسير سؤال المقارنة بين كميتين',
    'choose-subtraction-for-difference': 'استخدام الطرح لإيجاد الفرق',
    'evaluate-inverse-check-setup': 'تقويم اختيار حدود معادلة التحقق',
    'correct-subtraction-verification': 'تصحيح علاقة التحقق من الطرح',
  },
  applicationLabels: {
    'combine-quantities': 'إيجاد الكل من كميتين معطاتين',
    'inventory-change': 'تحديث رصيد بعد إضافة وإخراج',
    'number-puzzle': 'حل معادلة عددية ذات حد مجهول',
    'compare-quantities': 'إيجاد مقدار الفرق بين كميتين',
  },
  thinkingLabels: {
    'distinguish-unknown-position': 'اختيار العلاقة العكسية بحسب موضع المجهول',
    'choose-operation-from-comparison': 'استنتاج العملية من صياغة مقارنة',
    'evaluate-check-structure': 'تقييم بنية التحقق لا الناتج فقط',
  },
  commonErrorLabels: {
    'omit-carry-in-addition': 'إهمال الحمل في جمع المنازل',
    'subtract-larger-digit-without-borrowing': 'عكس أرقام العمود بدلاً من الاستلاف',
    'omit-carry-to-leading-place': 'إسقاط الحمل إلى المنزلة العليا',
    'add-instead-of-find-difference': 'جمع كميتين عند طلب الفرق بينهما',
    'add-minuend-and-subtrahend': 'جمع المطروح منه والمطروح بدلاً من الفرق والمطروح للتحقق',
  },
})

export default definition
