import { defineLessonTest, lessonQuestion, math, rich, text, textOnly, type LessonQuestionDraft } from '../../lessonTestBuilder'
import type { QuestionDefinition } from '../../types'

const testId = 'lesson-angle-measurement-test'
const lessonId = 'angle-measurement'
const qid = (number: number) => `${testId}-q${String(number).padStart(2, '0')}`
const q = (number: number, draft: LessonQuestionDraft) =>
  lessonQuestion(testId, lessonId, qid(number), draft)
const option = (id: string, ...runs: Parameters<typeof rich>) => ({ id, label: rich(...runs) })
const optionText = (id: string, value: string) => ({ id, label: textOnly(value) })

const questions: QuestionDefinition[] = [
  q(1, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('في الترميز '), math('∠PQR'), text('، أي حرف يمثل رأس الزاوية؟')),
    concepts: ['angle-naming', 'angle-vertex'], skills: ['identify-middle-letter-vertex'], sourceConcepts: ['angle-names-and-vertex'],
    options: [option('q01-a', math('P')), option('q01-b', math('Q')), option('q01-c', math('R')), optionText('q01-d', 'لا يمكن تحديده')],
    answer: 'q01-b',
    solution: { idea: rich(text('عند تسمية الزاوية بثلاثة أحرف يكون حرف الرأس في الوسط.')), steps: [rich(text('نقرأ الحروف بالترتيب '), math('P,Q,R'), text('.')), rich(text('الحرف الأوسط هو '), math('Q'), text('.'))], finalAnswer: rich(text('رأس الزاوية هو '), math('Q'), text('.')) },
    originalityNote: 'يفحص قاعدة الحرف الأوسط باستخدام تسمية جديدة، لا ينسخ أسماء الزوايا أو النقاط الواردة في أمثلة الكتاب.',
  }),
  q(2, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('إذا بدأ نصفا مستقيمين من نقطة واحدة، فإن هذه النقطة المشتركة هي رأس الزاوية التي يصنعانها.')),
    concepts: ['angle-rays-and-vertex'], skills: ['recognize-common-endpoint'], sourceConcepts: ['angle-formation'],
    answer: true,
    solution: { idea: rich(text('تتشكل الزاوية من التقاء نصفي مستقيمين لهما نقطة بداية مشتركة.')), steps: [rich(text('نقطة البداية المشتركة هي الرأس.')), rich(text('ويمثل كل نصف مستقيم ضلعاً من ضلعي الزاوية.'))], finalAnswer: rich(text('صحيح.')) },
    originalityNote: 'صياغة تعريفية مستقلة تربط نقطتي البداية بالرأس والضلعين، لا سؤال تسمية أو قياس مباشر.',
  }),
  q(3, {
    type: 'matching', difficulty: 'basic',
    prompt: rich(text('طابق قياس كل زاوية مع نوعها.')),
    concepts: ['angle-classification'], skills: ['classify-angle-by-measure'], sourceConcepts: ['angle-types'],
    left: [option('q03-l1', math('50°')), option('q03-l2', math('90°')), option('q03-l3', math('110°')), option('q03-l4', math('180°'))],
    right: [optionText('q03-r1', 'حادة'), optionText('q03-r2', 'قائمة'), optionText('q03-r3', 'منفرجة'), optionText('q03-r4', 'مستقيمة')],
    answer: [{ leftId: 'q03-l1', rightId: 'q03-r1' }, { leftId: 'q03-l2', rightId: 'q03-r2' }, { leftId: 'q03-l3', rightId: 'q03-r3' }, { leftId: 'q03-l4', rightId: 'q03-r4' }],
    solution: { idea: rich(text('نقارن القياس بالزاوية القائمة '), math('90°'), text(' والمستقيمة '), math('180°'), text('.')), steps: [rich(math('50°<90°'), text('؛ حادة.')), rich(math('90°'), text('؛ قائمة.')), rich(text('بين '), math('90°'), text(' و'), math('180°'), text('؛ منفرجة.')), rich(math('180°'), text('؛ مستقيمة.'))], finalAnswer: rich(math('50°'), text(' حادة؛ '), math('90°'), text(' قائمة؛ '), math('110°'), text(' منفرجة؛ '), math('180°'), text(' مستقيمة.')) },
    originalityNote: 'مطابقة أربع قياسات مع التصنيفات الحدية والداخلية؛ لا تعيد تصنيف الرسومات الأربعة بالحروف في صفحة الانطلاق.',
  }),
  q(4, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('إذا بقي اتجاه ضلعي زاوية وفتحتها كما هما، فإن إطالة أحد الضلعين لا تغيّر قياس الزاوية.')),
    concepts: ['angle-measure-and-ray-length'], skills: ['distinguish-angle-measure-from-side-length'], sourceConcepts: ['angle-measure-and-length'],
    coverage: { applications: ['antenna-length-application'] },
    answer: true,
    solution: { idea: rich(text('قياس الزاوية يعتمد على اتجاه الضلعين والفتحة بينهما، لا على طول الضلعين.')), steps: [rich(text('إطالة ضلع على الاتجاه نفسه لا تغيّر فتحة الزاوية.')), rich(text('لذلك يبقى القياس كما هو.'))], finalAnswer: rich(text('صحيح.')) },
    originalityNote: 'يعالج ثبات القياس عند تغيير طول ضلع واحد من دون تغيير اتجاهه؛ ليس سؤالاً عددياً أو عن قراءة تدريج.',
  }),
  q(5, {
    type: 'multi-select', difficulty: 'basic',
    prompt: rich(text('اختر كل خطوة صحيحة من خطوات استعمال المنقلة لقياس زاوية.')),
    concepts: ['protractor-measurement'], skills: ['prepare-protractor-correctly'], sourceConcepts: ['protractor-and-measurement'],
    options: [optionText('q05-a', 'ضع مركز المنقلة على رأس الزاوية'), optionText('q05-b', 'طابق خط الصفر مع أحد الضلعين'), optionText('q05-c', 'ابدأ من التدريج الذي يحمل الصفر المطابق لضلع البداية'), optionText('q05-d', 'اقرأ رقماً من التدريج الآخر حتى لو لم يبدأ من الصفر المطابق')],
    answer: ['q05-a', 'q05-b', 'q05-c'],
    solution: { idea: rich(text('القراءة الصحيحة تتطلب تثبيت المركز ومحاذاة خط الصفر واختيار التدريج الموافق.')), steps: [rich(text('يوضع المركز عند الرأس.')), rich(text('يطابق خط الصفر ضلع البداية.')), rich(text('يقرأ الضلع الآخر على التدريج الذي بدأ من ذلك الصفر.'))], finalAnswer: rich(text('الخطوات الأولى والثانية والثالثة صحيحة؛ الرابعة خطأ.')) },
    originalityNote: 'يختبر مكونات الإعداد الصحيحة في اختيار متعدد قبل القراءة؛ لا يعيد سؤال الاختبار الختامي عن صفر من جهة محددة.',
  }),
  q(6, {
    type: 'ordering', difficulty: 'basic',
    prompt: rich(text('رتّب أعمال قياس زاوية بالمنقلة من الإعداد حتى التحقق.')),
    concepts: ['protractor-measurement'], skills: ['sequence-angle-measurement'], sourceConcepts: ['protractor-and-measurement'],
    items: [optionText('q06-a', 'اقرأ التدريج عند الضلع الآخر'), optionText('q06-b', 'ضع مركز المنقلة عند الرأس'), optionText('q06-c', 'طابق خط الصفر مع ضلع البداية'), optionText('q06-d', 'تحقق من معقولية النتيجة بنوع الزاوية')],
    answer: ['q06-b', 'q06-c', 'q06-a', 'q06-d'],
    solution: { idea: rich(text('تبدأ القراءة بتثبيت المنقلة، ثم المحاذاة، ثم اختيار التدريج، وتنتهي بفحص معقولية النتيجة.')), steps: [rich(text('ضع المركز عند الرأس.')), rich(text('طابق الصفر مع ضلع البداية.')), rich(text('اقرأ التدريج عند الضلع الثاني ثم قارنه بنوع الزاوية.'))], finalAnswer: rich(text('المركز، ثم الصفر، ثم القراءة، ثم التحقق.')) },
    originalityNote: 'يرتب بروتوكول القياس كاملاً بصياغة جديدة، بدلاً من ترتيب خطوات رسم زاوية معلومة القياس.',
  }),
  q(7, {
    type: 'single-choice', difficulty: 'medium',
    prompt: rich(text('وُضع ضلع البداية على خط المنقلة الذي يحمل '), math('0°'), text(' من جهة اليمين، وقطع الضلع الآخر التدريج المطابق عند '), math('65°'), text('. ما القياس الذي يجب قراءته؟')),
    concepts: ['protractor-scales', 'protractor-measurement'], skills: ['choose-scale-aligned-to-zero'], sourceConcepts: ['protractor-and-measurement'],
    options: [option('q07-a', math('65°')), option('q07-b', math('115°')), option('q07-c', math('90°')), option('q07-d', math('180°'))],
    answer: 'q07-a',
    solution: { idea: rich(text('اختيار التدريج يبدأ من الصفر الذي يطابق ضلع البداية.')), steps: [rich(text('المعطى أن ضلع البداية على جهة الصفر في اليمين.')), rich(text('القراءة على التدريج الموافق لضلع البداية هي '), math('65°'), text('.')), rich(text('لا نختار العدد المقابل على التدريج المعاكس.'))], finalAnswer: rich(math('65°')) },
    originalityNote: 'يطلب قراءة تدريج موافق لجهة الصفر في وصف جديد، لا يعيد بند الاختبار النهائي عن اختيار صفر يمين المنقلة.',
  }),
  q(8, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('زاويتان متجاورتان تقسمان زاوية أكبر؛ قياس الأولى '), math('35°'), text(' والثانية '), math('50°'), text('. ما قياس الزاوية الأكبر؟')),
    concepts: ['angle-additivity'], skills: ['add-adjacent-angle-measures'], sourceConcepts: ['adjacent-angle-addition'],
    answer: { expected: '85', format: 'integer', unitPolicy: { kind: 'required', acceptedUnits: ['°', 'degree', 'degrees', 'درجة', 'درجات'] } },
    solution: { idea: rich(text('عندما تتجاور الزاويتان على فتحة أكبر، نجمع قياسيهما.')), steps: [rich(math('35°+50°=85°')), rich(text('المجموع أقل من '), math('90°'), text('، لذا يمكن التحقق بأنه قياس زاوية حادة.'))], finalAnswer: rich(math('85°')) },
    originalityNote: 'مجموع لزاويتين معطاتين بقيم جديدة ومجموع غير مستخدم في المثال المدرسي؛ يختبر جمع الفتحتين لا حفظ النتيجة 90°.',
  }),
  q(9, {
    type: 'matching', difficulty: 'medium',
    prompt: rich(text('طابق كل جزء من الزاوية مع معناه الهندسي.')),
    concepts: ['angle-rays-and-vertex', 'angle-vertex'], skills: ['distinguish-vertex-and-arms'], sourceConcepts: ['angle-formation', 'angle-names-and-vertex'],
    left: [optionText('q09-l1', 'الرأس'), optionText('q09-l2', 'ضلعا الزاوية'), optionText('q09-l3', 'المنطقة الداخلية'), optionText('q09-l4', 'قياس الزاوية')],
    right: [optionText('q09-r1', 'نقطة البداية المشتركة'), optionText('q09-r2', 'نصفا المستقيمين المنطلقان من الرأس'), optionText('q09-r3', 'الفتحة المحصورة بين الضلعين'), optionText('q09-r4', 'مقدار الفتحة معبراً عنه بالدرجات')],
    answer: [{ leftId: 'q09-l1', rightId: 'q09-r1' }, { leftId: 'q09-l2', rightId: 'q09-r2' }, { leftId: 'q09-l3', rightId: 'q09-r3' }, { leftId: 'q09-l4', rightId: 'q09-r4' }],
    solution: { idea: rich(text('تتكون الزاوية من رأس وضلعين وتوصف بفتحتها وقياسها.')), steps: [rich(text('الرأس نقطة الالتقاء، والضلعان نصفا مستقيمين.')), rich(text('المنطقة الداخلية هي الفتحة، أما القياس فيعبر عن مقدارها بالدرجات.'))], finalAnswer: rich(text('الرأس: نقطة البداية؛ الضلعان: نصفا المستقيم؛ الداخلية: الفتحة؛ القياس: مقدارها بالدرجات.')) },
    originalityNote: 'مطابقة لأربعة مصطلحات وتعريفاتها، تكمل سؤال تسمية الرأس لكنها لا تعيد نفس بنية اختيار حرف من رمز.',
  }),
  q(10, {
    type: 'error-analysis', difficulty: 'medium',
    prompt: rich(text('رسم طالب زاوية رأسها '), math('B'), text(' وضلعَاها '), math('[BA)'), text(' و'), math('[BC)'), text('، ثم سماها '), math('∠ABC'), text(' على أن '), math('A'), text(' هو الرأس. اختر التشخيص والتصحيح.')),
    concepts: ['angle-naming', 'angle-vertex'], skills: ['diagnose-vertex-position-in-name', 'correct-angle-notation'], sourceConcepts: ['angle-names-and-vertex'],
    coverage: { commonErrors: ['vertex-not-middle-letter'] },
    studentWork: rich(math('∠ABC'), text('؛ الرأس '), math('A')),
    diagnoses: [optionText('q10-d1', 'الحرف الأوسط B هو الرأس، وليس A'), optionText('q10-d2', 'الحرف الأول في الاسم الثلاثي هو الرأس دائماً')],
    corrections: [option('q10-c1', math('∠ABC'), text(' أو '), math('∠CBA')), option('q10-c2', math('∠BAC'))],
    answer: { diagnosisId: 'q10-d1', correctionId: 'q10-c1' },
    solution: { idea: rich(text('في التسمية بثلاثة أحرف يجب أن يقع الرأس في الوسط.')), steps: [rich(text('الضلعان يلتقيان عند '), math('B'), text('، إذن الرأس '), math('B'), text('.')), rich(text('الاسمان اللذان يضعان '), math('B'), text(' في الوسط هما '), math('∠ABC'), text(' و'), math('∠CBA'), text('.'))], finalAnswer: rich(text('التشخيص: B هو الرأس؛ والتصحيح '), math('∠ABC'), text(' أو '), math('∠CBA'), text('.')), commonError: rich(text('اختيار الحرف الأول أو الأخير رأساً، بدلاً من الحرف الأوسط.')) },
    originalityNote: 'يصحح تسمية زاوية بمعطيات ضلعين ورأس معلوم؛ يختلف عن إعادة تعريف الترتيب من دون موقف خطأ.',
  }),
  q(11, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('جزء من زاوية مستقيمة قياسه '), math('65°'), text('. ما قياس الجزء المتبقي؟')),
    concepts: ['angle-additivity', 'straight-angle'], skills: ['find-complement-within-straight-angle'], sourceConcepts: ['angle-types', 'adjacent-angle-addition'],
    answer: { expected: '115', format: 'integer', unitPolicy: { kind: 'required', acceptedUnits: ['°', 'degree', 'degrees', 'درجة', 'درجات'] } },
    solution: { idea: rich(text('الزاوية المستقيمة قياسها '), math('180°'), text('، والجزآن المتجاوران يكمل أحدهما الآخر إلى هذا القياس.')), steps: [rich(math('180°−65°=115°')), rich(text('نتحقق أن المجموع '), math('65°+115°'), text(' يساوي '), math('180°'), text('.'))], finalAnswer: rich(math('115°')) },
    originalityNote: 'يستنتج جزءاً متبقياً من زاوية مستقيمة باستخدام قيمة معطاة جديدة؛ ليس قراءة زاوية أو نسخ أحد قياسات صفحات التمرين.',
  }),
  q(12, {
    type: 'true-false', difficulty: 'medium',
    prompt: rich(text('الزاوية التي قياسها '), math('125°'), text(' منفرجة؛ لأنها أكبر من القائمة وأصغر من المستقيمة.')),
    concepts: ['angle-classification'], skills: ['justify-obtuse-classification'], sourceConcepts: ['angle-types'],
    answer: true,
    solution: { idea: rich(text('تقع الزاوية المنفرجة بين '), math('90°'), text(' و'), math('180°'), text('.')), steps: [rich(math('90°<125°<180°')), rich(text('إذن القياس ضمن مجال الزوايا المنفرجة.'))], finalAnswer: rich(text('صحيح؛ هي منفرجة.')) },
    originalityNote: 'يطلب تبرير التصنيف بالمجال العددي عند قيمة جديدة، لا تصنيف زاوية مرسومة بالاسم نفسه في الكتاب.',
  }),
  q(13, {
    type: 'multi-select', difficulty: 'medium',
    prompt: rich(text('أراد طالب رسم زاوية قياسها '), math('60°'), text(' من شعاع بداية معلوم. اختر جميع الخطوات الضرورية الصحيحة.')),
    concepts: ['angle-construction', 'protractor-measurement'], skills: ['sequence-protractor-drawing-actions', 'mark-angle-measure'], sourceConcepts: ['draw-angle-with-protractor'],
    options: [optionText('q13-a', 'ضع مركز المنقلة عند رأس الشعاع'), optionText('q13-b', 'حاذ خط الصفر مع شعاع البداية'), option('q13-c', text('ضع علامة عند القراءة '), math('60°'), text(' على التدريج الموافق للصفر')), optionText('q13-d', 'صل العلامة بالرأس لتكوين الضلع الثاني'), option('q13-e', text('غيّر طول شعاع البداية كي تتغير الزاوية إلى '), math('60°'))],
    answer: ['q13-a', 'q13-b', 'q13-c', 'q13-d'],
    solution: { idea: rich(text('الرسم يستعمل الرأس وخط الصفر والقياس لتحديد اتجاه الضلع الثاني.')), steps: [rich(text('ثبّت المركز عند الرأس وطابق الصفر مع شعاع البداية.')), rich(text('علّم موضع '), math('60°'), text(' على التدريج الموافق.')), rich(text('ارسم من الرأس عبر العلامة الضلع الثاني؛ لا يحدد طول الشعاع قيمة الزاوية.'))], finalAnswer: rich(text('الخطوات الأولى إلى الرابعة لازمة؛ الخامسة غير صحيحة.')) },
    originalityNote: 'يقيس خطة رسم زاوية جديدة من شعاع معلوم مع استبعاد تغيير الطول، لا يكرر رسم زاوية الصفحة 26 نفسها.',
  }),
  q(14, {
    type: 'error-analysis', difficulty: 'advanced',
    prompt: rich(text('وُضع خط البداية عند تدريج '), math('0°'), text(' على يمين المنقلة، وقطع الضلع الآخر خطي التدريج عند '), math('35°'), text(' و'), math('145°'), text('. قرأ سامي '), math('145°'), text(' من التدريج المعاكس. اختر التشخيص والتصحيح.')),
    concepts: ['protractor-scales', 'protractor-measurement'], skills: ['diagnose-reversed-protractor-scale', 'select-matching-zero'], sourceConcepts: ['protractor-and-measurement'],
    coverage: { commonErrors: ['read-opposite-protractor-scale'] },
    studentWork: rich(math('0°'), text(' عند اليمين؛ القراءة '), math('145°')),
    diagnoses: [optionText('q14-d1', 'اختار تدريجاً لا يبدأ من الصفر الذي يطابق خط البداية'), optionText('q14-d2', 'استخدم المركز عند رأس الزاوية')],
    corrections: [option('q14-c1', math('35°')), option('q14-c2', math('145°'))],
    answer: { diagnosisId: 'q14-d1', correctionId: 'q14-c1' },
    solution: { idea: rich(text('عند وجود تدريجين نقرأ من الصفر المحاذي لضلع البداية.')), steps: [rich(text('خط البداية عند الصفر على اليمين.')), rich(text('القراءة '), math('35°'), text(' هي التي تبدأ من هذا الصفر؛ أما '), math('145°'), text(' فتبدأ من الطرف المقابل.'))], finalAnswer: rich(text('التشخيص: اختيار التدريج المقابل؛ القياس الصحيح '), math('35°'), text('.')), commonError: rich(text('قراءة الرقم المقابل على تدريج آخر بدلاً من تتبع الصفر المحاذي.')) },
    originalityNote: 'يحلل قراءة مزدوجة محددة ويستند إلى موضع الصفر، مع قيم مختلفة عن زاوية المثال والاختبار الختامي.',
  }),
  q(15, {
    type: 'numeric', difficulty: 'advanced',
    prompt: rich(text('تتكون زاوية أكبر من زاويتين متجاورتين قياساهما '), math('35°'), text(' و'), math('60°'), text('. ما قياس الزاوية الأكبر؟')),
    concepts: ['angle-additivity'], skills: ['add-adjacent-angle-measures', 'check-angle-classification'], sourceConcepts: ['adjacent-angle-addition', 'angle-types'],
    answer: { expected: '95', format: 'integer', unitPolicy: { kind: 'required', acceptedUnits: ['°', 'degree', 'degrees', 'درجة', 'درجات'] } },
    solution: { idea: rich(text('نجمع قياسي الجزأين، ثم نتحقق من نوع الزاوية الناتجة.')), steps: [rich(math('35°+60°=95°')), rich(text('والناتج أكبر من '), math('90°'), text(' وأصغر من '), math('180°'), text('، لذلك هو منفرج.'))], finalAnswer: rich(math('95°')) },
    originalityNote: 'تركيب جمع قياسين جديدين مع تصنيف الناتج؛ يختلف عن جمع 60° و30° في تدريب الصفحة 28.',
  }),
  q(16, {
    type: 'ordering', difficulty: 'advanced',
    prompt: rich(text('رتّب خطوات رسم زاوية معلومة القياس باستعمال المنقلة.')),
    concepts: ['angle-construction', 'protractor-measurement'], skills: ['sequence-angle-construction'], sourceConcepts: ['draw-angle-with-protractor'],
    items: [optionText('q16-a', 'علّم النقطة عند القياس المطلوب على التدريج الصحيح'), optionText('q16-b', 'ارسم شعاع البداية وحدد رأسه'), optionText('q16-c', 'ضع المركز عند الرأس وحاذ الصفر مع الشعاع'), optionText('q16-d', 'صل الرأس بالنقطة لتكوين الشعاع الثاني')],
    answer: ['q16-b', 'q16-c', 'q16-a', 'q16-d'],
    solution: { idea: rich(text('يبدأ الرسم بإنشاء ضلع معلوم، ثم تستعمل المنقلة لتعيين اتجاه الضلع الآخر.')), steps: [rich(text('ارسم شعاع البداية وحدد الرأس.')), rich(text('حاذ مركز المنقلة وخط الصفر.')), rich(text('ضع العلامة عند القياس المطلوب، ثم صلها بالرأس.'))], finalAnswer: rich(text('شعاع ورأس، ثم محاذاة المنقلة، ثم علامة، ثم الشعاع الثاني.')) },
    originalityNote: 'يرتب إنشاء زاوية جديدة من شعاع البداية، ويميزه عن ترتيب إجراءات القياس فقط في السؤال السابق.',
  }),
  q(17, {
    type: 'numeric', difficulty: 'advanced',
    prompt: rich(text('ما الفرق بين قياس الزاوية المستقيمة وقياس زاوية مقدارها '), math('127°'), text('؟')),
    concepts: ['straight-angle', 'angle-additivity'], skills: ['compare-measures-with-straight-angle'], sourceConcepts: ['angle-types', 'adjacent-angle-addition'],
    answer: { expected: '53', format: 'integer', unitPolicy: { kind: 'required', acceptedUnits: ['°', 'degree', 'degrees', 'درجة', 'درجات'] } },
    solution: { idea: rich(text('الزاوية المستقيمة تساوي '), math('180°'), text('، فنطرح القياس المعطى منها.')), steps: [rich(math('180°−127°=53°')), rich(text('والفرق هو الجزء الذي يكملها إلى زاوية مستقيمة.'))], finalAnswer: rich(math('53°')) },
    originalityNote: 'يقارن قياساً معطى بالزاوية المستقيمة لإيجاد الفرق؛ يستخدم قياساً غير وارد في الاختبار الختامي أو تمارين الرسم.',
  }),
  q(18, {
    type: 'matching', difficulty: 'thinking',
    prompt: rich(text('في زاوية رأسها '), math('O'), text('، تقع النقطة '), math('X'), text(' بين الضلعين، وتقع النقطة '), math('B'), text(' خارج الفتحة. طابق كل وصف بالنقطة المناسبة.')),
    concepts: ['inside-and-outside-angle'], skills: ['classify-point-relative-to-angle'], sourceConcepts: ['inside-and-outside-angle'],
    coverage: { thinking: ['reason-about-angle-region'] },
    left: [optionText('q18-l1', 'النقطة تقع بين الضلعين داخل الفتحة'), optionText('q18-l2', 'النقطة تقع خارج الفتحة على الجهة الأخرى من أحد الضلعين'), optionText('q18-l3', 'النقطة هي نقطة البداية المشتركة للضلعين')],
    right: [option('q18-r1', math('X')), option('q18-r2', math('B')), option('q18-r3', math('O'))],
    answer: [{ leftId: 'q18-l1', rightId: 'q18-r1' }, { leftId: 'q18-l2', rightId: 'q18-r2' }, { leftId: 'q18-l3', rightId: 'q18-r3' }],
    solution: { idea: rich(text('الموقع داخل الزاوية يقع بين ضلعيها، أما الرأس فهو نقطة الالتقاء المشتركة.')), steps: [rich(text('X تقع بين الضلعين، وB خارج الفتحة.')), rich(text('O هي نقطة البداية المشتركة، أي الرأس.'))], finalAnswer: rich(text('داخل: X؛ خارج: B؛ الرأس: O.')) },
    originalityNote: 'يحلل ثلاثة أوصاف موضعية في زاوية واحدة، مستنداً إلى مفهوم الداخل والخارج والرأس لا إلى قياس أو تسمية فقط.',
  }),
  q(19, {
    type: 'error-analysis', difficulty: 'thinking',
    prompt: rich(text('وضع طالب مركز المنقلة عند الرأس، لكنه ترك خط الصفر بعيداً عن ضلع البداية ثم قرأ '), math('75°'), text(' من تدريج يبدأ من الطرف الآخر. اختر التشخيص والتصحيح.')),
    concepts: ['protractor-measurement', 'protractor-scales'], skills: ['evaluate-protractor-alignment', 'correct-scale-reading'], sourceConcepts: ['protractor-and-measurement'],
    coverage: { thinking: ['evaluate-measurement-procedure'], commonErrors: ['zero-not-aligned-with-starting-ray'] },
    studentWork: rich(text('المركز صحيح؛ الصفر غير محاذٍ؛ القراءة المعلنة '), math('75°')),
    diagnoses: [optionText('q19-d1', 'المركز وحده لا يكفي؛ يجب محاذاة الصفر مع ضلع البداية قبل القراءة'), optionText('q19-d2', 'وضع المركز عند الرأس يجعل أي تدريج صالحاً')],
    corrections: [optionText('q19-c1', 'حاذ خط الصفر أولاً ثم اقرأ التدريج الذي يبدأ منه'), option('q19-c2', text('اقرأ '), math('75°'), text(' من التدريج الأقرب بصرف النظر عن الصفر'))],
    answer: { diagnosisId: 'q19-d1', correctionId: 'q19-c1' },
    solution: { idea: rich(text('القراءة تعتمد على المركز والمحاذاة معاً، ثم على اختيار التدريج الموافق.')), steps: [rich(text('وضع المركز صحيح لكنه لا يحدد بداية القياس وحده.')), rich(text('يجب مطابقة الصفر مع ضلع البداية ثم قراءة الضلع الآخر من التدريج نفسه.'))], finalAnswer: rich(text('التشخيص: نقص محاذاة الصفر؛ والتصحيح: حاذ الصفر أولاً ثم اقرأ.')), commonError: rich(text('الاعتقاد أن تمركز المنقلة وحده يضمن القياس الصحيح حتى مع عدم محاذاة خط الصفر.')) },
    originalityNote: 'يقيم سبباً إجرائياً مركباً رغم صحة تمركز المنقلة، ويختلف عن خطأ قراءة التدريج المعاكس بعد محاذاة صحيحة.',
  }),
  q(20, {
    type: 'single-choice', difficulty: 'thinking',
    prompt: rich(text('زاوية مقدارها '), math('128°'), text(' قُسمت إلى جزأين متجاورين، قياس أحدهما '), math('50°'), text('. ما قياس الجزء الآخر ونوعه؟')),
    concepts: ['angle-additivity', 'angle-classification'], skills: ['combine-and-classify-angle'], sourceConcepts: ['adjacent-angle-addition', 'angle-types'],
    coverage: { thinking: ['combine-measure-and-category'] },
    options: [option('q20-a', math('78°'), text('، وهو حاد')), option('q20-b', math('78°'), text('، وهو منفرج')), option('q20-c', math('50°'), text('، وهو حاد')), option('q20-d', math('128°'), text('، وهو مستقيم'))],
    answer: 'q20-a',
    solution: { idea: rich(text('الزاويتان المتجاورتان تجمعان إلى القياس الكلي؛ نطرح الجزء المعروف ثم نصنف الباقي.')), steps: [rich(math('128°−50°=78°')), rich(text('والباقي أقل من '), math('90°'), text('، لذلك هو حاد.'))], finalAnswer: rich(math('78°'), text('، زاوية حادة.')) },
    originalityNote: 'يستنتج جزءاً مجهولاً من قياس كلي معلوم ثم يصنفه؛ يختلف عن حساب مجموع زاويتين معطاتين في السؤال السابق.',
  }),
]

const definition = defineLessonTest({
  id: testId,
  lessonId,
  title: 'اختبار قياس الزوايا',
  description: rich(text('يقيس هذا الاختبار تسمية الزوايا وفهم الرأس والضلعين، واستخدام المنقلة، ورسم الزوايا وتصنيفها، وجمع قياسات الزوايا المتجاورة.')),
  instructions: rich(text('تُذكر قياسات الزوايا الجديدة داخل كل سؤال ولا تُنسب إلى رسومات مقيسة في الكتاب. عند استخدام المنقلة، حاذ الصفر مع ضلع البداية ثم اقرأ التدريج الموافق.')),
  questions,
  sourceConcepts: [
    { id: 'angle-formation', label: 'الزاوية من التقاء نصفي مستقيمين لهما نقطة بداية مشتركة', pages: [23] },
    { id: 'angle-names-and-vertex', label: 'الرأس والضلعان وتسمية الزاوية مع وضع الرأس في الوسط', pages: [23, 24] },
    { id: 'inside-and-outside-angle', label: 'تحديد النقاط الواقعة داخل الزاوية وخارجها', pages: [24] },
    { id: 'protractor-and-measurement', label: 'مركز المنقلة وخط الصفر والتدريجان وقراءة القياس', pages: [24, 25, 26] },
    { id: 'angle-measure-and-length', label: 'قياس الفتحة مستقل عن طول ضلعي الزاوية', pages: [26] },
    { id: 'angle-types', label: 'الزاوية الحادة والقائمة والمنفرجة والمستقيمة', pages: [23, 25, 27] },
    { id: 'draw-angle-with-protractor', label: 'خطوات رسم زاوية معلومة القياس بالمنقلة', pages: [26, 27] },
    { id: 'adjacent-angle-addition', label: 'جمع قياسات زاويتين متجاورتين في فتحة أكبر', pages: [28, 29] },
  ],
  conceptLabels: {
    'angle-naming': 'تسمية الزاوية بثلاثة أحرف',
    'angle-vertex': 'الرأس نقطة التقاء ضلعي الزاوية',
    'angle-rays-and-vertex': 'الزاوية من نصفَي مستقيمين ورأس مشترك',
    'angle-classification': 'تصنيف الزوايا بحسب القياس',
    'angle-measure-and-ray-length': 'استقلال قياس الزاوية عن طول الضلعين',
    'protractor-measurement': 'قياس الزاوية بالمنقلة',
    'protractor-scales': 'اختيار تدريج المنقلة بحسب موضع الصفر',
    'angle-additivity': 'جمع قياسات الزوايا المتجاورة',
    'straight-angle': 'الزاوية المستقيمة وقياسها 180 درجة',
    'angle-construction': 'رسم زاوية معلومة القياس',
    'inside-and-outside-angle': 'النقطة الداخلية والخارجية بالنسبة إلى زاوية',
  },
  skillLabels: {
    'identify-middle-letter-vertex': 'تحديد الرأس من الحرف الأوسط في اسم الزاوية',
    'recognize-common-endpoint': 'تمييز نقطة البداية المشتركة لنصفي المستقيمين',
    'classify-angle-by-measure': 'مطابقة قياس الزاوية مع نوعها',
    'distinguish-angle-measure-from-side-length': 'فصل قياس الزاوية عن طول ضلعها',
    'prepare-protractor-correctly': 'تهيئة مركز المنقلة وخط الصفر والتدريج',
    'sequence-angle-measurement': 'ترتيب خطوات قياس زاوية',
    'choose-scale-aligned-to-zero': 'اختيار التدريج الذي يبدأ من الصفر المحاذي',
    'add-adjacent-angle-measures': 'جمع قياسي زاويتين متجاورتين',
    'distinguish-vertex-and-arms': 'تمييز الرأس والضلعين والفتحة والقياس',
    'diagnose-vertex-position-in-name': 'كشف وضع الرأس في موضع غير الأوسط',
    'correct-angle-notation': 'تصحيح تسمية الزاوية بثلاثة أحرف',
    'find-complement-within-straight-angle': 'إيجاد الجزء المكمل لزاوية مستقيمة',
    'justify-obtuse-classification': 'تبرير التصنيف المنفرج بالمجال العددي',
    'sequence-protractor-drawing-actions': 'تحديد خطوات استخدام المنقلة في الرسم',
    'mark-angle-measure': 'تعيين علامة عند القياس المطلوب',
    'diagnose-reversed-protractor-scale': 'تشخيص قراءة التدريج المعاكس',
    'select-matching-zero': 'اختيار القراءة من صفر ضلع البداية',
    'check-angle-classification': 'التحقق من نوع الزاوية الناتجة',
    'sequence-angle-construction': 'ترتيب إنشاء زاوية معلومة القياس',
    'compare-measures-with-straight-angle': 'مقارنة قياس بزاوية مستقيمة',
    'classify-point-relative-to-angle': 'تصنيف نقطة داخل الفتحة أو خارجها',
    'evaluate-protractor-alignment': 'تقويم محاذاة مركز المنقلة وخط الصفر',
    'correct-scale-reading': 'تصحيح قراءة تدريج المنقلة',
    'combine-and-classify-angle': 'جمع قياسات الزوايا ثم تصنيف الناتج',
  },
  applicationLabels: { 'antenna-length-application': 'تفسير أثر طول الضلع في قياس زاوية مرسومة' },
  thinkingLabels: {
    'reason-about-angle-region': 'الاستدلال من موضع نقطة بالنسبة إلى ضلعي زاوية',
    'evaluate-measurement-procedure': 'تقييم كفاية خطوات القياس قبل قبول قراءة',
    'combine-measure-and-category': 'جمع قياسات ثم الاستدلال على نوع الزاوية',
  },
  commonErrorLabels: {
    'vertex-not-middle-letter': 'تحديد حرف غير أوسط بوصفه رأس الزاوية',
    'read-opposite-protractor-scale': 'قراءة التدريج الذي لا يبدأ عند ضلع البداية',
    'zero-not-aligned-with-starting-ray': 'القراءة قبل محاذاة خط الصفر مع ضلع البداية',
  },
})

export default definition
