import { defineLessonTest, lessonQuestion, math, rich, text, textOnly, type LessonQuestionDraft } from '../../lessonTestBuilder'
import type { QuestionDefinition } from '../../types'

const testId = 'lesson-coordinates-test'
const lessonId = 'coordinates'
const qid = (number: number) => `${testId}-q${String(number).padStart(2, '0')}`
const q = (number: number, draft: LessonQuestionDraft) =>
  lessonQuestion(testId, lessonId, qid(number), draft)
const option = (id: string, ...runs: Parameters<typeof rich>) => ({ id, label: rich(...runs) })
const optionText = (id: string, value: string) => ({ id, label: textOnly(value) })

const questions: QuestionDefinition[] = [
  q(1, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('تُسجّل بطاقة الشبكة أن النقطة تقع عند '), math('(x,y)=(2,5)'), text('؛ أي كتابة تحفظ العمود الأفقي أولاً ثم الصف الشاقولي؟')),
    concepts: ['ordered-pair'], skills: ['read-coordinate-pair'], sourceConcepts: ['ordered-pair-rule'],
    options: [option('q01-a', math('(2,5)')), option('q01-b', math('(5,2)')), option('q01-c', math('(2,0)')), option('q01-d', math('(0,5)'))],
    answer: 'q01-a',
    solution: { idea: rich(text('الزوج المرتب يكتب قيمة المحور الأفقي قبل قيمة المحور الشاقولي.')), steps: [rich(text('نأخذ '), math('x=2'), text(' بوصفها القيمة الأولى.')), rich(text('ثم نكتب '), math('y=5'), text(' بوصفها القيمة الثانية.'))], finalAnswer: rich(math('(2,5)')) },
    originalityNote: 'صيغت كبطاقة ترميز تختبر ترتيب مركبتي نقطة جديدة، لا كسؤال حركة من الأصل أو قراءة إحدى نقاط الرسم المدرسي.',
  }),
  q(2, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('إذا كان للنقطتين '), math('(1,4)'), text(' و'), math('(6,4)'), text(' الإحداثي الثاني نفسه، فهما على الارتفاع الأفقي نفسه في الشبكة.')),
    concepts: ['coordinate-rows-columns'], skills: ['compare-coordinate-components'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    answer: true,
    solution: { idea: rich(text('الإحداثي الثاني يحدد الموضع الشاقولي، وتساويه يعني أن النقطتين تقعان على الصف نفسه.')), steps: [rich(text('في النقطتين كلتا قيمتي '), math('y'), text(' تساويان '), math('4'), text('.')), rich(text('لذلك يثبت الارتفاع وتختلفان أفقياً فقط.'))], finalAnswer: rich(text('صحيح؛ تقعان على الصف الأفقي نفسه.')) },
    originalityNote: 'يحوّل فكرة الزوج المرتب إلى علاقة عامة بين صفّين من الإحداثيات، بدلاً من سؤال مباشر عن نقطة على أحد المحورين.',
  }),
  q(3, {
    type: 'numeric', difficulty: 'basic',
    prompt: rich(text('على شبكة وحدات، تقع '), math('A=(1,3)'), text(' و'), math('B=(5,3)'), text(' على صف واحد. كم فاصلة أفقية بين عموديهما؟')),
    concepts: ['coordinate-rows-columns'], skills: ['compare-coordinate-components', 'count-grid-intervals'], sourceConcepts: ['coordinate-axes', 'reading-grid'],
    answer: { expected: '4', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('للنقطتين قيمة شاقولية مشتركة، لذا نقارن الإحداثيين الأفقيين فقط.')), steps: [rich(math('5−1=4')), rich(text('يمثل الفرق أربع فواصل بين العمودين على تدريج الوحدة.'))], finalAnswer: rich(math('4')) },
    originalityNote: 'يطلب مقارنة المسافة بين عمودين لنقطتين على صف مشترك؛ ليس إعادة لسؤال قراءة قيمة x لنقطة مفردة.',
  }),
  q(4, {
    type: 'matching', difficulty: 'basic',
    prompt: rich(text('طابق كل نقطة مع الوصف الذي يصدق عليها.')),
    concepts: ['ordered-pair', 'coordinate-axes'], skills: ['interpret-zero-coordinate', 'read-coordinate-pair'], sourceConcepts: ['coordinate-axes', 'reading-grid'],
    left: [option('q04-p', math('P=(0,3)')), option('q04-q', math('Q=(4,0)')), option('q04-r', math('R=(2,5)'))],
    right: [optionText('q04-a', 'الإحداثي الأفقي يساوي صفراً'), optionText('q04-b', 'الإحداثي الشاقولي يساوي صفراً'), optionText('q04-c', 'كلا الإحداثيين غير صفريين')],
    answer: [{ leftId: 'q04-p', rightId: 'q04-a' }, { leftId: 'q04-q', rightId: 'q04-b' }, { leftId: 'q04-r', rightId: 'q04-c' }],
    solution: { idea: rich(text('نقرأ موضع الصفر في الزوج المرتب لتحديد المحور أو معرفة أن النقطة ليست على أحدهما.')), steps: [rich(math('P=(0,3)'), text(' له '), math('x=0'), text('.')), rich(math('Q=(4,0)'), text(' له '), math('y=0'), text('.')), rich(math('R=(2,5)'), text(' لا يحتوي صفراً في أي مركبة.'))], finalAnswer: rich(text('P: أفقي صفر؛ Q: شاقولي صفر؛ R: كلاهما غير صفري.')) },
    originalityNote: 'بُنيت كمطابقة لثلاث حالات للصفر داخل الزوج المرتب؛ لم تُنسخ صياغة سؤال اختيار نقطة على محور بعينه.',
  }),
  q(5, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('تمثل نقطة الأصل تقاطع المحورين، ولذلك يكون الزوج المرتب لها '), math('(0,0)'), text('.')),
    concepts: ['coordinate-origin'], skills: ['identify-origin'], sourceConcepts: ['origin'],
    answer: true,
    solution: { idea: rich(text('الأصل هو نقطة بدء القياس على المحورين معاً.')), steps: [rich(text('لا نتحرك أفقياً من الأصل، فتكون المركبة الأولى صفراً.')), rich(text('ولا نتحرك شاقولياً، فتكون المركبة الثانية صفراً أيضاً.'))], finalAnswer: rich(math('(0,0)')) },
    originalityNote: 'يتحقق من تعريف الأصل بصيغة حكم مفاهيمي قصير، لا من إحداثيات معلم أو نقطة مرسومة بعينها.',
  }),
  q(6, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('أي نقطة تقع على الصف نفسه الذي تقع عليه '), math('M=(2,6)'), text('؟')),
    concepts: ['coordinate-rows-columns'], skills: ['compare-coordinate-components'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    options: [option('q06-a', math('(4,6)')), option('q06-b', math('(6,4)')), option('q06-c', math('(2,5)')), option('q06-d', math('(5,2)'))],
    answer: 'q06-a',
    solution: { idea: rich(text('الصف الأفقي يثبت قيمة الإحداثي الشاقولي، أي العدد الثاني.')), steps: [rich(text('إحداثي '), math('y'), text(' للنقطة '), math('M'), text(' هو '), math('6'), text('.')), rich(text('الاختيار الوحيد الذي يحفظ العدد الثاني '), math('6'), text(' هو '), math('(4,6)'), text('.'))], finalAnswer: rich(math('(4,6)')) },
    originalityNote: 'يستعمل علاقة الصف الأفقي لاستخراج نقطة من بدائل متعددة؛ لا يعيد سؤال تحديد عدد الوحدات الأفقية لنقطة واحدة.',
  }),
  q(7, {
    type: 'ordering', difficulty: 'medium',
    prompt: rich(text('رتّب النقاط من الأيسر إلى الأيمن بحسب مواقعها على المحور الأفقي.')),
    concepts: ['ordered-pair', 'coordinate-rows-columns'], skills: ['order-by-horizontal-coordinate'], sourceConcepts: ['ordered-pair-rule', 'reading-grid'],
    items: [option('q07-a', math('A=(4,1)')), option('q07-b', math('B=(1,5)')), option('q07-c', math('C=(3,2)')), option('q07-d', math('D=(2,6)'))],
    answer: ['q07-b', 'q07-d', 'q07-c', 'q07-a'],
    solution: { idea: rich(text('الترتيب الأفقي يعتمد على المركبة الأولى فقط، ولا تغيّره قيمة المركبة الثانية.')), steps: [rich(text('قيم '), math('x'), text(' للنقاط بالترتيب المعطى هي '), math('4,1,3,2'), text('.')), rich(text('نرتبها تصاعدياً: '), math('1<2<3<4'), text('.'))], finalAnswer: rich(text('B ثم D ثم C ثم A.')) },
    originalityNote: 'يطلب ترتيب مجموعة كاملة بحسب العمود الأفقي مع تجاهل قيم الصف، وهو تحويل جديد للتمثيل لا ترتيب خطوات قراءة الزوج.',
  }),
  q(8, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('إذا كان '), math('P=(3,2)'), text(' و'), math('Q=(3,6)'), text('، فكم نقطة من الإحداثيين تختلف بين الزوجين؟')),
    concepts: ['ordered-pair', 'coordinate-rows-columns'], skills: ['compare-coordinate-components', 'reason-about-equality'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    answer: { expected: '1', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نقارن مركبتي الزوجين في الموضعين المناظرين، ولا نقارن الأرقام منفصلة عن موضعها.')), steps: [rich(text('المركبتان الأوليان متساويتان: '), math('3=3'), text('.')), rich(text('المركبتان الثانية مختلفتان: '), math('2≠6'), text('.'))], finalAnswer: rich(text('مركبة واحدة تختلف.')) },
    originalityNote: 'يختبر عدد المركبات المختلفة في زوجين مرتبين، بدلاً من سؤال عن الحركة أو قراءة مكوّن واحد.',
  }),
  q(9, {
    type: 'matching', difficulty: 'medium',
    prompt: rich(text('طابق كل وصف للعلاقة مع زوج النقاط الذي يحققه.')),
    concepts: ['coordinate-rows-columns'], skills: ['infer-shared-coordinate'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    left: [optionText('q09-l1', 'لهما العمود نفسه'), optionText('q09-l2', 'لهما الصف نفسه'), optionText('q09-l3', 'يختلفان أفقياً وشاقولياً')],
    right: [option('q09-r1', math('A=(1,4), B=(1,2)')), option('q09-r2', math('C=(2,5), D=(6,5)')), option('q09-r3', math('E=(3,1), F=(5,4)'))],
    answer: [{ leftId: 'q09-l1', rightId: 'q09-r1' }, { leftId: 'q09-l2', rightId: 'q09-r2' }, { leftId: 'q09-l3', rightId: 'q09-r3' }],
    solution: { idea: rich(text('تساوي العدد الأول يعني عموداً واحداً، وتساوي الثاني يعني صفاً واحداً.')), steps: [rich(text('في الخيار الأول يتساوى '), math('x=1'), text('.')), rich(text('في الثاني يتساوى '), math('y=5'), text('.')), rich(text('في الثالث تختلف المركبتان معاً.'))], finalAnswer: rich(text('العمود: A وB؛ الصف: C وD؛ اختلاف المركبتين: E وF.')) },
    originalityNote: 'يحوّل مفهومي الصف والعمود إلى تصنيف علاقات بين أزواج؛ لا يعيد تسمية نقطة مفردة أو موضعاً من أمثلة الصفحات.',
  }),
  q(10, {
    type: 'multi-select', difficulty: 'advanced',
    prompt: rich(text('للنقاط '), math('P=(2,3)'), text(' و'), math('Q=(2,6)'), text(' و'), math('R=(5,3)'), text('، اختر كل عبارة صحيحة.')),
    concepts: ['coordinate-rows-columns', 'ordered-pair'], skills: ['compare-coordinate-components', 'justify-grid-alignment'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    options: [optionText('q10-a', 'P وQ على العمود نفسه'), optionText('q10-b', 'P وR على الصف نفسه'), optionText('q10-c', 'Q وR على الصف نفسه'), optionText('q10-d', 'P وQ على الصف نفسه')],
    answer: ['q10-a', 'q10-b'],
    solution: { idea: rich(text('نختبر تساوي كل مركبة في موضعها، لا تشابه الأرقام بين الأزواج.')), steps: [rich(text('لـ P وQ المركبة الأولى '), math('2'), text(' مشتركة، فيتساوى العمود.')), rich(text('لـ P وR المركبة الثانية '), math('3'), text(' مشتركة، فيتساوى الصف.')), rich(text('أما Q وR فلا تتساوى مركبتهما الثانية ولا الأولى.'))], finalAnswer: rich(text('العبارتان الصحيحتان هما A وB.')) },
    originalityNote: 'يجمع بين فحص علاقتين صحيحتين وعلاقتين مضللتين ضمن ثلاث نقاط جديدة؛ لا يبدّل أرقام تمرين من الكتاب.',
  }),
  q(11, {
    type: 'true-false', difficulty: 'medium',
    prompt: rich(text('إذا تساوى الإحداثي الأول لنقطتين، فهما على خط شاقولي واحد حتى لو اختلف الإحداثي الثاني.')),
    concepts: ['coordinate-rows-columns'], skills: ['interpret-first-coordinate'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    answer: true,
    solution: { idea: rich(text('الإحداثي الأول يحدد العمود، وجميع نقاط العمود تقع على خط شاقولي واحد.')), steps: [rich(text('ثبات المركبة الأولى يثبت '), math('x'), text('.')), rich(text('اختلاف المركبة الثانية يغير الارتفاع فقط، لا العمود.'))], finalAnswer: rich(text('صحيح.')) },
    originalityNote: 'يصوغ قاعدة العمود كاستنتاج عام لا كسؤال اختيار عن نقطة على المحور الشاقولي.',
  }),
  q(12, {
    type: 'error-analysis', difficulty: 'medium',
    prompt: rich(text('سجلّ الطالب نقطةً لها '), math('x=4'), text(' و'), math('y=1'), text('، ثم كتب '), math('(1,4)'), text('. حدّد التشخيص والتصحيح المناسبين.')),
    concepts: ['ordered-pair', 'coordinate-error'], skills: ['diagnose-coordinate-swap', 'correct-ordered-pair'], sourceConcepts: ['ordered-pair-rule'],
    coverage: { commonErrors: ['swapped-coordinate-order'] },
    studentWork: rich(math('x=4, y=1 \u21d2 (1,4)')),
    diagnoses: [optionText('q12-d1', 'بدّل موضعي الإحداثيين'), optionText('q12-d2', 'قرأ قيمة صحيحة للزوج المرتب')],
    corrections: [option('q12-c1', math('(4,1)')), option('q12-c2', math('(1,4)'))],
    answer: { diagnosisId: 'q12-d1', correctionId: 'q12-c1' },
    solution: { idea: rich(text('في الزوج المرتب يبقى '), math('x'), text(' أولاً و'), math('y'), text(' ثانياً.')), steps: [rich(text('كتب الطالب قيمة '), math('y'), text(' في الموضع الأول وقيمة '), math('x'), text(' في الموضع الثاني.')), rich(text('نعيد الترتيب إلى أفقي ثم شاقولي.'))], finalAnswer: rich(text('التشخيص: تبديل؛ التصحيح: '), math('(4,1)'), text('.')), commonError: rich(text('اعتبار الزوجين ذوي الرقمين نفسيهما موقعاً واحداً مع أن الترتيب جزء من المعنى.')) },
    originalityNote: 'حالة تصحيح مكتوبة تربط الرمزين x وy بترتيبهما؛ لا تستخدم أرقام خطأ التبديل الواردة في نشاط المنصة.',
  }),
  q(13, {
    type: 'single-choice', difficulty: 'medium',
    prompt: rich(text('أي نقطة تحقق الشرطين معاً: إحداثيها الأول '), math('5'), text(' وإحداثيها الثاني أصغر منه بوحدتين؟')),
    concepts: ['ordered-pair', 'coordinate-constraints'], skills: ['construct-coordinate-from-clues'], sourceConcepts: ['ordered-pair-rule', 'reading-grid'],
    options: [option('q13-a', math('(5,3)')), option('q13-b', math('(3,5)')), option('q13-c', math('(5,7)')), option('q13-d', math('(7,5)'))],
    answer: 'q13-a',
    solution: { idea: rich(text('نحوّل الشرطين إلى قيمتين محددتين قبل اختيار الزوج.')), steps: [rich(text('المركبة الأولى تساوي '), math('5'), text('.')), rich(text('المركبة الثانية تساوي '), math('5−2=3'), text('.'))], finalAnswer: rich(math('(5,3)')) },
    originalityNote: 'يستنتج زوجاً من قيدين لفظيين مترابطين، بدلاً من قراءة إحداثيات نقطة جاهزة أو تحويل حركة من الأصل.',
  }),
  q(14, {
    type: 'numeric', difficulty: 'advanced',
    prompt: rich(text('نقطة '), math('A=(3,2)'), text(' ونقطة '), math('B=(3,6)'), text(' لهما العمود نفسه. إذا انتقلت B إلى النقطة '), math('C=(5,6)'), text('، فكم مركبة تغيّرت من B إلى C؟')),
    concepts: ['coordinate-rows-columns', 'ordered-pair'], skills: ['compare-coordinate-components', 'track-coordinate-change'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    answer: { expected: '1', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نقارن B وC مركبةً بمركبة، مع إبقاء موضع كل عدد في الزوج.')), steps: [rich(text('الإحداثي الأول انتقل من '), math('3'), text(' إلى '), math('5'), text(' فتغيّر.')), rich(text('الإحداثي الثاني بقي '), math('6'), text('، فلا يتغيّر.'))], finalAnswer: rich(text('مركبة واحدة.')) },
    originalityNote: 'يتتبع أي مركبة تتغير عبر انتقالين مترابطين ويستخدم نقطة وسيطة على العمود نفسه؛ بنية تحليلية مختلفة عن تمارين تحديد محور نقطة.',
  }),
  q(15, {
    type: 'ordering', difficulty: 'medium',
    prompt: rich(text('رتّب النقاط تصاعدياً بحسب الإحداثي الشاقولي، وعند التعادل لا حاجة إلى ترتيب إضافي.')),
    concepts: ['ordered-pair', 'coordinate-rows-columns'], skills: ['order-by-vertical-coordinate', 'compare-coordinate-components'], sourceConcepts: ['ordered-pair-rule', 'reading-grid'],
    items: [option('q15-a', math('A=(2,5)')), option('q15-b', math('B=(4,1)')), option('q15-c', math('C=(1,3)')), option('q15-d', math('D=(6,2)'))],
    answer: ['q15-b', 'q15-d', 'q15-c', 'q15-a'],
    solution: { idea: rich(text('هذه المرة نعتمد على المركبة الثانية لأنها تحدد الارتفاع.')), steps: [rich(text('قيم '), math('y'), text(' هي على الترتيب '), math('5,1,3,2'), text('.')), rich(text('تصاعدياً: '), math('1<2<3<5'), text('.'))], finalAnswer: rich(text('B ثم D ثم C ثم A.')) },
    originalityNote: 'يعكس معيار الترتيب إلى الارتفاع الشاقولي بعد سؤال أفقي مستقل، ولا يعيد سلسلة خطوات التمثيل أو القراءة.',
  }),
  q(16, {
    type: 'multi-select', difficulty: 'advanced',
    prompt: rich(text('للنقطتين '), math('P=(1,5)'), text(' و'), math('Q=(5,1)'), text('، اختر جميع العبارات الصحيحة.')),
    concepts: ['ordered-pair', 'coordinate-error'], skills: ['distinguish-ordered-pairs', 'compare-coordinate-components'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    options: [optionText('q16-a', 'لهما الرقمان نفسيهما لكن الترتيبهما مختلف'), optionText('q16-b', 'تمثلان الموقع نفسه على الشبكة'), optionText('q16-c', 'لهما الإحداثي الأول نفسه'), optionText('q16-d', 'يختلف كل من الإحداثي الأول والثاني')],
    answer: ['q16-a', 'q16-d'],
    solution: { idea: rich(text('ترتيب العددين يحدد الموقع؛ لا يكفي وجود الرقمين نفسيهما.')), steps: [rich(text('في P يكون '), math('x=1,y=5'), text('، وفي Q يكون '), math('x=5,y=1'), text('.')), rich(text('اختلفت المركبتان وتبادل موضعاهما، لذلك لا تتطابق النقطتان.'))], finalAnswer: rich(text('العبارتان A وD صحيحتان.')) },
    originalityNote: 'يفحص الفرق المنطقي بين قائمة أعداد وزوج مرتب عبر اختيار عبارات متعددة، وليس تصحيح مثال تبديل محفوظ.',
  }),
  q(17, {
    type: 'error-analysis', difficulty: 'advanced',
    prompt: rich(text('وُصفت نقطتان بأن لهما الصف نفسه، فكتب متعلم '), math('A=(2,4), B=(5,2)'), text(' لأن العدد '), math('2'), text(' يظهر في الزوجين. ما موضع الخلل؟')),
    concepts: ['coordinate-rows-columns', 'coordinate-error'], skills: ['diagnose-false-coordinate-match', 'justify-shared-row'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    coverage: { commonErrors: ['confusing-equal-digits-with-equal-component'] },
    studentWork: rich(math('A=(2,4), B=(5,2)'), text('؛ الصف نفسه')),
    diagnoses: [optionText('q17-d1', 'قارن رقماً في موضعين مختلفين بدل الإحداثي الثاني'), optionText('q17-d2', 'الصف تحدده المركبة الأولى')],
    corrections: [option('q17-c1', math('B=(5,4)')), option('q17-c2', math('B=(2,5)'))],
    answer: { diagnosisId: 'q17-d1', correctionId: 'q17-c1' },
    solution: { idea: rich(text('الصف الأفقي يتطلب تساوي الإحداثي الثاني في الموضع نفسه.')), steps: [rich(text('قيمة '), math('4'), text(' في A هي المركبة الثانية.')), rich(text('لذلك يجب أن تكون المركبة الثانية في B هي '), math('4'), text('؛ ظهور العدد '), math('2'), text(' في موضع مختلف لا يثبت تساوي الصف.'))], finalAnswer: rich(text('التشخيص A؛ والتصحيح المقترح '), math('B=(5,4)'), text('.')), commonError: rich(text('البحث عن رقم مشترك دون مراعاة كونه المركبة الأولى أو الثانية.')) },
    originalityNote: 'يستهدف خطأ مطابقة رقم متكرر بين موضعين مختلفين، وهو أعمق من مجرد تبديل ترتيب الزوج في مثال واحد.',
  }),
  q(18, {
    type: 'single-choice', difficulty: 'thinking',
    prompt: rich(text('تبحث ليلى عن نقطة تقع على الصف نفسه الذي تقع عليه '), math('(2,4)'), text('، ويكون عمودها إلى يمين عمود '), math('(2,4)'), text('. أي نقطة تحقق الشرطين؟')),
    concepts: ['coordinate-constraints', 'coordinate-rows-columns'], skills: ['infer-location-from-two-conditions', 'reason-about-coordinate-order'], sourceConcepts: ['ordered-pair-rule', 'coordinate-axes'],
    coverage: { thinking: ['two-coordinate-constraints'], applications: ['grid-navigation'] },
    options: [option('q18-a', math('(5,4)')), option('q18-b', math('(1,4)')), option('q18-c', math('(5,2)')), option('q18-d', math('(2,5)'))],
    answer: 'q18-a',
    solution: { idea: rich(text('نجمع شرط الصف وشرط الاتجاه الأفقي قبل فحص الخيارات.')), steps: [rich(text('الصف نفسه يقتضي '), math('y=4'), text('.')), rich(text('إلى اليمين يقتضي إحداثياً أول أكبر من '), math('2'), text('.')), rich(text('الاختيار '), math('(5,4)'), text(' يحقق الشرطين.'))], finalAnswer: rich(math('(5,4)')) },
    originalityNote: 'مسألة استدلال من قيدين متزامنين (صف ثابت واتجاه أفقي)، لا سؤال قراءة أو حركة أحادية من نقطة الأصل.',
  }),
  q(19, {
    type: 'matching', difficulty: 'thinking',
    prompt: rich(text('تأمل سجل النقاط ثم طابق كل وصف بالنقطة الوحيدة التي تحققه.')),
    concepts: ['coordinate-constraints', 'ordered-pair'], skills: ['identify-point-from-clues', 'check-coordinate-conditions'], sourceConcepts: ['ordered-pair-rule', 'reading-grid'],
    coverage: { thinking: ['multi-clue-coordinate-reasoning'] },
    left: [optionText('q19-l1', 'الإحداثي الأول يساوي 1'), optionText('q19-l2', 'الإحداثي الثاني يساوي 5'), optionText('q19-l3', 'الإحداثيان متساويان')],
    right: [option('q19-r1', math('A=(2,2)')), option('q19-r2', math('B=(4,5)')), option('q19-r3', math('C=(1,4)'))],
    answer: [{ leftId: 'q19-l1', rightId: 'q19-r3' }, { leftId: 'q19-l2', rightId: 'q19-r2' }, { leftId: 'q19-l3', rightId: 'q19-r1' }],
    solution: { idea: rich(text('كل وصف يختبر علاقة مختلفة بين موضعي العددين.')), steps: [rich(text('C وحدها لها مركبة أولى تساوي '), math('1'), text('.')), rich(text('B وحدها لها مركبة ثانية تساوي '), math('5'), text('.')), rich(text('في A تتساوى المركبتان '), math('2'), text(' و'), math('2'), text('.'))], finalAnswer: rich(text('الأوصاف بالترتيب: C، B، A.')) },
    originalityNote: 'يبني الحل من ثلاثة قيود مستقلة على سجل صغير، ويطلب مطابقة فريدة بدلاً من تمرين نقطة واحدة ذي عملية مباشرة.',
  }),
  q(20, {
    type: 'error-analysis', difficulty: 'thinking',
    prompt: rich(text('تقول مها إن النقطتين '), math('R=(1,4)'), text(' و'), math('S=(2,3)'), text(' تمثلان المكان نفسه لأن مجموع مركبتي كل زوج يساوي '), math('5'), text('. اختر التشخيص والتصحيح.')),
    concepts: ['ordered-pair', 'coordinate-error'], skills: ['evaluate-coordinate-claim', 'compare-coordinate-components'], sourceConcepts: ['ordered-pair-rule'],
    coverage: { thinking: ['evaluate-coordinate-claim'], commonErrors: ['treat-coordinate-sum-as-location'] },
    studentWork: rich(math('R=(1,4), S=(2,3)'), text('؛ 1+4=2+3')),
    diagnoses: [optionText('q20-d1', 'تساوي المجموع لا يكفي؛ يجب مقارنة كل مركبة في موضعها'), optionText('q20-d2', 'المجموع وحده يحدد موقع النقطة على الشبكة')],
    corrections: [optionText('q20-c1', 'المركبتان مختلفتان في الزوجين، لذا R وS نقطتان مختلفتان'), optionText('q20-c2', 'نبدل ترتيب المركبتين ليصبح المجموع متساوياً')],
    answer: { diagnosisId: 'q20-d1', correctionId: 'q20-c1' },
    solution: { idea: rich(text('يتحدد الموقع بزوج المركبتين ومكان كل منهما، لا بمجموعهما.')), steps: [rich(text('المركبة الأولى هي '), math('1'), text(' في R و'), math('2'), text(' في S؛ فهما مختلفتان.')), rich(text('والمركبة الثانية هي '), math('4'), text(' في R و'), math('3'), text(' في S؛ فهما مختلفتان أيضاً.')), rich(math('1+4=2+3=5'), text(' لا يجعل الزوجين متساويين.'))], finalAnswer: rich(text('التشخيص: مجموع الإحداثيين لا يحدد الموقع؛ التصحيح: قارن المركبتين في موضعيهما.')), commonError: rich(text('استبدال ترتيب الزوج المرتب أو جمع مركبتيه ثم التعامل مع الناتج كأنه يصف الموقع كاملاً.')) },
    originalityNote: 'ينقد مساواة نقطتين بسبب مجموع مركبتيهما فقط؛ يختلف عن تبديل أرقام الزوج المرتب أو عن اختيار نقطة من المحور.',
  }),
]

const definition = defineLessonTest({
  id: testId,
  lessonId,
  title: 'اختبار الإحداثيات والزوج المرتب',
  description: rich(text('يقيس هذا الاختبار قراءة الشبكة، وتفسير ترتيب الإحداثيين، والاستدلال من الصفوف والأعمدة ونقطة الأصل.')),
  instructions: rich(text('اقرأ المركبة الأفقية أولاً ثم الشاقولية. في أسئلة الاختيار المتعدد حدّد كل العبارات الصحيحة؛ وفي المطابقة استخدم كل عنصر مرة واحدة.')),
  questions,
  sourceConcepts: [
    { id: 'origin', label: 'الأصل نقطة تقاطع المحورين ومرجع قراءة الشبكة', pages: [3] },
    { id: 'coordinate-axes', label: 'المحور الأفقي X والمحور الشاقولي Y ومواقع النقاط عليهما', pages: [3, 4] },
    { id: 'ordered-pair-rule', label: 'الزوج المرتب يكتب الإحداثي الأفقي ثم الشاقولي', pages: [3, 4] },
    { id: 'reading-grid', label: 'قراءة نقطة من تقاطع صف وعمود على الشبكة', pages: [4] },
  ],
  conceptLabels: {
    'ordered-pair': 'الزوج المرتب ومعنى ترتيب مركبتيه',
    'coordinate-origin': 'نقطة الأصل',
    'coordinate-axes': 'المحوران الأفقي والشاقولي',
    'coordinate-rows-columns': 'العلاقة بين الإحداثيات والصفوف والأعمدة',
    'coordinate-error': 'أخطاء الخلط بين موضعي الإحداثيين',
    'coordinate-constraints': 'استنتاج موقع من قيود على الإحداثيين',
  },
  skillLabels: {
    'read-coordinate-pair': 'قراءة الزوج المرتب وفق ترتيب المحورين',
    'compare-coordinate-components': 'مقارنة مركبات أزواج مرتبة في مواضعها',
    'count-grid-intervals': 'عدّ الفواصل بين عمودين على شبكة الوحدة',
    'interpret-zero-coordinate': 'تفسير أثر الصفر في أحد الإحداثيين',
    'identify-origin': 'تحديد إحداثيي نقطة الأصل',
    'order-by-horizontal-coordinate': 'ترتيب نقاط بحسب الإحداثي الأفقي',
    'reason-about-equality': 'استنتاج ما تثبته مركبة متساوية',
    'infer-shared-coordinate': 'اكتشاف الصف أو العمود المشترك من أزواج',
    'justify-grid-alignment': 'تبرير اصطفاف نقاط على صف أو عمود',
    'interpret-first-coordinate': 'تفسير المركبة الأولى بوصفها موضعاً أفقياً',
    'diagnose-coordinate-swap': 'تشخيص تبديل ترتيب مركبتي الزوج',
    'correct-ordered-pair': 'تصحيح زوج مرتب وفق المحورين',
    'construct-coordinate-from-clues': 'تكوين زوج مرتب من شروط لفظية',
    'track-coordinate-change': 'تتبّع المركبات التي تتغير بين نقطتين',
    'order-by-vertical-coordinate': 'ترتيب نقاط بحسب الإحداثي الشاقولي',
    'distinguish-ordered-pairs': 'تمييز الزوجين عند تبادل موضعي العددين',
    'diagnose-false-coordinate-match': 'كشف مطابقة عددين في موضعين غير متناظرين',
    'justify-shared-row': 'التحقق من الصف بمقارنة المركبة الثانية',
    'infer-location-from-two-conditions': 'استنتاج موقع يحقق شرطين متزامنين',
    'reason-about-coordinate-order': 'تطبيق ترتيب المركبتين على قيود مكانية',
    'identify-point-from-clues': 'تحديد نقطة من أوصاف متعددة',
    'check-coordinate-conditions': 'فحص شروط الإحداثيات على سجل نقاط',
    'evaluate-coordinate-claim': 'تقويم ادعاء عن تطابق نقطتين',
  },
  applicationLabels: { 'grid-navigation': 'تحديد موقع على شبكة وفق شروط اتجاهية' },
  thinkingLabels: {
    'two-coordinate-constraints': 'الاستدلال من شرطين مستقلين على الزوج المرتب',
    'multi-clue-coordinate-reasoning': 'تجميع قرائن متعددة لتحديد نقطة واحدة',
    'evaluate-coordinate-claim': 'تقييم ادعاء عام حول معنى ترتيب الإحداثيين',
  },
  commonErrorLabels: {
    'swapped-coordinate-order': 'تبديل الإحداثي الأفقي بالشاقولي',
    'confusing-equal-digits-with-equal-component': 'اعتبار رقم مشترك في موضعين مختلفين دليلاً على صف واحد',
    'treat-coordinate-sum-as-location': 'اعتبار مجموع الإحداثيين كافياً لتحديد النقطة',
  },
})

export default definition
