import { defineLessonTest, lessonQuestion, math, rich, text, textOnly, type LessonQuestionDraft } from '../../lessonTestBuilder'
import type { QuestionDefinition } from '../../types'

const testId = 'lesson-line-graphs-test'
const lessonId = 'line-graphs'
const qid = (number: number) => `${testId}-q${String(number).padStart(2, '0')}`
const q = (number: number, draft: LessonQuestionDraft) =>
  lessonQuestion(testId, lessonId, qid(number), draft)
const option = (id: string, ...runs: Parameters<typeof rich>) => ({ id, label: rich(...runs) })
const optionText = (id: string, value: string) => ({ id, label: textOnly(value) })

const questions: QuestionDefinition[] = [
  q(1, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('يريد طالب تمثيل قياسات مسجلة عند أوقات متتابعة. أي توزيع للمحورين يوافق اصطلاح التمثيل البياني بالخطوط في الدرس؟')),
    concepts: ['line-graph-axes'], skills: ['assign-graph-axes'], sourceConcepts: ['time-and-data-axes'],
    options: [optionText('q01-a', 'الزمن على الأفقي، والقياسات على الشاقولي'), optionText('q01-b', 'القياسات على الأفقي، والزمن على الشاقولي'), optionText('q01-c', 'المحوران للأزمنة'), optionText('q01-d', 'لا حاجة إلى محور شاقولي')],
    answer: 'q01-a',
    solution: { idea: rich(text('يفصل التمثيل بين ترتيب الزمن ومقدار البيانات.')), steps: [rich(text('تُرتب الأيام أو الأزمنة على المحور الأفقي.')), rich(text('وتُقرأ القيمة المقاسة على المحور الشاقولي.'))], finalAnswer: rich(text('الزمن أفقي والقياس شاقولي.')) },
    originalityNote: 'سؤال قرار حول تصميم محورين لسجل قياس جديد؛ لا ينسخ سؤال الاختبار الختامي عن وظيفة المحور الأفقي وحده.',
  }),
  q(2, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('إذا كانت القراءة المسجلة التالية أكبر من القراءة السابقة، فالمقطع الواصل بين النقطتين يصعد عند تتبع الزمن من اليسار إلى اليمين.')),
    concepts: ['line-segments-and-trend'], skills: ['interpret-line-direction'], sourceConcepts: ['connect-points-and-read-trend'],
    answer: true,
    solution: { idea: rich(text('يمثل ارتفاع النقطة التالية زيادة في قيمة البيانات مع تقدم الزمن.')), steps: [rich(text('تتحرك القراءة من النقطة الأولى إلى التالية على المحور الأفقي.')), rich(text('إذا زادت قيمة المحور الشاقولي، يتجه المقطع إلى أعلى.'))], finalAnswer: rich(text('صحيح؛ يظهر المقطع صاعداً.')) },
    originalityNote: 'يختبر اتجاه مقطع واحد من علاقة ترتيبية عامة، وليس سبب وصل الخطوط أو وصف اتجاه أسبوع كامل.',
  }),
  q(3, {
    type: 'numeric', difficulty: 'basic',
    prompt: rich(text('في سجل تجريبي أُعد لهذا السؤال، كانت القراءتان عند الزمنين المتتاليين '), math('4'), text(' ثم '), math('7'), text(' وحدات. بكم زادت القراءة؟')),
    concepts: ['reading-line-graph'], skills: ['calculate-change-between-records'], sourceConcepts: ['read-values-and-trends'],
    answer: { expected: '3', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('مقدار الزيادة هو الفرق بين القراءة اللاحقة والسابقة.')), steps: [rich(math('7−4=3')), rich(text('والإشارة موجبة لأن القراءة اللاحقة أكبر.'))], finalAnswer: rich(math('3'), text(' وحدات.')) },
    originalityNote: 'يستخدم بيانات عددية مصممة للسؤال لقياس تغير صاعد بين تسجيلين؛ لا يعيد مسألة انخفاض درجة الحرارة في الاختبار السابق.',
  }),
  q(4, {
    type: 'matching', difficulty: 'basic',
    prompt: rich(text('طابق كل جزء من التمثيل البياني بالخطوط مع دوره.')),
    concepts: ['line-graph-axes', 'line-segments-and-trend'], skills: ['identify-graph-elements'], sourceConcepts: ['time-and-data-axes', 'connect-points-and-read-trend'],
    left: [optionText('q04-l1', 'المحور الأفقي'), optionText('q04-l2', 'المحور الشاقولي'), optionText('q04-l3', 'النقطة المرسومة'), optionText('q04-l4', 'المقطع الواصل')],
    right: [optionText('q04-r1', 'ترتيب الزمن'), optionText('q04-r2', 'قيمة البيانات'), optionText('q04-r3', 'قيمة مسجلة عند زمن محدد'), optionText('q04-r4', 'إظهار اتجاه التغير بين تسجيلين متتاليين')],
    answer: [{ leftId: 'q04-l1', rightId: 'q04-r1' }, { leftId: 'q04-l2', rightId: 'q04-r2' }, { leftId: 'q04-l3', rightId: 'q04-r3' }, { leftId: 'q04-l4', rightId: 'q04-r4' }],
    solution: { idea: rich(text('لكل عنصر وظيفة مختلفة في تمثيل سلسلة من البيانات عبر الزمن.')), steps: [rich(text('نقرأ الزمن أفقياً والقيمة شاقولياً.')), rich(text('كل نقطة تقابل قراءة مسجلة واحدة.')), rich(text('يوضح وصل النقاط كيف يتغير المسار بين القراءات المتتابعة.'))], finalAnswer: rich(text('الأفقي: الزمن؛ الشاقولي: القيمة؛ النقطة: قراءة؛ المقطع: اتجاه التغير.')) },
    originalityNote: 'يبني مطابقة رباعية بين أجزاء الرسم ووظائفها، لا تعريفاً منقولاً ولا سؤال اختيار عن المحور فقط.',
  }),
  q(5, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('إذا تساوت قراءتان متتاليتان في تمثيل خطي، كان المقطع الواصل بينهما أفقياً.')),
    concepts: ['line-segments-and-trend'], skills: ['interpret-constant-interval'], sourceConcepts: ['connect-points-and-read-trend'],
    answer: true,
    solution: { idea: rich(text('ثبات القيمة مع انتقال الزمن لا يسبب ارتفاعاً أو انخفاضاً في الرسم.')), steps: [rich(text('تتغير قيمة الزمن على المحور الأفقي.')), rich(text('تبقى القراءة الشاقولية ثابتة، لذلك يصل بين النقطتين مقطع أفقي.'))], finalAnswer: rich(text('صحيح؛ يدل المقطع الأفقي هنا على ثبات القراءتين.')) },
    originalityNote: 'يربط تساوي تسجيلين بشكل المقطع بينهما؛ لا يطلب قراءة يوم أو تحديد أعلى قيمة من بيانات الدرس.',
  }),
  q(6, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('في سجل أُخذت قراءاته عند الأزمنة '), math('1,2,3,4'), text('، ما ترتيب مواقعها على المحور الأفقي عند رسمها؟')),
    concepts: ['line-graph-axes'], skills: ['order-time-values'], sourceConcepts: ['time-and-data-axes'],
    options: [option('q06-a', math('1,2,3,4')), option('q06-b', math('4,3,2,1')), option('q06-c', math('2,1,4,3')), option('q06-d', math('1,3,2,4'))],
    answer: 'q06-a',
    solution: { idea: rich(text('ترتيب المحور الأفقي يحافظ على التسلسل الزمني للتسجيلات.')), steps: [rich(text('نبدأ بأقدم زمن مسجل، وهو '), math('1'), text('.')), rich(text('ثم نتابع إلى '), math('2'), text(' فـ'), math('3'), text(' ثم '), math('4'), text('.'))], finalAnswer: rich(math('1,2,3,4')) },
    originalityNote: 'يختبر ترتيب نقاط زمنية قبل الرسم، وليس خطوات إنشاء رسم كامل أو ترتيب أيام من مثال الكتاب.',
  }),
  q(7, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('سجل جديد يبين القيم '), math('2,6,4,7'), text(' عند الأزمنة المتتالية '), math('1,2,3,4'), text('. كم مقطعاً متتالياً يدل على انخفاض؟')),
    concepts: ['reading-line-graph', 'line-segments-and-trend'], skills: ['count-decreasing-intervals', 'interpret-line-direction'], sourceConcepts: ['read-values-and-trends', 'connect-points-and-read-trend'],
    answer: { expected: '1', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نقارن كل زوج متتالٍ ونعدّ المقاطع التي تكون قراءتها التالية أقل.')), steps: [rich(math('2<6'), text('؛ المقطع الأول صاعد.')), rich(math('6>4'), text('؛ المقطع الثاني هابط.')), rich(math('4<7'), text('؛ المقطع الثالث صاعد.'))], finalAnswer: rich(text('مقطع واحد يدل على انخفاض.')) },
    originalityNote: 'يعدّ المقاطع الهابطة في سلسلة من أربع قراءات بدلاً من حساب مقدار انخفاض بين قراءتين كما في السؤال الختامي.',
  }),
  q(8, {
    type: 'multi-select', difficulty: 'medium',
    prompt: rich(text('في بيانات صُممت لهذا السؤال، كانت القيم عند الأزمنة '), math('1,2,3,4'), text(' هي '), math('3,5,5,2'), text('. اختر كل وصف صحيح.')),
    concepts: ['reading-line-graph', 'line-segments-and-trend'], skills: ['interpret-data-patterns', 'compare-recorded-values'], sourceConcepts: ['read-values-and-trends', 'connect-points-and-read-trend'],
    options: [optionText('q08-a', 'القيمتان عند الزمنين 2 و3 متساويتان'), optionText('q08-b', 'يرتفع المسار من الزمن 1 إلى 2'), optionText('q08-c', 'تنخفض القراءة من الزمن 3 إلى 4'), optionText('q08-d', 'تبقى القراءة ثابتة طوال الأزمنة الأربعة')],
    answer: ['q08-a', 'q08-b', 'q08-c'],
    solution: { idea: rich(text('نقارن كل زوج متتالٍ بحسب ترتيب الزمن، ثم نتحقق من العبارات واحدةً واحدة.')), steps: [rich(math('5=5'), text(' عند الزمنين 2 و3.')), rich(math('3<5'), text(' فيرتفع المقطع الأول.')), rich(math('5>2'), text(' فتنخفض القراءة في المقطع الأخير.'))], finalAnswer: rich(text('العبارات A وB وC صحيحة؛ D غير صحيحة.')) },
    originalityNote: 'يجمع ثلاثة استنتاجات مختلفة من سلسلة قصيرة معدّة للاختبار؛ لا يعيد أسئلة أعلى/أدنى يوم في الجدول المدرسي.',
  }),
  q(9, {
    type: 'ordering', difficulty: 'medium',
    prompt: rich(text('رتّب الإجراءات الواردة في الدرس لإنشاء تمثيل خطي بعد الحصول على البيانات.')),
    concepts: ['line-graph-construction'], skills: ['sequence-graph-construction'], sourceConcepts: ['time-and-data-axes', 'plot-and-connect-records'],
    items: [optionText('q09-a', 'توصيل النقاط المتتابعة بمقاطع مستقيمة'), optionText('q09-b', 'تحديد المحور الأفقي للزمن والشاقولي للبيانات'), optionText('q09-c', 'تمثيل كل قراءة عند زمنها على الشبكة')],
    answer: ['q09-b', 'q09-c', 'q09-a'],
    solution: { idea: rich(text('نحدد محورَي الزمن والبيانات، ثم نمثل القراءات ونصل النقاط المتتابعة.')), steps: [rich(text('نضع الزمن على المحور الأفقي والبيانات على الشاقولي.')), rich(text('نمثل كل قراءة في موضع زمنها.')), rich(text('نصل النقاط المتتابعة بمقاطع مستقيمة لإظهار التغير.'))], finalAnswer: rich(text('تحديد المحورين، تمثيل النقاط، ثم توصيلها.')) },
    originalityNote: 'يرتب خطوات الإنشاء التي يعرضها الدرس نفسه دون إضافة قاعدة اختيار تدريج غير مذكورة في الشرح.'
  }),
  q(10, {
    type: 'matching', difficulty: 'medium',
    prompt: rich(text('طابق كل مقطع بين تسجيلين مع وصف تغير القيمة.')),
    concepts: ['line-segments-and-trend'], skills: ['classify-interval-trend'], sourceConcepts: ['connect-points-and-read-trend'],
    left: [option('q10-l1', math('(1,2)'), text(' إلى '), math('(2,6)')), option('q10-l2', math('(2,6)'), text(' إلى '), math('(3,6)')), option('q10-l3', math('(3,6)'), text(' إلى '), math('(4,3)'))],
    right: [optionText('q10-r1', 'صاعد'), optionText('q10-r2', 'أفقي'), optionText('q10-r3', 'هابط')],
    answer: [{ leftId: 'q10-l1', rightId: 'q10-r1' }, { leftId: 'q10-l2', rightId: 'q10-r2' }, { leftId: 'q10-l3', rightId: 'q10-r3' }],
    solution: { idea: rich(text('نقارن القيمة الثانية في كل زوج مرتب مع الزمن المتقدم.')), steps: [rich(math('2<6'), text('؛ المقطع الأول صاعد.')), rich(math('6=6'), text('؛ الثاني أفقي.')), rich(math('6>3'), text('؛ الثالث هابط.'))], finalAnswer: rich(text('الأول صاعد، الثاني أفقي، الثالث هابط.')) },
    originalityNote: 'يطابق ثلاثة مقاطع محددة بثلاثة اتجاهات من سلسلة جديدة؛ لا يكتفي بوصف الاتجاه العام لأسبوع أو سنة.',
  }),
  q(11, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('في تمثيل خطي، تقابل الأزمنة '), math('1,2,3,4'), text(' القيم '), math('2,4,4,7'), text(' على الترتيب. كم قراءة مسجلة قيمتها '), math('4'), text('؟')),
    concepts: ['reading-line-graph'], skills: ['count-equal-recorded-values'], sourceConcepts: ['read-values-and-trends'],
    answer: { expected: '2', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نعد النقاط ذات القيمة المطلوبة ولا نعد المسافة بين النقاط.')), steps: [rich(text('تظهر القيمة '), math('4'), text(' عند الزمنين '), math('2'), text(' و'), math('3'), text('.'))], finalAnswer: rich(text('قراءتان مسجلتان.')) },
    originalityNote: 'يقيس تكرار قيمة مسجلة في سلسلة بيانات جديدة، لا تحديد اليوم الأعلى أو الأدنى في بيانات الكتاب.',
  }),
  q(12, {
    type: 'error-analysis', difficulty: 'medium',
    prompt: rich(text('رسم متعلم الزمن على المحور الشاقولي واسم القياس على الأفقي، ثم قال إن النقاط مرتبة ترتيباً صحيحاً. اختر التشخيص والتصحيح.')),
    concepts: ['line-graph-axes', 'graph-construction-error'], skills: ['diagnose-axis-assignment-error', 'correct-graph-setup'], sourceConcepts: ['time-and-data-axes'],
    coverage: { commonErrors: ['swap-time-and-data-axes'] },
    studentWork: rich(text('المحور الأفقي: مقدار القياس؛ المحور الشاقولي: الزمن.')),
    diagnoses: [optionText('q12-d1', 'عكس موضعي الزمن والبيانات'), optionText('q12-d2', 'استخدم المحورين كما يطلب الدرس')],
    corrections: [optionText('q12-c1', 'الزمن أفقي والقياس شاقولي'), optionText('q12-c2', 'الزمن شاقولي والقياس أفقي')],
    answer: { diagnosisId: 'q12-d1', correctionId: 'q12-c1' },
    solution: { idea: rich(text('في التمثيل الخطي للدرس يكون الزمن على المحور الأفقي والبيانات على الشاقولي.')), steps: [rich(text('نقارن التوزيع المرسوم بالاصطلاح الذي تدرب عليه الطالب.')), rich(text('المحوران موجودان لكن تسميتيهما تبادلتا.'))], finalAnswer: rich(text('التشخيص: عكس المحورين؛ والتصحيح: الزمن أفقي والقياس شاقولي.')), commonError: rich(text('الاعتقاد أن أي تبديل للمحورين يحافظ على قراءة الرسم بالطريقة نفسها.')) },
    originalityNote: 'تحليل لخطأ إعداد محورين كاملين، لا لالتباس قراءة نقطة فوق يوم بعينه في الاختبار الختامي.',
  }),
  q(13, {
    type: 'true-false', difficulty: 'medium',
    prompt: rich(text('إذا وصل الخط بين تسجيلين عند الزمنين '), math('1'), text(' و'), math('3'), text('، فإن مرور القطعة عند موضع الزمن '), math('2'), text(' وحده لا يثبت أن قيمة فعلية سُجلت عند الزمن '), math('2'), text('.')),
    concepts: ['line-segments-and-trend', 'limits-of-interpolation'], skills: ['distinguish-trend-from-recorded-value'], sourceConcepts: ['connect-points-and-read-trend', 'read-values-and-trends'],
    answer: true,
    solution: { idea: rich(text('المقطع يوضح الاتجاه بين القراءتين، لكنه لا يضيف قياساً لم يُسجل.')), steps: [rich(text('البيانات المعطاة تسجل نقطتين فقط عند الزمنين '), math('1'), text(' و'), math('3'), text('.')), rich(text('لا يجوز تحويل موضع على القطعة إلى قراءة دقيقة مؤكدة للزمن الوسيط من دون بيانات إضافية.'))], finalAnswer: rich(text('صحيح؛ المقطع لا يثبت قراءة غير مسجلة.')) },
    originalityNote: 'يعالج حدود الاستدلال من مقطع بين تسجيلين في مثال زمني جديد؛ لا يكرر سيناريو اليوم غير المطبوع المستخدم في شرح الدرس.',
  }),
  q(14, {
    type: 'numeric', difficulty: 'advanced',
    prompt: rich(text('في سجل واحد، كانت القراءات عند الأزمنة '), math('1,2,3,4'), text(' هي '), math('3,9,6,4'), text(' على الترتيب. كم وحدة تفوق القراءة الأعلى قراءة الزمن الرابع؟')),
    concepts: ['reading-line-graph', 'compare-recorded-values'], skills: ['compare-highest-and-selected-reading'], sourceConcepts: ['read-values-and-trends'],
    answer: { expected: '5', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نحدد أعلى قراءة في السجل، ثم نقارنها بقراءة الزمن المحدد.')), steps: [rich(text('أعلى قيمة هي '), math('9'), text(' عند الزمن الثاني.')), rich(text('قراءة الزمن الرابع هي '), math('4'), text('.')), rich(math('9−4=5'))], finalAnswer: rich(math('5'), text(' وحدات.')) },
    originalityNote: 'يقارن أعلى تسجيل بقراءة لاحقة ضمن سلسلة واحدة معطاة؛ لا يفترض رسماً ثانياً أو مهارة مقارنة منحنيين غير مشمولة في الدرس.',
  }),
  q(15, {
    type: 'multi-select', difficulty: 'advanced',
    prompt: rich(text('سجلّ جديد يعطي عند الأزمنة '), math('1,2,3,4,5'), text(' القيم '), math('2,5,5,3,7'), text('. اختر كل استنتاج تدعمه التسجيلات.')),
    concepts: ['reading-line-graph', 'line-segments-and-trend'], skills: ['analyze-multiple-trend-features', 'compare-recorded-values'], sourceConcepts: ['read-values-and-trends', 'connect-points-and-read-trend'],
    options: [optionText('q15-a', 'تثبت القراءة بين الزمنين 2 و3'), optionText('q15-b', 'تنخفض القراءة من الزمن 3 إلى 4'), optionText('q15-c', 'قيمة الزمن 5 أكبر من كل القيم المسجلة قبلها'), optionText('q15-d', 'كل مقطع في الرسم صاعد')],
    answer: ['q15-a', 'q15-b', 'q15-c'],
    solution: { idea: rich(text('نختبر الثبات والاتجاه والمقارنة مع القيمة النهائية كلّاً على حدة.')), steps: [rich(math('5=5'), text('؛ ثبات بين الزمنين 2 و3.')), rich(math('5>3'), text('؛ انخفاض من الزمن 3 إلى 4.')), rich(math('7>2,5,5,3'), text('؛ القراءة الأخيرة هي الأكبر.'))], finalAnswer: rich(text('A وB وC صحيحة؛ D خاطئة لأن بعض المقاطع أفقية أو هابطة.')) },
    originalityNote: 'يتطلب التحقق من ثلاث خصائص لمسار واحد ذي خمس نقاط، مع عدم تحويل التساوي أو الزيادة إلى إعادة لسؤال ذروة يوم بعينه.',
  }),
  q(16, {
    type: 'error-analysis', difficulty: 'advanced',
    prompt: rich(text('وضع رسام نقاط القياس بترتيب ورودها في الورقة، لكنه كتب على المحور الأفقي الزمن '), math('1,3,2,4'), text(' بدلاً من التسلسل الزمني. ما التشخيص والتصحيح؟')),
    concepts: ['line-graph-construction', 'graph-construction-error'], skills: ['diagnose-time-order-error', 'restore-chronological-axis'], sourceConcepts: ['time-and-data-axes', 'plot-and-connect-records'],
    coverage: { commonErrors: ['misorder-time-axis'] },
    studentWork: rich(text('تدريج الزمن على المحور الأفقي: '), math('1,3,2,4')),
    diagnoses: [optionText('q16-d1', 'ترتيب الأزمنة غير متتابع'), optionText('q16-d2', 'القيم الشاقولية هي التي يجب أن ترتب زمنياً')],
    corrections: [option('q16-c1', math('1,2,3,4')), option('q16-c2', math('4,3,2,1'))],
    answer: { diagnosisId: 'q16-d1', correctionId: 'q16-c1' },
    solution: { idea: rich(text('ينبغي أن يحافظ موضع كل نقطة على ترتيب الأزمنة المسجلة.')), steps: [rich(text('الزمن '), math('2'), text(' يسبق الزمن '), math('3'), text('، فلا يصح وضعه بعده على المحور.')), rich(text('نستعيد التسلسل من الأقدم إلى الأحدث.'))], finalAnswer: rich(text('التشخيص: خلل في ترتيب الزمن؛ التصحيح: '), math('1,2,3,4'), text('.')), commonError: rich(text('ترتيب النقاط وفق ظهورها في قائمة غير مرتبة بدلاً من ترتيبها الزمني.')) },
    originalityNote: 'يفحص خلل ترتيب تدريج الزمن قبل وصل النقاط؛ يختلف عن خطأ اختيار اليوم الخطأ أثناء قراءة نقطة جاهزة.',
  }),
  q(17, {
    type: 'single-choice', difficulty: 'advanced',
    prompt: rich(text('في سجل مقصود لهذا السؤال، كانت القيم عند الأزمنة '), math('1,2,3'), text(' هي '), math('2,7,4'), text('. أي وصف يقارن مقدار التغير في أول مقطعين مقارنة صحيحة؟')),
    concepts: ['line-segments-and-trend', 'reading-line-graph'], skills: ['compare-change-magnitudes', 'interpret-line-direction'], sourceConcepts: ['read-values-and-trends', 'connect-points-and-read-trend'],
    options: [optionText('q17-a', 'الزيادة الأولى 5 وحدات، والانخفاض التالي 3 وحدات؛ فالزيادة أكبر'), optionText('q17-b', 'الزيادة والانخفاض متساويان'), optionText('q17-c', 'الانخفاض أكبر من الزيادة'), optionText('q17-d', 'لا يمكن تحديد الاتجاه من القيم المسجلة')],
    answer: 'q17-a',
    solution: { idea: rich(text('نحسب فرق كل مقطع متتالٍ ثم نقارن المقدارين.')), steps: [rich(math('7−2=5'), text(' وحدات زيادة.')), rich(math('7−4=3'), text(' وحدات انخفاض.')), rich(text('وبما أن '), math('5>3'), text(' فالزيادة الأولى أكبر.'))], finalAnswer: rich(text('الاختيار A.')) },
    originalityNote: 'يقارن مقداري تغير متعاكسين في سلسلة من ثلاث قراءات؛ لا يطلب وصف التوجه العام فقط ولا يستخدم أرقام اختبار الدرس.',
  }),
  q(18, {
    type: 'multi-select', difficulty: 'thinking',
    prompt: rich(text('رُصدت القيم عند الأزمنة '), math('1,2,3,4'), text(' فكانت '), math('3,6,4,4'), text('. اختر كل عبارة تفسر المسار بدقة.')),
    concepts: ['reading-line-graph', 'line-segments-and-trend'], skills: ['synthesize-series-pattern', 'distinguish-equal-and-changing-values'], sourceConcepts: ['read-values-and-trends', 'connect-points-and-read-trend'],
    coverage: { thinking: ['synthesize-several-intervals'], applications: ['recorded-measurement-series'] },
    options: [optionText('q18-a', 'يرتفع أولاً من الزمن 1 إلى 2'), optionText('q18-b', 'ينخفض من الزمن 2 إلى 3 ثم يثبت من 3 إلى 4'), optionText('q18-c', 'يبقى المسار ثابتاً من الزمن 1 إلى 4'), optionText('q18-d', 'قيمة الزمن 4 أكبر من قيمة الزمن 2')],
    answer: ['q18-a', 'q18-b'],
    solution: { idea: rich(text('نفصل المسار إلى المقاطع الثلاثة بدلاً من وصف السلسلة كلها بكلمة واحدة.')), steps: [rich(math('3<6'), text('؛ المقطع الأول صاعد.')), rich(math('6>4'), text('؛ الثاني هابط.')), rich(math('4=4'), text('؛ الثالث أفقي.'))], finalAnswer: rich(text('A وB صحيحتان؛ C وD لا تدعمهما القيم.')) },
    originalityNote: 'يطلب تركيب ثلاثة اتجاهات محلية مختلفة في مسار واحد، لا اختيار وصف عام لتوجه خط صاعد أو هابط.',
  }),
  q(19, {
    type: 'error-analysis', difficulty: 'thinking',
    prompt: rich(text('سُجلت القراءة '), math('2'), text(' عند الزمن '), math('1'), text(' والقراءة '), math('8'), text(' عند الزمن '), math('3'), text('. استنتج طالب أن القراءة المؤكدة عند الزمن '), math('2'), text(' هي '), math('5'), text(' لأن النقاط موصولة. اختر التشخيص والتصحيح.')),
    concepts: ['limits-of-interpolation', 'line-segments-and-trend'], skills: ['evaluate-unrecorded-value-claim', 'separate-graph-trend-from-measurement'], sourceConcepts: ['connect-points-and-read-trend', 'read-values-and-trends'],
    coverage: { thinking: ['evaluate-evidence-for-unrecorded-time'], commonErrors: ['treat-segment-as-exact-measurement'] },
    studentWork: rich(math('(1,2),(3,8) ⇒ (2,5)'), text(' قراءة مؤكدة')),
    diagnoses: [optionText('q19-d1', 'استنتج قراءة لم تُعطَ من مجرد وصل النقطتين'), optionText('q19-d2', 'لم يلاحظ أن القراءة المسجلة عند الزمن 3 تساوي 5')],
    corrections: [optionText('q19-c1', 'المعروف أن المسار يرتفع بين القراءتين؛ لا توجد قراءة مسجلة دقيقة للزمن 2'), optionText('q19-c2', 'تُعد القيمة 5 قياساً مؤكداً لأن المقطع مستقيم')],
    answer: { diagnosisId: 'q19-d1', correctionId: 'q19-c1' },
    solution: { idea: rich(text('المعطيات تثبت نقطتي البداية والنهاية فقط، أما القيمة الوسيطة فتحتاج إلى تسجيل مستقل.')), steps: [rich(text('القيمة '), math('5'), text(' تقع على استيفاء بصري محتمل، لكنها غير مذكورة في السجل.')), rich(text('المقطع يبين اتجاهاً صاعداً ولا يحول الزمن غير المسجل إلى قياس مؤكد.'))], finalAnswer: rich(text('التشخيص A؛ والتصحيح A.')), commonError: rich(text('قراءة كل موضع على القطعة المستقيمة على أنه قياس فعلي مسجل.')) },
    originalityNote: 'نقد لاستنتاج قيمة عند زمن غير مسجل باستخدام زوج قياسات جديد؛ لا ينسخ مثال اليوم الوسيط الوارد في ملاحظات الدرس.',
  }),
  q(20, {
    type: 'matching', difficulty: 'thinking',
    prompt: rich(text('في سجل واحد عند الأزمنة '), math('1,2,3,4,5'), text(' القيم '), math('6,3,3,8,5'), text('؛ طابق كل عبارة بالجزء الذي يثبتها.')),
    concepts: ['reading-line-graph', 'line-segments-and-trend'], skills: ['identify-maximum-record', 'identify-equal-consecutive-readings', 'locate-decline-after-peak'], sourceConcepts: ['read-values-and-trends', 'connect-points-and-read-trend'],
    coverage: { thinking: ['synthesize-evidence-in-one-series'] },
    left: [optionText('q20-l1', 'أعلى قراءة في السجل'), optionText('q20-l2', 'قراءتان متتاليتان متساويتان'), optionText('q20-l3', 'مقطع هابط يلي أعلى قراءة')],
    right: [option('q20-r1', text('الزمن '), math('4'), text(': القيمة '), math('8')), option('q20-r2', text('الزمنان '), math('2'), text(' و'), math('3'), text(': القيمة '), math('3')), option('q20-r3', text('من الزمن '), math('4'), text(' إلى '), math('5'), text(': '), math('8'), text(' إلى '), math('5'))],
    answer: [{ leftId: 'q20-l1', rightId: 'q20-r1' }, { leftId: 'q20-l2', rightId: 'q20-r2' }, { leftId: 'q20-l3', rightId: 'q20-r3' }],
    solution: { idea: rich(text('نحدد القراءة الأعلى والمقطع المرتبط بها، ونلاحظ أيضاً تساوي تسجيلين متتاليين.')), steps: [rich(text('أكبر قيمة هي '), math('8'), text(' عند الزمن الرابع.')), rich(text('القراءتان عند الزمنين الثاني والثالث متساويتان: '), math('3=3'), text('.')), rich(text('بعد أعلى قراءة مباشرة ينخفض المسار من '), math('8'), text(' إلى '), math('5'), text('.'))], finalAnswer: rich(text('الأعلى: الزمن 4؛ التساوي: الزمنان 2 و3؛ الهبوط: من الزمن 4 إلى 5.')) },
    originalityNote: 'يجمع ثلاث قرائن من سلسلة زمنية واحدة، لا يقارن رسوماً أو سلاسل منفصلة، ويستند إلى القراءة والاتجاهين الواردين في الدرس.',
  }),
]

const definition = defineLessonTest({
  id: testId,
  lessonId,
  title: 'اختبار التمثيل البياني بالخطوط',
  description: rich(text('يقيس هذا الاختبار تنظيم الزمن والبيانات على المحورين، وقراءة القيم والاتجاهات، والتمييز بين التسجيل الفعلي وما لا يثبته وصل النقاط.')),
  instructions: rich(text('كل سلسلة رقمية جديدة في السؤال بيانات اختبارية معطاة هنا وليست ادعاءً عن أرقام مطبوعة في الكتاب. استخدم ترتيب الزمن، ولا تستنتج قياساً غير مسجل لمجرد مرور الخط بموضع ما.')),
  questions,
  sourceConcepts: [
    { id: 'time-and-data-axes', label: 'الزمن على المحور الأفقي والبيانات على المحور الشاقولي', pages: [7, 8] },
    { id: 'connect-points-and-read-trend', label: 'تمثيل القراءات بنقاط ووصلها لإظهار التغير بين التسجيلات', pages: [7, 8] },
    { id: 'read-values-and-trends', label: 'قراءة القيم المسجلة وملاحظة الثبات والزيادة والانخفاض', pages: [7, 8, 9] },
    { id: 'plot-and-connect-records', label: 'إنشاء التمثيل الخطي بترتيب التسجيلات على الزمن', pages: [7, 8] },
  ],
  conceptLabels: {
    'line-graph-axes': 'وظيفة المحورين في التمثيل البياني بالخطوط',
    'line-segments-and-trend': 'دلالة المقاطع الواصلة على تغير البيانات',
    'reading-line-graph': 'قراءة القراءات من تمثيل خطي',
    'compare-recorded-values': 'مقارنة قراءات ضمن سلسلة زمنية واحدة',
    'line-graph-construction': 'خطوات إنشاء تمثيل بياني بالخطوط',
    'graph-construction-error': 'أخطاء إعداد المحاور وترتيب الزمن',
    'limits-of-interpolation': 'حدود الاستدلال على قيمة غير مسجلة بين نقطتين',
  },
  skillLabels: {
    'assign-graph-axes': 'إسناد الزمن والبيانات إلى المحورين الصحيحين',
    'interpret-line-direction': 'تفسير اتجاه المقطع الصاعد أو الهابط',
    'calculate-change-between-records': 'حساب مقدار تغير بين تسجيلين متتاليين',
    'count-decreasing-intervals': 'عدّ المقاطع التي تنخفض فيها القراءة',
    'identify-graph-elements': 'تمييز المحاور والنقاط والمقاطع ووظائفها',
    'interpret-constant-interval': 'التعرف إلى الثبات من تساوي قراءتين متتاليتين',
    'order-time-values': 'ترتيب أزمنة التسجيل على المحور الأفقي',
    'interpret-data-patterns': 'استخلاص أنماط من عدة قراءات',
    'compare-recorded-values': 'مقارنة قيم مسجلة في أزمنة مختلفة',
    'sequence-graph-construction': 'ترتيب خطوات إعداد التمثيل الخطي',
    'classify-interval-trend': 'تصنيف اتجاه مقطع بين تسجيلين',
    'count-equal-recorded-values': 'عدّ التسجيلات التي تتساوى في القيمة',
    'diagnose-axis-assignment-error': 'تشخيص تبديل محوري الزمن والبيانات',
    'correct-graph-setup': 'تصحيح إعداد محوري التمثيل الخطي',
    'distinguish-trend-from-recorded-value': 'تمييز الاتجاه المرئي من القراءة المسجلة',
    'compare-highest-and-selected-reading': 'مقارنة أعلى قراءة بقراءة زمن محدد',
    'analyze-multiple-trend-features': 'تحليل الثبات والتغير والمقارنة معاً',
    'diagnose-time-order-error': 'كشف ترتيب زمني غير متتابع على المحور',
    'restore-chronological-axis': 'إعادة الأزمنة إلى ترتيبها الزمني',
    'compare-change-magnitudes': 'مقارنة مقداري زيادة وانخفاض',
    'synthesize-series-pattern': 'تركيب اتجاهات عدة مقاطع في وصف واحد',
    'distinguish-equal-and-changing-values': 'التمييز بين المقطع الثابت والمقاطع المتغيرة',
    'evaluate-unrecorded-value-claim': 'تقويم ادعاء عن قياس غير وارد في السجل',
    'separate-graph-trend-from-measurement': 'فصل اتجاه الرسم عن بيانات القياس الفعلية',
    'identify-maximum-record': 'تحديد أعلى قراءة في سلسلة زمنية',
    'identify-equal-consecutive-readings': 'اكتشاف قراءتين متتاليتين متساويتين',
    'locate-decline-after-peak': 'تحديد المقطع الهابط بعد أعلى قراءة',
  },
  applicationLabels: {
    'recorded-measurement-series': 'قراءة سلسلة قياسات زمنية معطاة',
  },
  thinkingLabels: {
    'synthesize-several-intervals': 'جمع دلالات أكثر من مقطع في تفسير واحد',
    'evaluate-evidence-for-unrecorded-time': 'تقييم كفاية الدليل لقراءة زمن غير مسجل',
    'synthesize-evidence-in-one-series': 'تركيب قرائن من سلسلة زمنية واحدة',
  },
  commonErrorLabels: {
    'swap-time-and-data-axes': 'وضع الزمن والبيانات على المحورين المعاكسين',
    'misorder-time-axis': 'عدم حفظ التسلسل الزمني على المحور الأفقي',
    'treat-segment-as-exact-measurement': 'اعتبار كل موضع على المقطع قياساً مؤكداً',
  },
})

export default definition
