import { defineLessonTest, lessonQuestion, math, rich, text, textOnly, type LessonQuestionDraft } from '../../lessonTestBuilder'
import type { QuestionDefinition } from '../../types'

const testId = 'lesson-natural-numbers-test'
const lessonId = 'natural-numbers'
const qid = (number: number) => `${testId}-q${String(number).padStart(2, '0')}`
const q = (number: number, draft: LessonQuestionDraft) =>
  lessonQuestion(testId, lessonId, qid(number), draft)
const option = (id: string, ...runs: Parameters<typeof rich>) => ({ id, label: rich(...runs) })
const optionText = (id: string, value: string) => ({ id, label: textOnly(value) })

const questions: QuestionDefinition[] = [
  q(1, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('في العدد '), math('6,203,041'), text('، ما اسم المنزلة التي يشغلها الرقم '), math('2'), text('؟')),
    concepts: ['place-value'], skills: ['identify-digit-place'], sourceConcepts: ['place-value-and-groups'],
    options: [optionText('q01-a', 'مئات الآلاف'), optionText('q01-b', 'عشرات الآلاف'), optionText('q01-c', 'الآلاف'), optionText('q01-d', 'الملايين')],
    answer: 'q01-a',
    solution: { idea: rich(text('يصف اسم المنزلة موقع الرقم داخل مجموعته، أما قيمة الرقم فتتطلب ضربه بقيمة تلك المنزلة.')), steps: [rich(text('نقسم العدد إلى مجموعات: '), math('6 | 203 | 041'), text('.')), rich(text('الرقم '), math('2'), text(' هو أول رقم في مجموعة الآلاف، أي في منزلة مئات الآلاف.'))], finalAnswer: rich(text('مئات الآلاف.')) },
    originalityNote: 'يسأل عن اسم المنزلة لا قيمتها؛ يميز بين هذين المصطلحين في عدد جديد بدلاً من إعادة سؤال القيمة العددية في الاختبار الختامي.',
  }),
  q(2, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('تساعد الفواصل في العدد '), math('8,014,002'), text(' على تقسيمه إلى مجموعات الملايين والآلاف والوحدات، وكل مجموعة بعد الأولى تقرأ في ثلاث خانات.')),
    concepts: ['number-groups'], skills: ['group-digits-by-threes'], sourceConcepts: ['place-value-and-groups'],
    answer: true,
    solution: { idea: rich(text('تُنظم الأعداد الكبيرة في مجموعات ثلاثية من اليمين إلى اليسار.')), steps: [rich(text('نكتب التجميع '), math('8 | 014 | 002'), text('.')), rich(text('تمثل المجموعات الملايين ثم الآلاف ثم الوحدات.'))], finalAnswer: rich(text('صحيح.')) },
    originalityNote: 'يتحقق من وظيفة التجميع الثلاثي في عدد ذي مجموعتين صفريتين؛ لا يطلب تسمية العدد أو كتابة عدد كتابي مكرر.',
  }),
  q(3, {
    type: 'numeric', difficulty: 'basic',
    prompt: rich(text('كم صفراً يظهر في كتابة العدد '), math('7,040,206'), text('؟')),
    concepts: ['zero-placeholders', 'number-groups'], skills: ['count-zero-digits', 'read-standard-form'], sourceConcepts: ['zeros-hold-place'],
    answer: { expected: '3', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نعدّ الأصفار المكتوبة في العدد نفسه، لا الخانات التي لا تظهر في الصيغة التفصيلية.')), steps: [rich(text('في مجموعة الآلاف '), math('040'), text(' يظهر صفران، وفي مجموعة الوحدات '), math('206'), text(' يظهر صفر واحد.'))], finalAnswer: rich(text('ثلاثة أصفار.')) },
    originalityNote: 'يقيس الانتباه إلى الأصفار الظاهرة في كتابة قياسية جديدة، وهو عدّ للخانات لا إعادة لتحليل عدد كتابي سابق.',
  }),
  q(4, {
    type: 'matching', difficulty: 'basic',
    prompt: rich(text('طابق كل جزء من العدد '), math('5,708,042'), text(' مع المجموعة التي ينتمي إليها.')),
    concepts: ['number-groups', 'place-value'], skills: ['identify-three-digit-groups'], sourceConcepts: ['place-value-and-groups'],
    left: [option('q04-l1', math('5')), option('q04-l2', math('708')), option('q04-l3', math('042'))],
    right: [optionText('q04-r1', 'مجموعة الملايين'), optionText('q04-r2', 'مجموعة الآلاف'), optionText('q04-r3', 'مجموعة الوحدات')],
    answer: [{ leftId: 'q04-l1', rightId: 'q04-r1' }, { leftId: 'q04-l2', rightId: 'q04-r2' }, { leftId: 'q04-l3', rightId: 'q04-r3' }],
    solution: { idea: rich(text('نبدأ التقسيم من اليمين، بحيث تمثل كل مجموعة ثلاث خانات.')), steps: [rich(text('المجموعة اليمنى '), math('042'), text(' للوحدات.')), rich(text('تسبقها '), math('708'), text(' للآلاف، ثم '), math('5'), text(' للملايين.'))], finalAnswer: rich(text('5: الملايين؛ 708: الآلاف؛ 042: الوحدات.')) },
    originalityNote: 'مطابقة موضعية لمجموعات عدد واحد مع إبقاء الصفر في أول مجموعة الوحدات؛ لا تنقل سؤال صيغة لفظية أو تفصيلية.',
  }),
  q(5, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('عند كتابة العدد '), math('8,020,306'), text(' بالتفصيل، لماذا لا يظهر حد مستقل لكل صفر؟')),
    concepts: ['expanded-form', 'zero-placeholders'], skills: ['explain-zero-placeholder'], sourceConcepts: ['expanded-standard-forms', 'zeros-hold-place'],
    options: [optionText('q05-a', 'قيمة الصفر صفر، فلا يضيف حداً؛ لكنه يبقى في الصيغة القياسية حافظاً لمواضع الأرقام.'), optionText('q05-b', 'نحذف الأصفار من العدد القياسي قبل كتابة أي صيغة أخرى.'), optionText('q05-c', 'كل صفر يجعل الأرقام التي تليه بلا قيمة.'), optionText('q05-d', 'الصفر يساوي عشرة عند كتابة التفصيل.')],
    answer: 'q05-a',
    solution: { idea: rich(text('التفصيل يجمع الحدود ذات القيم غير الصفرية، بينما تحفظ الأصفار مواضع الخانات في العدد القياسي.')), steps: [rich(text('في '), math('8,020,306'), text(' تساهم المنازل غير الصفرية بقيم '), math('8,000,000'), text(' و'), math('20,000'), text(' و'), math('300'), text(' و'), math('6'), text('.')), rich(text('قيمة كل منزلة صفرية تساوي صفراً، فلا نضيف حداً مستقلاً لها، ولا نحذفها من الكتابة القياسية.'))], finalAnswer: rich(text('الأصفار لا تضيف حدوداً، لكنها تحفظ مواضع الخانات.')) },
    originalityNote: 'يفسر وظيفة الأصفار في الانتقال من الصيغة القياسية إلى حدودها بدلاً من اختيار مجموع تفصيلي كامل كما في السؤال الختامي.',
  }),
  q(6, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('الكتابة '), math('8,000,000+30,000+400+2'), text(' تساوي العدد '), math('8,030,402'), text('.')),
    concepts: ['expanded-form', 'place-value'], skills: ['verify-number-by-recomposition'], sourceConcepts: ['expanded-standard-forms', 'recompose-to-check'],
    answer: true,
    solution: { idea: rich(text('نعيد جمع قيم المنازل ثم نقارن الناتج بالعدد المطلوب.')), steps: [rich(math('8,000,000+30,000+400+2=8,030,402')), rich(text('إذن العبارة تطابق العدد المعطى فعلاً.'))], finalAnswer: rich(text('صحيح؛ المجموع يساوي '), math('8,030,402'), text('.')) },
    originalityNote: 'يعرض مساواة تحتاج إلى تحقق بالتجميع؛ صيغت كحكم إعادة تركيب لعدد جديد لا كسؤال عن حد ناقص في صيغة محفوظة.',
  }),
  q(7, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('في العدد '), math('6,240,075'), text('، كم تزيد قيمة منزلة عشرات الآلاف على قيمة منزلة الآلاف؟')),
    concepts: ['place-value', 'number-comparison'], skills: ['compare-place-value-contributions'], sourceConcepts: ['place-value-and-groups'],
    answer: { expected: '40000', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نحسب قيمة الرقم في كل من المنزلتين ثم نطرح الأصغر من الأكبر.')), steps: [rich(text('الرقم '), math('4'), text(' في عشرات الآلاف قيمته '), math('40,000'), text('.')), rich(text('منزلة الآلاف تحمل الرقم '), math('0'), text('، فقيمتها '), math('0'), text('.')), rich(math('40,000−0=40,000'))], finalAnswer: rich(math('40,000')) },
    originalityNote: 'يقارن مساهمتين منزليتين داخل العدد ويحسب الفرق بينهما؛ لا يملأ حداً مفقوداً في صيغة تفصيلية كما يفعل السؤال الختامي.',
  }),
  q(8, {
    type: 'ordering', difficulty: 'medium',
    prompt: rich(text('رتّب الأعداد من الأصغر إلى الأكبر بمقارنة مجموعاتها ثم منازلها.')),
    concepts: ['number-comparison', 'number-groups'], skills: ['compare-large-numbers', 'order-standard-numerals'], sourceConcepts: ['place-value-and-groups'],
    items: [option('q08-a', math('4,305,018')), option('q08-b', math('4,350,018')), option('q08-c', math('3,950,900')), option('q08-d', math('4,035,180'))],
    answer: ['q08-c', 'q08-d', 'q08-a', 'q08-b'],
    solution: { idea: rich(text('نقارن من اليسار، وننتقل إلى المنزلة التالية عند التعادل.')), steps: [rich(text('العدد '), math('3,950,900'), text(' أصغر لأن مجموعة الملايين فيه '), math('3'), text(' بدلاً من '), math('4'), text('.')), rich(text('بين الأعداد الباقية تتساوى الملايين؛ تقارن مجموعة الآلاف ثم بقية المنازل: '), math('035<305<350'), text('.'))], finalAnswer: rich(math('3,950,900<4,035,180<4,305,018<4,350,018')) },
    originalityNote: 'ترتيب أربعة أعداد يتطلب الانتقال بين مجموعات الملايين والآلاف ثم المنازل؛ يختلف عن أسئلة كتابة رقم لفظي أو قيمة رقم مفرد.',
  }),
  q(9, {
    type: 'matching', difficulty: 'medium',
    prompt: rich(text('طابق كل وصف لمجموعة عددية بالصيغة القياسية التي تحقق الوصف.')),
    concepts: ['number-groups', 'standard-form'], skills: ['translate-group-description-to-numeral'], sourceConcepts: ['word-standard-expanded-forms'],
    left: [optionText('q09-l1', '4 ملايين، و7 آلاف، و30'), optionText('q09-l2', 'مليونان، و50 ألفاً، و8'), optionText('q09-l3', '6 ملايين، و300 ألف، و40 ألفاً، و2')],
    right: [option('q09-r1', math('2,050,008')), option('q09-r2', math('6,340,002')), option('q09-r3', math('4,007,030'))],
    answer: [{ leftId: 'q09-l1', rightId: 'q09-r3' }, { leftId: 'q09-l2', rightId: 'q09-r1' }, { leftId: 'q09-l3', rightId: 'q09-r2' }],
    solution: { idea: rich(text('نضع كل مجموعة في منزلتها ونستخدم الأصفار لحفظ الخانات غير المذكورة.')), steps: [rich(text('4 ملايين و7 آلاف و30 تكتب '), math('4,007,030'), text('.')), rich(text('مليونان و50 ألفاً و8 تكتب '), math('2,050,008'), text('.')), rich(text('6 ملايين و340 ألفاً و2 تكتب '), math('6,340,002'), text('.'))], finalAnswer: rich(text('الوصف الأول: الخيار الثالث؛ الثاني: الأول؛ الثالث: الثاني.')) },
    originalityNote: 'مطابقة وصف مجموعات لفظية بثلاث كتابات قياسية جديدة؛ لا تستعمل العدد اللفظي المتكرر في الاختبار الختامي.',
  }),
  q(10, {
    type: 'multi-select', difficulty: 'medium',
    prompt: rich(text('في العدد '), math('4,072,050'), text('، اختر كل عبارة صحيحة عن الخانات والمجموعات.')),
    concepts: ['place-value', 'zero-placeholders', 'number-groups'], skills: ['analyze-digit-positions', 'interpret-zero-placeholders'], sourceConcepts: ['place-value-and-groups', 'zeros-hold-place'],
    options: [optionText('q10-a', 'الرقم 7 في منزلة عشرات الآلاف'), optionText('q10-b', 'مجموعة الوحدات هي 050'), optionText('q10-c', 'الرقم 4 قيمته 4,000,000'), optionText('q10-d', 'الصفر في المئات يجعل مجموعة الوحدات تُحذف')],
    answer: ['q10-a', 'q10-b', 'q10-c'],
    solution: { idea: rich(text('نحدد المجموعة ثم المنزلة داخلها، ولا نحذف مجموعة تحتوي أصفاراً.')), steps: [rich(text('في مجموعة الآلاف '), math('072'), text(' يقع '), math('7'), text(' في منزلة عشرات الآلاف.')), rich(text('المجموعة اليمنى '), math('050'), text(' تبقى مكتوبة للمحافظة على الخانات.')), rich(text('الرقم '), math('4'), text(' في الملايين فقيمته '), math('4,000,000'), text('.'))], finalAnswer: rich(text('A وB وC صحيحة؛ D خاطئة.')) },
    originalityNote: 'يفحص ثلاث حقائق متزامنة في عدد واحد ذي أصفار داخلية، وليس اختيار تحليل تفصيلي معروض لعدد نهائي سابق.',
  }),
  q(11, {
    type: 'error-analysis', difficulty: 'medium',
    prompt: rich(text('كتب سامر أن '), math('5,084,006=5,000,000+80,000+4,000+6'), text('، لكنه قال إن الصفر في المئات يعني حذف مجموعة الوحدات. حدّد الخطأ والتصحيح.')),
    concepts: ['zero-placeholders', 'expanded-form'], skills: ['diagnose-place-value-omission', 'explain-zero-placeholder'], sourceConcepts: ['zeros-hold-place', 'expanded-standard-forms'],
    coverage: { commonErrors: ['delete-zero-group'] },
    studentWork: rich(math('5,084,006=5,000,000+80,000+4,000+6')),
    diagnoses: [optionText('q11-d1', 'المجموع المكتوب لا يعيد تركيب العدد كاملاً'), optionText('q11-d2', 'الصفر يعني حذف مجموعة الوحدات من العدد القياسي')],
    corrections: [optionText('q11-c1', 'نحتفظ بالمجموعة 006 ويظل حد الآحاد 6 في التفصيل'), optionText('q11-c2', 'نحذف المجموعة الأخيرة لأن المئات فيها صفر')],
    answer: { diagnosisId: 'q11-d2', correctionId: 'q11-c1' },
    solution: { idea: rich(text('الصفر في المئات لا يلغي الآحاد؛ وتبقى المجموعة الأخيرة ذات الخانات الثلاث.')), steps: [rich(text('العدد ينتهي بالمجموعة '), math('006'), text('، أي ستة آحاد مع أصفار حافظة للمئات والعشرات.')), rich(text('المجموع المكتوب صحيح، لكن تفسير حذف مجموعة الوحدات هو الخطأ.'))], finalAnswer: rich(text('التشخيص: D2؛ والتصحيح: اترك حد الآحاد '), math('6'), text(' في التفصيل.')), commonError: rich(text('اعتبار وجود صفر في خانة واحدة سبباً لإسقاط المجموعة أو الأرقام المجاورة.')) },
    originalityNote: 'يفصل بين صحة التفصيل وخطأ تفسير وظيفة الصفر في المجموعة الأخيرة؛ هذا تحليل مزدوج لا ينسخ تمرين تصحيح تفصيل عددي سابق.',
  }),
  q(12, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('عند كتابة '), math('7,206,040'), text(' كمجموع لقيم منازله غير الصفرية، كم حداً غير صفرياً يظهر؟')),
    concepts: ['expanded-form', 'place-value'], skills: ['count-nonzero-place-value-terms'], sourceConcepts: ['expanded-standard-forms', 'zeros-hold-place'],
    answer: { expected: '4', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('لا نضيف حداً قيمته صفر، لكن لا نحذف الخانات الصفرية من العدد القياسي.')), steps: [rich(text('التفصيل هو '), math('7,000,000+200,000+6,000+40'), text('.')), rich(text('توجد أربعة حدود غير صفرية.'))], finalAnswer: rich(math('4')) },
    originalityNote: 'يطلب عدد الحدود غير الصفرية في التفصيل بدلاً من كتابة التفصيل نفسه؛ يعزل فهم الخانات الصفرية في بنية مختلفة.',
  }),
  q(13, {
    type: 'single-choice', difficulty: 'medium',
    prompt: rich(text('إذا أسقطت ندى قيمة الرقم '), math('3'), text(' من التفصيل الصحيح للعدد '), math('9,030,208'), text('، فأي مجموع تمثله الحدود الباقية؟')),
    concepts: ['expanded-form', 'place-value'], skills: ['analyze-omitted-place-value', 'recompose-number-from-place-values'], sourceConcepts: ['expanded-standard-forms', 'recompose-to-check'],
    options: [option('q13-a', math('9,000,208')), option('q13-b', math('9,030,208')), option('q13-c', math('9,030,008')), option('q13-d', math('9,000,028'))],
    answer: 'q13-a',
    solution: { idea: rich(text('نحدد قيمة الحد الذي أُسقط ثم نعيد تركيب ما بقي من المنازل.')), steps: [rich(text('الرقم '), math('3'), text(' في عشرات الآلاف، فقيمته '), math('30,000'), text('.')), rich(text('بعد حذف هذا الحد تبقى '), math('9,000,000+200+8=9,000,208'), text('.'))], finalAnswer: rich(math('9,000,208')) },
    originalityNote: 'يستنتج العدد الذي تمثله حدود ناقصة بعد إسقاط قيمة منزلية محددة؛ يختلف عن اختيار الصيغة التفصيلية الصحيحة لعدد كامل.',
  }),
  q(14, {
    type: 'error-analysis', difficulty: 'advanced',
    prompt: rich(text('قال طالب إن العبارة «ثلاثة ملايين وأربعة آلاف وخمسة» تكتب '), math('3,040,005'), text('. اختر التشخيص والتصحيح المناسبين.')),
    concepts: ['number-groups', 'word-form', 'standard-form'], skills: ['diagnose-group-placement', 'translate-spoken-groups-to-standard-form'], sourceConcepts: ['place-value-and-groups', 'word-standard-expanded-forms'],
    coverage: { commonErrors: ['misplace-digit-in-number-group'] },
    studentWork: rich(text('ثلاثة ملايين وأربعة آلاف وخمسة '), math('→ 3,040,005')),
    diagnoses: [optionText('q14-d1', 'وضع الأربعة في مجموعة عشرات الآلاف بدلاً من مجموعة الآلاف'), optionText('q14-d2', 'أهمل مجموعة الملايين')],
    corrections: [option('q14-c1', math('3,004,005')), option('q14-c2', math('3,040,005'))],
    answer: { diagnosisId: 'q14-d1', correctionId: 'q14-c1' },
    solution: { idea: rich(text('نقسم العدد المنطوق إلى مجموعات: ملايين، ثم آلاف، ثم وحدات.')), steps: [rich(text('ثلاثة ملايين هي المجموعة '), math('3'), text('.')), rich(text('أربعة آلاف تكتب في مجموعة الآلاف '), math('004'), text('، وخمسة تكتب في مجموعة الوحدات '), math('005'), text('.')), rich(text('إذن التجميع الصحيح '), math('3 | 004 | 005'), text(' يكتب '), math('3,004,005'), text('.'))], finalAnswer: rich(text('التشخيص: إزاحة الأربعة إلى عشرات الآلاف؛ والتصحيح: '), math('3,004,005'), text('.')), commonError: rich(text('وضع الرقم في منزلة أو مجموعة مجاورة عند تحويل العبارة اللفظية إلى عدد قياسي.')) },
    originalityNote: 'يشخّص خطأ نقل مجموعة لفظية إلى موضع مجاور عند بناء الصيغة القياسية؛ يبتعد عن سؤال الاختبار الختامي في تحليل مجموع قيم منازل.',
  }),
  q(15, {
    type: 'numeric', difficulty: 'advanced',
    prompt: rich(text('عدد من سبع خانات فيه '), math('4'), text(' في الملايين، و'), math('2'), text(' في عشرات الآلاف، و'), math('6'), text(' في المئات، وبقية أرقامه صفراً. ما كتابته القياسية؟')),
    concepts: ['place-value', 'zero-placeholders'], skills: ['construct-standard-form-from-place-clues'], sourceConcepts: ['place-value-and-groups', 'zeros-hold-place'],
    answer: { expected: '4020600', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نضع كل رقم في منزلته المحددة، ثم نملأ الخانات غير المذكورة بالأصفار.')), steps: [rich(text('الملايين: '), math('4'), text('؛ مئات الآلاف: '), math('0'), text('؛ عشرات الآلاف: '), math('2'), text('.')), rich(text('الآلاف والمئات والعشرات والآحاد: '), math('0,6,0,0'), text('.'))], finalAnswer: rich(math('4,020,600')) },
    originalityNote: 'يعيد بناء عدد كامل من ثلاثة أدلة منزليّة ويستخدم أصفاراً متعددة، لا يملأ خانة ناقصة في عدد معطى كما في الاختبار الختامي.',
  }),
  q(16, {
    type: 'matching', difficulty: 'advanced',
    prompt: rich(text('طابق كل صيغة لفظية مختصرة مع كتابتها العددية الدقيقة، مع الانتباه إلى المجموعات الخالية.')),
    concepts: ['word-form', 'number-groups', 'zero-placeholders'], skills: ['translate-spoken-groups-to-standard-form', 'preserve-empty-groups'], sourceConcepts: ['word-standard-expanded-forms', 'zeros-hold-place'],
    left: [optionText('q16-l1', 'سبعة ملايين وأربعة آلاف وتسعة'), optionText('q16-l2', 'ثلاثة ملايين ومئتا ألف وخمسون'), optionText('q16-l3', 'مليونان وستون ألفاً وسبعمئة')],
    right: [option('q16-r1', math('2,060,700')), option('q16-r2', math('7,004,009')), option('q16-r3', math('3,200,050'))],
    answer: [{ leftId: 'q16-l1', rightId: 'q16-r2' }, { leftId: 'q16-l2', rightId: 'q16-r3' }, { leftId: 'q16-l3', rightId: 'q16-r1' }],
    solution: { idea: rich(text('نضع كل مجموعة لفظية في موضعها ونكتب أصفاراً للمنازل التي لم تذكر.')), steps: [rich(text('سبعة ملايين، وأربعة آلاف، وتسعة آحاد: '), math('7,004,009'), text('.')), rich(text('ثلاثة ملايين ومئتا ألف وخمسون: '), math('3,200,050'), text('.')), rich(text('مليونان وستون ألفاً وسبعمئة: '), math('2,060,700'), text('.'))], finalAnswer: rich(text('الأول: الخيار الثاني؛ الثاني: الثالث؛ الثالث: الأول.')) },
    originalityNote: 'مطابقة ثلاث عبارات مجموعات جديدة إلى أعداد مع فجوات صفرية مختلفة؛ لا تعيد سؤال تحويل عدد مفرد إلى كلمات.',
  }),
  q(17, {
    type: 'multi-select', difficulty: 'advanced',
    prompt: rich(text('أي العبارات الآتية تكتب قيمة الرقم '), math('5'), text(' في العدد '), math('5,050,005'), text(' أو تحدد موضعه بدقة؟ اختر كل ما يصح.')),
    concepts: ['place-value', 'number-groups'], skills: ['distinguish-repeated-digit-values', 'locate-digit-occurrences'], sourceConcepts: ['place-value-and-groups'],
    options: [optionText('q17-a', 'الرقم 5 الأول قيمته 5,000,000'), optionText('q17-b', 'الرقم 5 في مجموعة الآلاف يقع في عشرات الآلاف'), optionText('q17-c', 'كل رقم 5 في العدد له القيمة نفسها'), optionText('q17-d', 'الرقم 5 الأخير يقع في الآحاد')],
    answer: ['q17-a', 'q17-b', 'q17-d'],
    solution: { idea: rich(text('تتغير قيمة الرقم نفسه بتغير المنزلة التي يشغلها.')), steps: [rich(text('تظهر الأرقام '), math('5'), text(' في الملايين وعشرات الآلاف والآحاد.')), rich(text('قيمها على الترتيب '), math('5,000,000'), text(' و'), math('50,000'), text(' و'), math('5'), text('.'))], finalAnswer: rich(text('A وB وD صحيحة؛ C خاطئة.')) },
    originalityNote: 'يقارن ثلاث ظهورات للرقم نفسه في منازل متباعدة، بدلاً من السؤال الختامي عن قيمة رقم واحد في عدد آخر.',
  }),
  q(18, {
    type: 'single-choice', difficulty: 'thinking',
    prompt: rich(text('عند مقارنة '), math('6,405,021'), text(' و'), math('6,450,021'), text('، أي تفسير يحدد سبب كون أحدهما أكبر من الآخر؟')),
    concepts: ['number-comparison', 'place-value'], skills: ['justify-comparison-at-first-difference'], sourceConcepts: ['place-value-and-groups'],
    coverage: { thinking: ['first-different-place-reasoning'] },
    options: [optionText('q18-a', 'الملايين ومئات الآلاف متساوية، لكن عشرات الآلاف 5 أكبر من 0'), optionText('q18-b', 'الأول أكبر لأن فيه أصفاراً أقل'), optionText('q18-c', 'العددان متساويان لأن مجموعة الآلاف تبدأ بالرقم 4'), optionText('q18-d', 'الثاني أصغر لأن رقمه الأخير أكبر')],
    answer: 'q18-a',
    solution: { idea: rich(text('نقارن المنازل من الأكبر إلى الأصغر، ونتوقف عند أول اختلاف.')), steps: [rich(text('الملايين متساوية، ومئات الآلاف متساوية.')), rich(text('في عشرات الآلاف يظهر '), math('0'), text(' في العدد الأول و'), math('5'), text(' في الثاني.')), rich(text('إذن العدد الثاني أكبر.'))], finalAnswer: rich(math('6,405,021<6,450,021')) },
    originalityNote: 'يطلب تبرير المقارنة من أول منزلة مختلفة بدلاً من ترتيب مجموعة أعداد كاملة أو حساب قيمة رقم منفرد.',
  }),
  q(19, {
    type: 'ordering', difficulty: 'thinking',
    prompt: rich(text('رتّب بطاقات القيم من الأصغر إلى الأكبر، واستعمل أول منزلة مختلفة لتبرير موضع البطاقة الوسطى.')),
    concepts: ['number-comparison', 'place-value'], skills: ['order-numbers-by-first-difference', 'justify-middle-value'], sourceConcepts: ['place-value-and-groups'],
    coverage: { thinking: ['multi-number-place-value-reasoning'] },
    items: [option('q19-a', math('8,104,090')), option('q19-b', math('8,140,009')), option('q19-c', math('8,014,900'))],
    answer: ['q19-c', 'q19-a', 'q19-b'],
    solution: { idea: rich(text('عند تساوي الملايين، نقارن مجموعة الآلاف ومنازلها بالتتابع.')), steps: [rich(text('كل الأعداد تبدأ بثمانية ملايين.')), rich(text('مجموعة الآلاف هي '), math('014'), text(' ثم '), math('104'), text(' ثم '), math('140'), text('؛ وهذا يحسم الترتيب.')), rich(text('لذلك تقع البطاقة ذات مجموعة الآلاف '), math('104'), text(' في الوسط.'))], finalAnswer: rich(math('8,014,900<8,104,090<8,140,009')) },
    originalityNote: 'استدلال متسلسل لثلاثة أعداد متقاربة مع تبرير العنصر الأوسط؛ يختلف عن مسألة اختيار مقارنة ثنائية.',
  }),
  q(20, {
    type: 'error-analysis', difficulty: 'thinking',
    prompt: rich(text('قالت هدى عن العدد '), math('2,006,040'), text(': «أحذف الصفرين اللذين يسبقان 6 في مجموعة الآلاف، فأكتب '), math('26,040'), text(' من دون أن تتغير القيمة». اختر تشخيص الخطأ والتصحيح.')),
    concepts: ['zero-placeholders', 'number-groups', 'standard-form'], skills: ['evaluate-placeholder-removal', 'preserve-digit-position'], sourceConcepts: ['zeros-hold-place', 'recompose-to-check'],
    coverage: { thinking: ['reason-about-placeholder-preservation'], commonErrors: ['remove-internal-zeroes'] },
    studentWork: rich(math('2,006,040 \u2192 26,040')),
    diagnoses: [optionText('q20-d1', 'حذف الأصفار الداخلية يغيّر تجميع الخانات وقيمة العدد'), optionText('q20-d2', 'الأصفار لا تستخدم إلا في نهاية العدد')],
    corrections: [option('q20-c1', math('2,006,040')), option('q20-c2', math('26,040'))],
    answer: { diagnosisId: 'q20-d1', correctionId: 'q20-c1' },
    solution: { idea: rich(text('الأصفار تحفظ مواضع المجموعات حتى عندما لا تمثل حدوداً غير صفرية في التفصيل.')), steps: [rich(text('في '), math('2,006,040'), text(' مجموعة الآلاف هي '), math('006'), text('؛ لذلك قيمة الرقم '), math('6'), text(' فيها ستة آلاف.')), rich(text('حذف الصفرين يجعل تجميع الخانات يتغير، فلا تبقى الكتابة '), math('26,040'), text(' مساوية للعدد الأصلي.'))], finalAnswer: rich(text('التشخيص الأول؛ والتصحيح هو '), math('2,006,040'), text('.')), commonError: rich(text('حذف الأصفار الحافظة للمجموعات ثم افتراض أن القيمة لم تتغير.')) },
    originalityNote: 'يقيم ادعاءً عاماً عن حذف الأصفار الداخلية ويشرح أثره على مواضع الخانات؛ لا يعيد سؤالاً عن تفصيل عدد بعينه.',
  }),
]

const definition = defineLessonTest({
  id: testId,
  lessonId,
  title: 'اختبار الأعداد الطبيعية والقيمة المنزلية',
  description: rich(text('يقيس هذا الاختبار قراءة الأعداد إلى الملايين، وفهم المجموعات والخانات، والتحويل بين الصيغ والتحقق بإعادة تركيب القيم.')),
  instructions: rich(text('انتبه إلى موضع كل رقم وإلى الأصفار الحافظة للخانات. في أسئلة المطابقة استخدم كل خيار مرة واحدة، وفي الاختيار المتعدد حدّد جميع الإجابات الصحيحة.')),
  questions,
  sourceConcepts: [
    { id: 'place-value-and-groups', label: 'القيمة المنزلية وتقسيم الأعداد إلى مجموعات من ثلاث خانات', pages: [10, 11, 12] },
    { id: 'expanded-standard-forms', label: 'الصيغ القياسية والتفصيلية وإعادة تركيب العدد', pages: [10, 11, 12, 13] },
    { id: 'word-standard-expanded-forms', label: 'التحويل بين الصيغة اللفظية والقياسية والتفصيلية', pages: [10, 11, 12, 13] },
    { id: 'zeros-hold-place', label: 'الصفر الحافظ للخانة في العدد القياسي والمجموعات', pages: [11, 12, 13] },
    { id: 'recompose-to-check', label: 'التحقق من الكتابة بجمع قيم المنازل', pages: [12, 13] },
  ],
  conceptLabels: {
    'place-value': 'قيمة الرقم بحسب منزلته',
    'number-groups': 'مجموعات الملايين والآلاف والوحدات',
    'zero-placeholders': 'الأصفار الحافظة لمواضع الأرقام',
    'expanded-form': 'تفكيك العدد إلى مجموع قيم المنازل',
    'number-comparison': 'مقارنة الأعداد بحسب المنازل والمجموعات',
    'standard-form': 'الكتابة القياسية للعدد',
    'word-form': 'قراءة المجموعات في الصيغة اللفظية',
  },
  skillLabels: {
    'identify-digit-place': 'تسمية منزلة رقم ضمن المجموعة العددية',
    'group-digits-by-threes': 'تقسيم الأرقام إلى مجموعات ثلاثية',
    'count-zero-digits': 'عدّ الأصفار الظاهرة في الصيغة القياسية',
    'read-standard-form': 'قراءة عدد مكتوب بالأرقام',
    'identify-three-digit-groups': 'تحديد مجموعة الملايين والآلاف والوحدات',
    'recompose-number-from-place-values': 'إعادة تكوين العدد من قيم المنازل',
    'verify-number-by-recomposition': 'التحقق من مساواة عدد بإعادة جمع حدوده',
    'compare-place-value-contributions': 'مقارنة قيم رقمين بحسب منزلتيهما',
    'compare-large-numbers': 'مقارنة الأعداد الكبيرة من اليسار إلى اليمين',
    'order-standard-numerals': 'ترتيب كتابات قياسية بحسب القيمة',
    'translate-group-description-to-numeral': 'تحويل وصف المجموعات إلى كتابة قياسية',
    'analyze-digit-positions': 'تحليل مواضع الأرقام داخل مجموعاتها',
    'interpret-zero-placeholders': 'تفسير وظيفة الصفر في حفظ المنزلة',
    'diagnose-place-value-omission': 'كشف حذف أو تفسير خاطئ لخانة',
    'explain-zero-placeholder': 'شرح أثر الصفر في حفظ مجموعة العدد',
    'count-nonzero-place-value-terms': 'عد الحدود غير الصفرية في التفصيل',
    'select-equivalent-expanded-form': 'اختيار تحليل مكافئ للصيغة القياسية',
    'analyze-omitted-place-value': 'تحليل أثر إسقاط قيمة منزلة من المجموع',
    'diagnose-group-placement': 'كشف نقل مجموعة عددية إلى موضع مجاور',
    'construct-standard-form-from-place-clues': 'بناء عدد قياسي من دلائل منازل',
    'translate-spoken-groups-to-standard-form': 'ترجمة مجموعات لفظية إلى عدد قياسي',
    'preserve-empty-groups': 'حفظ المجموعات الخالية باستخدام الأصفار',
    'distinguish-repeated-digit-values': 'التمييز بين قيم ظهورات الرقم نفسه',
    'locate-digit-occurrences': 'تحديد منازل ظهورات رقم متكرر',
    'justify-comparison-at-first-difference': 'تبرير المقارنة عند أول منزلة مختلفة',
    'order-numbers-by-first-difference': 'ترتيب أعداد بحسب أول اختلاف منزلي',
    'justify-middle-value': 'تفسير موقع العدد الأوسط بعد الترتيب',
    'evaluate-placeholder-removal': 'تقويم ادعاء حذف أصفار داخلية',
    'preserve-digit-position': 'المحافظة على مواضع الأرقام في الصيغة القياسية',
  },
  thinkingLabels: {
    'first-different-place-reasoning': 'التوقف عند أول منزلة مختلفة لتبرير المقارنة',
    'multi-number-place-value-reasoning': 'ترتيب عدة أعداد متقاربة بمقارنة المجموعات',
    'reason-about-placeholder-preservation': 'تفسير أثر حذف الصفر الحافظ للخانة',
  },
  commonErrorLabels: {
    'delete-zero-group': 'حذف مجموعة الوحدات أو الخلط بين صفر الخانة والمجموعة',
    'misplace-digit-in-number-group': 'نقل مجموعة لفظية إلى منزلة مجاورة عند تكوين العدد القياسي',
    'remove-internal-zeroes': 'حذف الأصفار الداخلية وإزاحة قيم المنازل',
  },
})

export default definition
