import { defineLessonTest, lessonQuestion, math, rich, text, textOnly, type LessonQuestionDraft } from '../../lessonTestBuilder'
import type { QuestionDefinition } from '../../types'

const testId = 'lesson-parallelogram-test'
const lessonId = 'parallelogram'
const qid = (number: number) => `${testId}-q${String(number).padStart(2, '0')}`
const q = (number: number, draft: LessonQuestionDraft) =>
  lessonQuestion(testId, lessonId, qid(number), draft)
const option = (id: string, ...runs: Parameters<typeof rich>) => ({ id, label: rich(...runs) })
const optionText = (id: string, value: string) => ({ id, label: textOnly(value) })

const questions: QuestionDefinition[] = [
  q(1, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('أي وصف يطابق تعريف متوازي الأضلاع كما تعلمته؟')),
    concepts: ['parallelogram-definition'], skills: ['state-parallelogram-definition'], sourceConcepts: ['definition-and-shape-examples'],
    options: [optionText('q01-a', 'شكل رباعي فيه كل ضلعين متقابلين متوازيان'), optionText('q01-b', 'شكل رباعي فيه زوج واحد فقط من الأضلاع المتوازية'), optionText('q01-c', 'شكل رباعي أضلاعه الأربعة متساوية دائماً'), optionText('q01-d', 'شكل رباعي له زاوية قائمة واحدة على الأقل')],
    answer: 'q01-a',
    solution: { idea: rich(text('جوهر التعريف هو وجود زوجين من الأضلاع المتقابلة المتوازية.')), steps: [rich(text('ننظر إلى كل زوج من الأضلاع المتقابلة.')), rich(text('يجب أن يكون الزوجان متوازيين، لا زوجاً واحداً فقط.'))], finalAnswer: rich(text('الخيار الأول: شكل رباعي فيه كل ضلعين متقابلين متوازيان.')) },
    originalityNote: 'يعيد بناء التعريف في بدائل متمايزة بين شرط الزوجين وشرط الزوج الواحد أو تساوي الأضلاع، لا يقتبس سؤالاً عددياً من الكتاب.',
  }),
  q(2, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('المستطيل مثال على متوازي الأضلاع؛ لأن كل زوج من أضلاعه المتقابلة متوازٍ.')),
    concepts: ['special-parallelograms', 'parallelogram-definition'], skills: ['recognize-rectangle-as-parallelogram'], sourceConcepts: ['definition-and-shape-examples'],
    answer: true,
    solution: { idea: rich(text('يحقق المستطيل شرط التوازي في الزوجين المتقابلين، لذلك يندرج ضمن متوازيات الأضلاع.')), steps: [rich(text('في الشكل الرباعي المستطيل يتوازى كل ضلع مع الضلع المقابل له.')), rich(text('إذن تنطبق عليه قاعدة التعريف.'))], finalAnswer: rich(text('صحيح.')) },
    originalityNote: 'يطبق التعريف على حالة خاصة من الأشكال بدلاً من طلب تسمية متوازي الأضلاع أو إعادة مثال الشكل ذي الحروف نفسها.',
  }),
  q(3, {
    type: 'matching', difficulty: 'basic',
    prompt: rich(text('تتبّع ترتيب الرؤوس حول الرباعي '), math('ABCD'), text('، ثم طابق كل زوج مع الجزء الذي يمثله.')),
    concepts: ['diagonal-definition', 'parallelogram-parts'], skills: ['distinguish-side-vertex-and-diagonal'], sourceConcepts: ['diagonal-and-quadrilateral-parts'],
    left: [option('q03-l1', math('A,B')), option('q03-l2', math('A,C')), option('q03-l3', math('C,D'))],
    right: [optionText('q03-r1', 'طرفا الضلع AB على حد الشكل'), optionText('q03-r2', 'رأسان متقابلان يصل بينهما قطر داخل الشكل'), optionText('q03-r3', 'طرفا الضلع CD على حد الشكل')],
    answer: [{ leftId: 'q03-l1', rightId: 'q03-r1' }, { leftId: 'q03-l2', rightId: 'q03-r2' }, { leftId: 'q03-l3', rightId: 'q03-r3' }],
    solution: { idea: rich(text('نستخدم ترتيب الرؤوس حول الحد للتمييز بين زوج متجاور وزوج متقابل.')), steps: [rich(math('A,B'), text(' متجاوران ويحددان الضلع '), math('AB'), text('.')), rich(math('A,C'), text(' رأسان متقابلان، والقطعة بينهما تمر داخل الرباعي.')), rich(math('C,D'), text(' متجاوران ويحددان الضلع '), math('CD'), text('.'))], finalAnswer: rich(text('AB: طرفا ضلع؛ AC: قطر داخلي؛ CD: طرفا ضلع.')) },
    originalityNote: 'يطبق ترتيب الرؤوس على ثلاثة أزواج محددة في رباعي جديد بدلاً من إعادة سؤال تعريف القطر بصياغة مباشرة.',
  }),
  q(4, {
    type: 'multi-select', difficulty: 'basic',
    prompt: rich(text('في متوازي الأضلاع '), math('ABCD'), text('، اختر كل خاصية صحيحة دائماً بحسب الدرس.')),
    concepts: ['opposite-sides-parallel-equal', 'opposite-angles-equal'], skills: ['identify-guaranteed-properties'], sourceConcepts: ['opposite-side-properties', 'opposite-angle-property'],
    options: [option('q04-a', math('AB∥CD')), option('q04-b', math('AB=CD')), option('q04-c', math('∠A=∠C')), option('q04-d', math('AB=BC')), option('q04-e', math('∠A=∠B'))],
    answer: ['q04-a', 'q04-b', 'q04-c'],
    solution: { idea: rich(text('الخاصتان اللتان يدرسهما الشكل تتعلقان بالأضلاع والزوايا المتقابلة.')), steps: [rich(text('الأضلاع المتقابلة متوازية ومتساوية، لذا '), math('AB∥CD'), text(' و'), math('AB=CD'), text('.')), rich(text('والزاويتان المتقابلتان متساويتان، لذا '), math('∠A=∠C'), text('.')), rich(text('لا يلزم أن يتساوى كل ضلعين متجاورين أو كل زاويتين متجاورتين.'))], finalAnswer: rich(text('العبارات الأولى والثانية والثالثة صحيحة.')) },
    originalityNote: 'يتطلب فرز خصائص متقابلة عن خصائص متجاورة في شكل مسمى جديد؛ لا يكرر اختبار قياس زاويتين محددتين.',
  }),
  q(5, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('كل متوازي أضلاع له أربعة أضلاع متساوية في الطول.')),
    concepts: ['opposite-sides-parallel-equal', 'special-parallelograms'], skills: ['distinguish-opposite-equality-from-all-sides-equal'], sourceConcepts: ['opposite-side-properties', 'definition-and-shape-examples'],
    answer: false,
    solution: { idea: rich(text('الخاصية العامة تساوي كل ضلعين متقابلين، ولا تفرض تساوي الأضلاع المتجاورة.')), steps: [rich(text('في متوازي الأضلاع يتساوى كل زوج متقابل.')), rich(text('قد تكون الأضلاع المتجاورة مختلفة، كما يمكن أن يكون الشكل مستطيلاً غير مربع.'))], finalAnswer: rich(text('خطأ؛ المتساويان بالضرورة هما كل ضلعين متقابلين.')) },
    originalityNote: 'يفصل بين التساوي المتقابل وتساوي الأضلاع الأربعة، مستنداً إلى أمثلة المستطيل والمعين لا إلى أبعاد سؤال ختامي.',
  }),
  q(6, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('أي شكل رباعي يحقق تعريف متوازي الأضلاع من المعلومات الآتية؟')),
    concepts: ['parallelogram-definition'], skills: ['classify-quadrilateral-from-parallel-pairs'], sourceConcepts: ['definition-and-shape-examples'],
    options: [optionText('q06-a', 'فيه زوجان من الأضلاع المتقابلة المتوازية'), optionText('q06-b', 'فيه زوج واحد فقط من الأضلاع المتوازية'), optionText('q06-c', 'له ضلعان متساويان متجاوران فقط'), optionText('q06-d', 'له زاويتان متساويتان فقط')],
    answer: 'q06-a',
    solution: { idea: rich(text('يجب أن يتحقق التوازي في كلا الزوجين المتقابلين.')), steps: [rich(text('نستبعد وصف الزوج الواحد لأنه لا يفي بكلمة «كل» في التعريف.')), rich(text('أما تساوي ضلعين أو زاويتين وحده فلا يثبت شرط التوازي.'))], finalAnswer: rich(text('الشكل ذو زوجين متقابلين متوازيين.')) },
    originalityNote: 'اختيار من معلومات وصفية ناقصة وكاملة لتطبيق التعريف؛ لا يعيد السؤال الختامي عن رسم مسمى أو قياس ضلع.',
  }),
  q(7, {
    type: 'ordering', difficulty: 'medium',
    prompt: rich(text('رتّب خطوات إنشاء متوازي أضلاع بمسطرة ومنقلة عندما تُعطى أطوال ضلعين متجاورين والزاوية المحصورة.')),
    concepts: ['parallelogram-construction'], skills: ['sequence-ruler-protractor-construction'], sourceConcepts: ['construction-with-ruler-and-protractor'],
    items: [optionText('q07-a', 'من الرأس الثالث ارسم الضلع المقابل موازياً للأول وبطول يساويه، في الاتجاه الذي يغلق رباعياً غير متقاطع'), optionText('q07-b', 'ارسم الضلع الأول بالطول المعطى وحدد رأسه'), optionText('q07-c', 'أنشئ الزاوية المعطاة عند أحد طرفي الضلع'), optionText('q07-d', 'قِس طول الضلع المجاور على الشعاع الجديد وحدد النقطة الثالثة'), optionText('q07-e', 'صِل الطرفين الباقيين بالضلع الأخير لإغلاق الشكل الرباعي')],
    answer: ['q07-b', 'q07-c', 'q07-d', 'q07-a', 'q07-e'],
    solution: { idea: rich(text('تحدد الأطوال والزاوية ضلعين متجاورين أولاً، ثم تستخدم خاصية التوازي وتساوي الأضلاع لإكمال الشكل.')), steps: [rich(text('ابدأ بالضلع الأول.')), rich(text('أنشئ الزاوية عند طرفه ثم ضع طول الضلع المجاور على الشعاع.')), rich(text('من الرأس الثالث ارسم الضلع المقابل موازياً للأول وبطول يساويه، في الاتجاه الذي يغلق رباعياً غير متقاطع.')), rich(text('صِل الطرفين الباقيين بالضلع الأخير.'))], finalAnswer: rich(text('الضلع الأول، الزاوية، طول الضلع المجاور، ضلع مقابل موازٍ ومساوٍ للأول في اتجاه الإغلاق، ثم الضلع الأخير.')) },
    originalityNote: 'يرتب طريقة إنشاء كاملة من معطيات وصفية؛ لا ينسخ أطوال أو زاوية مثال الصفحة 34 ولا يسأل عن عدد الأشكال الممكنة مباشرة.',
  }),
  q(8, {
    type: 'error-analysis', difficulty: 'medium',
    prompt: rich(text('في الرباعي '), math('ABCD'), text('، قال طالب إن الضلعين '), math('AB'), text(' و'), math('BC'), text(' متقابلان لأنهما يلتقيان عند '), math('B'), text('. اختر التشخيص والتصحيح.')),
    concepts: ['parallelogram-parts', 'opposite-sides-parallel-equal'], skills: ['diagnose-adjacent-as-opposite', 'identify-opposite-side-pair'], sourceConcepts: ['diagonal-and-quadrilateral-parts', 'opposite-side-properties'],
    coverage: { commonErrors: ['confuse-adjacent-and-opposite-sides'] },
    studentWork: rich(math('AB'), text(' و'), math('BC'), text(' ضلعان متقابلان')),
    diagnoses: [optionText('q08-d1', 'الضلعان يلتقيان عند B، لذلك هما متجاوران لا متقابلان'), optionText('q08-d2', 'كل ضلعين يشتركان في رأس يكونان متقابلين')],
    corrections: [option('q08-c1', math('AB'), text(' يقابل '), math('CD')), option('q08-c2', math('AB'), text(' يقابل '), math('BC'))],
    answer: { diagnosisId: 'q08-d1', correctionId: 'q08-c1' },
    solution: { idea: rich(text('تتحدد المجاورة والتقابل من ترتيب الرؤوس حول الشكل.')), steps: [rich(text('الضلعان '), math('AB'), text(' و'), math('BC'), text(' يشتركان في الرأس '), math('B'), text('، فهما متجاوران.')), rich(text('الضلع المقابل لـ'), math('AB'), text(' هو '), math('CD'), text('.'))], finalAnswer: rich(text('التشخيص: خلط المتجاور بالمتقابل؛ والتصحيح: '), math('AB'), text(' يقابل '), math('CD'), text('.')), commonError: rich(text('اعتبار الضلعين المتجاورين متقابلين لمجرد أنهما يقعان ضمن الرباعي نفسه.')) },
    originalityNote: 'يعالج خطأ في ترتيب الأجزاء حول رباعي، لا حكم كفاية زوج متوازٍ واحد كما في أحد بنود الاختبار النهائي.',
  }),
  q(9, {
    type: 'matching', difficulty: 'medium',
    prompt: rich(text('في متوازي الأضلاع '), math('KLMN'), text('، طابق كل عنصر مع نظيره المتقابل.')),
    concepts: ['opposite-sides-parallel-equal', 'opposite-angles-equal'], skills: ['identify-opposite-parts-by-order'], sourceConcepts: ['opposite-side-properties', 'opposite-angle-property'],
    left: [option('q09-l1', math('KL')), option('q09-l2', math('LM')), option('q09-l3', math('∠K')), option('q09-l4', math('∠L'))],
    right: [option('q09-r1', math('∠N')), option('q09-r2', math('MN')), option('q09-r3', math('∠M')), option('q09-r4', math('KN'))],
    answer: [{ leftId: 'q09-l1', rightId: 'q09-r2' }, { leftId: 'q09-l2', rightId: 'q09-r4' }, { leftId: 'q09-l3', rightId: 'q09-r3' }, { leftId: 'q09-l4', rightId: 'q09-r1' }],
    solution: { idea: rich(text('نتبع ترتيب الرؤوس حول الشكل؛ الرؤوس والأضلاع غير المتجاورة تكون متقابلة.')), steps: [rich(text('الضلع '), math('KL'), text(' يقابله '), math('MN'), text('، و'), math('LM'), text(' يقابله '), math('KN'), text('.')), rich(text('الزاوية '), math('K'), text(' تقابل '), math('M'), text('، والزاوية '), math('L'), text(' تقابل '), math('N'), text('.'))], finalAnswer: rich(math('KL'), text(' مع '), math('MN'), text('؛ '), math('LM'), text(' مع '), math('KN'), text('؛ '), math('K'), text(' مع '), math('M'), text('؛ '), math('L'), text(' مع '), math('N'), text('.')) },
    originalityNote: 'مطابقة أضلاع وزوايا متقابلة في ترتيب رؤوس جديد، لا تعيد تحديد ضلع مقابل واحد في الاختبار السابق.',
  }),
  q(10, {
    type: 'true-false', difficulty: 'medium',
    prompt: rich(text('إذا تغيرت فتحة متوازي الأضلاع مع بقاء طولي الضلعين المتجاورين نفسيهما، فإن محيطه يتغير.')),
    concepts: ['perimeter-and-side-lengths', 'parallelogram-construction'], skills: ['reason-about-perimeter-under-angle-change'], sourceConcepts: ['perimeter-from-adjacent-sides', 'construction-with-ruler-and-protractor'],
    answer: false,
    solution: { idea: rich(text('المحيط يتحدد بأطوال الأضلاع؛ تغيير الزاوية وحده لا يغير أطوالها.')), steps: [rich(text('كل ضلعين متقابلين متساويان في الطول.')), rich(text('مع ثبات الضلعين المتجاورين تبقى الأطوال الأربعة ومجموعها ثابتاً.'))], finalAnswer: rich(text('خطأ؛ المحيط يبقى نفسه ما دامت الأطوال ثابتة.')) },
    originalityNote: 'يربط خاصية الأضلاع بمفهوم المحيط عند تغيير شكل الرسم، لا يطلب جمع طولين كما في سؤال حساب مباشر.',
  }),
  q(11, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('متوازي الأضلاع A له ضلعان متجاوران '), math('8 cm'), text(' و'), math('3 cm'), text('، ومتوازي الأضلاع B له ضلعان متجاوران '), math('7 cm'), text(' و'), math('4 cm'), text('. كم سنتيمتراً يزيد محيط أحدهما على الآخر؟')),
    concepts: ['perimeter-and-side-lengths', 'opposite-sides-parallel-equal'], skills: ['compare-parallelogram-perimeters'], sourceConcepts: ['perimeter-from-adjacent-sides', 'opposite-side-properties'],
    answer: { expected: '0', format: 'integer', unitPolicy: { kind: 'required', acceptedUnits: ['cm', 'سم', 'centimeter', 'centimeters', 'سنتيمتر', 'سنتيمترات'] } },
    solution: { idea: rich(text('نحسب مجموع الأضلاع الأربعة لكل شكل باستعمال تساوي كل ضلعين متقابلين.')), steps: [rich(text('محيط A: '), math('2×(8+3)=22 cm'), text('.')), rich(text('محيط B: '), math('2×(7+4)=22 cm'), text('.')), rich(text('المحيطان متساويان، فالفرق بينهما صفر.'))], finalAnswer: rich(math('0 cm')) },
    originalityNote: 'يقارن محيطي شكلين مختلفي زوجي الأضلاع المتجاورة ليكشف ثبات المجموع عند تساوي مجموعي الضلعين؛ ليس حساب محيط شكل واحد بأبعاد الاختبار النهائي.',
  }),
  q(12, {
    type: 'multi-select', difficulty: 'medium',
    prompt: rich(text('تريد سلمى إنشاء متوازي أضلاع بضلعين متجاورين طولهما '), math('8 cm'), text(' و'), math('3 cm'), text(' والزاوية المحصورة '), math('65°'), text('. اختر كل إجراء أو استنتاج صحيح.')),
    concepts: ['parallelogram-construction', 'opposite-sides-parallel-equal'], skills: ['select-valid-construction-actions', 'apply-included-angle-to-construction'], sourceConcepts: ['construction-with-ruler-and-protractor', 'opposite-side-properties'],
    options: [option('q12-a', text('ترسم ضلعاً أول طوله '), math('8 cm')), option('q12-b', text('تنشئ عند طرفه زاوية '), math('65°'), text(' ثم تحدد '), math('3 cm'), text(' على الشعاع الجديد')), option('q12-c', text('ترسم من الرأس الثالث ضلعاً موازياً للأول وطوله '), math('8 cm'), text('، في الاتجاه الذي يغلق رباعياً غير متقاطع، ثم تصل الطرفين الباقيين')), optionText('q12-d', 'تغيّر الزاوية المحصورة بحرية بعد تثبيتها في المعطيات')],
    answer: ['q12-a', 'q12-b', 'q12-c'],
    solution: { idea: rich(text('تحدد الأطوال ضلعين متجاورين، وتحدد الزاوية اتجاههما؛ ثم تكمل الشكل بخاصية توازي الأضلاع المتقابلة.')), steps: [rich(text('ارسم الضلع الأول بطول '), math('8 cm'), text('.')), rich(text('أنشئ عند طرفه زاوية '), math('65°'), text('، وضع طول '), math('3 cm'), text(' على شعاعها.')), rich(text('من الرأس الثالث ارسم الضلع المقابل موازياً للأول وبطوله '), math('8 cm'), text('، وفي الاتجاه الذي يغلق رباعياً غير متقاطع؛ ثم أغلق الشكل ولا تغيّر الزاوية المعطاة.'))], finalAnswer: rich(text('الإجراءات والاستنتاجات الصحيحة: A وB وC.')) },
    originalityNote: 'يطبق معطيات إنشاء جديدة لترتيب إجراءات صحيحة ويستبعد تغيير زاوية محددة؛ لا يعيد سؤالاً عن كفاية طولين وحدهما.',
  }),
  q(13, {
    type: 'single-choice', difficulty: 'medium',
    prompt: rich(text('ما العبارة الصحيحة عن المستطيل والمعين كما ظهرا ضمن أشكال الدرس؟')),
    concepts: ['special-parallelograms', 'parallelogram-definition'], skills: ['recognize-special-cases'], sourceConcepts: ['definition-and-shape-examples'],
    options: [optionText('q13-a', 'كلاهما حالة من متوازي الأضلاع ما دام كل زوجين متقابلين متوازيين'), optionText('q13-b', 'المستطيل فقط متوازي أضلاع'), optionText('q13-c', 'المعين فقط متوازي أضلاع'), optionText('q13-d', 'لا يمكن أن يكون أي منهما متوازي أضلاع')],
    answer: 'q13-a',
    solution: { idea: rich(text('يعرض الدرس المستطيل والمعين ضمن الأشكال التي تحقق خاصية الزوجين المتقابلين المتوازيين.')), steps: [rich(text('نطبق تعريف متوازي الأضلاع على كل شكل.')), rich(text('كلاهما يحقق التوازي في الزوجين المتقابلين.'))], finalAnswer: rich(text('المستطيل والمعين كلاهما من متوازيات الأضلاع.')) },
    originalityNote: 'يقارن حالتين خاصتين وردتا في تصنيف أشكال صفحة 31، ولا يعيد سؤالاً عن قياس قائم أو تساوي الأضلاع الأربعة.',
  }),
  q(14, {
    type: 'single-choice', difficulty: 'advanced',
    prompt: rich(text('يمثل الرسمان شكلين لهما محيطان محسوبان من أطوال أضلاع متقابلة متساوية. إذا كان مجموع الضلعين المتجاورين في كل منهما '), math('12 cm'), text('، فما العلاقة بين محيطيهما؟')),
    concepts: ['perimeter-and-side-lengths', 'opposite-sides-parallel-equal'], skills: ['infer-equal-perimeters-from-adjacent-sums'], sourceConcepts: ['perimeter-from-adjacent-sides', 'opposite-side-properties'],
    coverage: { thinking: ['infer-perimeter-from-paired-sides'] },
    options: [optionText('q14-a', 'محيطاهما متساويان'), optionText('q14-b', 'محيط الأول أكبر دائماً'), optionText('q14-c', 'محيط الثاني أكبر دائماً'), optionText('q14-d', 'لا يمكن المقارنة من دون معرفة الزاوية')],
    answer: 'q14-a',
    solution: { idea: rich(text('محيط كل متوازي أضلاع يضم مرتين مجموع الضلعين المتجاورين.')), steps: [rich(text('إذا كان المجموع في كل شكل '), math('12 cm'), text('، فمحيط كل منهما '), math('2×12=24 cm'), text('.')), rich(text('لا يؤثر اختلاف الزاوية في هذا الحساب ما دامت الأطوال كما وُصفت.'))], finalAnswer: rich(text('محيطاهما متساويان.')) },
    originalityNote: 'يستنتج تساوي محيطين من مجموعين مشتركين بدلاً من حساب محيط واحد أو إيجاد ضلع ناقص من محيط معلوم.',
  }),
  q(15, {
    type: 'error-analysis', difficulty: 'advanced',
    prompt: rich(text('أُعطيت رسامة ضلعين متجاورين طولهما '), math('8 cm'), text(' و'), math('3 cm'), text(' وزاوية محصورة '), math('65°'), text('؛ وبعد رسمهما جعلت الضلع الثالث عمودياً على الضلع الأول. اختر التشخيص والتصحيح.')),
    concepts: ['parallelogram-construction', 'opposite-sides-parallel-equal'], skills: ['diagnose-parallel-construction-error', 'correct-opposite-side-direction'], sourceConcepts: ['construction-with-ruler-and-protractor', 'opposite-side-properties'],
    coverage: { commonErrors: ['replace-parallel-with-perpendicular'] },
    studentWork: rich(text('الضلع الثالث عمودي على الضلع الأول.')),
    diagnoses: [optionText('q15-d1', 'استعملت شرط التعامد بدلاً من جعل الضلعين المتقابلين متوازيين'), optionText('q15-d2', 'استخدمت أطوال الضلعين المتجاورين لتحديد الشكل')],
    corrections: [option('q15-c1', text('من الرأس الثالث ارسم الضلع المقابل موازياً للأول وبطول '), math('8 cm'), text(' في اتجاه يغلق الشكل، ثم صِل الطرف الأخير')), optionText('q15-c2', 'اجعل الزاوية المحصورة قائمة مهما كانت معطاة')],
    answer: { diagnosisId: 'q15-d1', correctionId: 'q15-c1' },
    solution: { idea: rich(text('في الإنشاء يجب أن يحافظ الضلعان المتقابلان على التوازي؛ التعامد ليس شرطاً عاماً لمتوازي الأضلاع.')), steps: [rich(text('الضلعان المعطيان والزاوية '), math('65°'), text(' يحددان ضلعين متجاورين.')), rich(text('من الرأس الثالث نرسم الضلع المقابل موازياً للأول وبطول '), math('8 cm'), text(' وفي اتجاه إغلاق الرباعي، لا عمودياً عليه أو في الاتجاه المعاكس.')), rich(text('ثم نصل الطرف الأخير لإغلاق الشكل.'))], finalAnswer: rich(text('التشخيص: استبدلت التوازي بالتعامد؛ التصحيح: من الرأس الثالث ارسم الضلع المقابل موازياً للأول وبطول '), math('8 cm'), text(' وفي اتجاه يغلق الرباعي.')), commonError: rich(text('الاعتقاد أن كل متوازي أضلاع يجب أن يحتوي زوايا قائمة، أو استبدال شرط التوازي بالتعامد.')) },
    originalityNote: 'يشخّص خطأ في اتجاه ضلع أثناء إنشاء محدد بمعطيات جديدة؛ لا يكرر سؤال الاختبار النهائي عن نقص الزاوية المحصورة.',
  }),
  q(16, {
    type: 'true-false', difficulty: 'advanced',
    prompt: rich(text('إذا عُرف طول ضلع واحد فقط في متوازي أضلاع، أمكن تحديد محيطه وحده من دون أي معلومة أخرى عن ضلع مجاور.')),
    concepts: ['perimeter-and-side-lengths', 'insufficient-parallel-data'], skills: ['judge-perimeter-data-sufficiency'], sourceConcepts: ['perimeter-from-adjacent-sides', 'insufficient-measurements'],
    answer: false,
    solution: { idea: rich(text('محيط متوازي الأضلاع يعتمد على طولي ضلعين متجاورين، لأن كل طول يتكرر في الضلع المقابل.')), steps: [rich(text('معرفة طول واحد تحدد ضلعاً ومقابله فقط.')), rich(text('يبقى طول الزوج الآخر مجهولاً، لذلك لا يمكن تحديد المحيط.'))], finalAnswer: rich(text('خطأ؛ يلزم معرفة طول ضلع مجاور أيضاً.')) },
    originalityNote: 'يفحص كفاية معلومة واحدة لحساب المحيط، وهو عكس سؤال وجود طولين من دون زاوية في الإنشاء.',
  }),
  q(17, {
    type: 'multi-select', difficulty: 'advanced',
    prompt: rich(text('محيط متوازي أضلاع '), math('38 cm'), text('. اختر كل زوج من طولي ضلعين متجاورين يمكن أن يحقق هذا المحيط.')),
    concepts: ['perimeter-and-side-lengths'], skills: ['select-adjacent-sides-for-perimeter', 'use-perimeter-as-twice-adjacent-sum'], sourceConcepts: ['perimeter-from-adjacent-sides'],
    options: [option('q17-a', math('15 cm'), text(' و'), math('4 cm')), option('q17-b', math('12 cm'), text(' و'), math('7 cm')), option('q17-c', math('10 cm'), text(' و'), math('9 cm')), option('q17-d', math('13 cm'), text(' و'), math('7 cm'))],
    answer: ['q17-a', 'q17-b', 'q17-c'],
    solution: { idea: rich(text('محيط متوازي الأضلاع يساوي ضعفي مجموع طولي ضلعين متجاورين.')), steps: [rich(text('نصف المحيط هو '), math('38÷2=19 cm'), text('.')), rich(text('الأزواج الأولى والثانية والثالثة مجموع كل منها '), math('19 cm'), text('.')), rich(text('الزوج الأخير مجموعه '), math('20 cm'), text('، فيعطي محيطاً قدره '), math('40 cm'), text('.'))], finalAnswer: rich(text('الأزواج الصحيحة: A وB وC.')) },
    originalityNote: 'يختار عدة أزواج ممكنة من مجموع يساوي نصف محيط معلوم؛ يختلف عن إيجاد ضلع مفرد مجهول من محيط وطول آخر.',
  }),
  q(18, {
    type: 'multi-select', difficulty: 'thinking',
    prompt: rich(text('رُسم متوازيان مختلفان بالضلعين المتجاورين نفسيهما، لكن بزاويتين مختلفتين. اختر العبارات التي تبقى صحيحة في كليهما.')),
    concepts: ['opposite-sides-parallel-equal', 'opposite-angles-equal', 'perimeter-and-side-lengths'], skills: ['synthesize-invariant-parallelogram-properties', 'separate-angle-and-length-effects'], sourceConcepts: ['opposite-side-properties', 'opposite-angle-property', 'perimeter-from-adjacent-sides'],
    coverage: { thinking: ['reason-about-shape-invariants'] },
    options: [optionText('q18-a', 'كل ضلعين متقابلين متساويان في الطول'), optionText('q18-b', 'محيطاهما متساويان'), optionText('q18-c', 'الزاويتان المتقابلتان متساويتان داخل كل شكل'), optionText('q18-d', 'الزاوية نفسها في الشكلين بالضرورة')],
    answer: ['q18-a', 'q18-b', 'q18-c'],
    solution: { idea: rich(text('نميز الخصائص الثابتة لمتوازي الأضلاع عن مقدار الزاوية التي اختيرت لكل رسم.')), steps: [rich(text('تساوي الأضلاع المتقابلة والزوايا المتقابلة يبقى في كل شكل.')), rich(text('مجموع الضلعين المتجاورين نفسه، لذلك المحيطان متساويان.')), rich(text('لكن الزاوية بين الضلعين قد تختلف من رسم إلى آخر.'))], finalAnswer: rich(text('العبارات الأولى والثانية والثالثة صحيحة؛ الرابعة غير لازمة.')) },
    originalityNote: 'يفصل الثوابت الهندسية عن اختلاف شكل الإنشاء عبر مقارنة رسمين، لا يسأل عن عدد الرسوم الممكنة بقيمتي اختبار سابق.',
  }),
  q(19, {
    type: 'error-analysis', difficulty: 'thinking',
    prompt: rich(text('رأت سلمى متوازي أضلاع ومعلومة أن كل ضلعين متقابلين متساويان، فاستنتجت أن الأضلاع الأربعة متساوية. اختر التشخيص والتصحيح.')),
    concepts: ['opposite-sides-parallel-equal', 'special-parallelograms'], skills: ['distinguish-equal-opposite-pairs-from-rhombus'], sourceConcepts: ['opposite-side-properties', 'definition-and-shape-examples'],
    coverage: { thinking: ['evaluate-overgeneralized-side-property'], commonErrors: ['confuse-opposite-equality-with-all-equal'] },
    studentWork: rich(text('كل ضلعين متقابلين متساويان؛ إذن الأضلاع الأربعة متساوية.')),
    diagnoses: [optionText('q19-d1', 'حوّلت تساوي كل زوج متقابل إلى تساوي الزوجين المتجاورين أيضاً'), optionText('q19-d2', 'استخدمت خاصية صحيحة للأضلاع المتقابلة')],
    corrections: [optionText('q19-c1', 'المعطى يثبت التساوي بين كل زوج متقابل فقط'), optionText('q19-c2', 'كل متوازي أضلاع معين بالضرورة')],
    answer: { diagnosisId: 'q19-d1', correctionId: 'q19-c1' },
    solution: { idea: rich(text('المساواة بين زوجي الأضلاع المتقابلة لا تساوي بالضرورة الأضلاع المتجاورة.')), steps: [rich(text('نستنتج طولين متساويين في كل زوج متقابل.')), rich(text('لا توجد من ذلك وحده معلومة تجعل هذين الطولين متساويين أحدهما بالآخر.')), rich(text('المستطيل غير المربع مثال يوضح الفرق بين المتوازي والمعين.'))], finalAnswer: rich(text('التشخيص: تعميم زائد؛ الخاصية تضمن تساوي كل زوج متقابل فقط.')), commonError: rich(text('الخلط بين وجود زوجين متساويين كلٌّ على حدة وبين تساوي الأضلاع الأربعة جميعاً.')) },
    originalityNote: 'يفحص تعميماً زائداً من خاصية صحيحة ويستعمل حالة المستطيل للتمييز بين الزوجين المتقابلين والمتجاورين.',
  }),
  q(20, {
    type: 'single-choice', difficulty: 'thinking',
    prompt: rich(text('في رسم رباعي، ما الدليل الأقوى وحده على أنه يحقق تعريف متوازي الأضلاع؟')),
    concepts: ['parallelogram-definition', 'insufficient-parallel-data'], skills: ['select-sufficient-definition-evidence'], sourceConcepts: ['definition-and-shape-examples'],
    coverage: { thinking: ['choose-complete-parallel-evidence'] },
    options: [optionText('q20-a', 'علامات تبين توازي كلا الزوجين من الأضلاع المتقابلة'), optionText('q20-b', 'علامة توازي على زوج واحد فقط'), optionText('q20-c', 'رسم يبدو مائلاً مثل متوازي الأضلاع'), optionText('q20-d', 'وجود قطر مرسوم داخل الشكل')],
    answer: 'q20-a',
    solution: { idea: rich(text('التعريف يعتمد على خاصية التوازي في الزوجين المتقابلين، لا على شكل الرسم بصرياً.')), steps: [rich(text('الدليل الأول يثبت الشرطين معاً.')), rich(text('أما زوج واحد أو قطر أو هيئة الرسم فلا يثبت وحده التعريف.'))], finalAnswer: rich(text('علامات توازي كلا الزوجين المتقابلين.')) },
    originalityNote: 'يقارن قوة أدلة مرئية متعددة لتطبيق التعريف، بدلاً من إعادة سؤال مباشر عن تعريف الكلمة أو نتيجة تمرين.',
  }),
]

const definition = defineLessonTest({
  id: testId,
  lessonId,
  title: 'اختبار متوازي الأضلاع',
  description: rich(text('يقيس هذا الاختبار تعريف متوازي الأضلاع وخصائص أضلاعه وزواياه المتقابلة، والقطر والمحيط، والإنشاء وكفاية المعطيات.')),
  instructions: rich(text('استخدم ترتيب الرؤوس كما ورد، وميّز دائماً بين الأضلاع المتقابلة والمتجاورة. لا تعتمد على مظهر الرسم وحده لإثبات التوازي أو تحديد شكل وحيد.')),
  questions,
  sourceConcepts: [
    { id: 'definition-and-shape-examples', label: 'تعريف متوازي الأضلاع وتصنيف المستطيل والمعين ضمن الأشكال', pages: [31, 32] },
    { id: 'opposite-side-properties', label: 'توازي الأضلاع المتقابلة وتساوي أطوالها', pages: [31, 32, 33] },
    { id: 'opposite-angle-property', label: 'تساوي قياسي الزاويتين المتقابلتين', pages: [32, 33, 35] },
    { id: 'diagonal-and-quadrilateral-parts', label: 'القطر قطعة تصل بين رأسين غير متتاليين', pages: [32] },
    { id: 'perimeter-from-adjacent-sides', label: 'حساب المحيط من طولي ضلعين متجاورين والأضلاع المتقابلة', pages: [33, 35] },
    { id: 'construction-with-ruler-and-protractor', label: 'إنشاء متوازي أضلاع بالمسطرة والمنقلة من ضلعين وزاوية', pages: [33, 34] },
    { id: 'insufficient-measurements', label: 'تعدد الأشكال عند غياب معلومات كافية عن الزاوية أو الأطوال', pages: [35] },
  ],
  conceptLabels: {
    'parallelogram-definition': 'تعريف متوازي الأضلاع بزوجي الأضلاع المتقابلة المتوازية',
    'special-parallelograms': 'المستطيل والمعين حالتان خاصتان ضمن أمثلة الدرس',
    'diagonal-definition': 'القطر يصل بين رأسين غير متتاليين',
    'parallelogram-parts': 'أجزاء الشكل الرباعي: رأس وضلع وقطر',
    'opposite-sides-parallel-equal': 'توازي الأضلاع المتقابلة وتساويها',
    'opposite-angles-equal': 'تساوي الزوايا المتقابلة',
    'insufficient-parallel-data': 'عدم كفاية توازي زوج واحد لإثبات التعريف',
    'parallelogram-construction': 'إنشاء الشكل من أطوال وزاوية معطاة',
    'perimeter-and-side-lengths': 'المحيط مرتبط بطولي ضلعين متجاورين',
  },
  skillLabels: {
    'state-parallelogram-definition': 'ذكر تعريف متوازي الأضلاع بدقة',
    'recognize-rectangle-as-parallelogram': 'تطبيق التعريف على المستطيل',
    'distinguish-side-vertex-and-diagonal': 'تمييز الرأس والضلع والقطر',
    'identify-guaranteed-properties': 'اختيار الخصائص المضمونة للشكل',
    'distinguish-opposite-equality-from-all-sides-equal': 'التفريق بين تساوي الأضلاع المتقابلة وتساوي الأربعة',
    'classify-quadrilateral-from-parallel-pairs': 'تصنيف رباعي من عدد أزواج التوازي',
    'sequence-ruler-protractor-construction': 'ترتيب خطوات الإنشاء بالمسطرة والمنقلة',
    'diagnose-adjacent-as-opposite': 'كشف الخلط بين الضلعين المتجاورين والمتقابلين',
    'identify-opposite-side-pair': 'تحديد الضلع المقابل بحسب ترتيب الرؤوس',
    'identify-opposite-parts-by-order': 'تحديد الأجزاء المتقابلة من ترتيب الرؤوس',
    'reason-about-perimeter-under-angle-change': 'استنتاج ثبات المحيط عند تغيير الزاوية وحدها',
    'compare-parallelogram-perimeters': 'مقارنة محيطي شكلين من أطوال أضلاعهما',
    'select-valid-construction-actions': 'اختيار خطوات صحيحة لإنشاء متوازي أضلاع',
    'apply-included-angle-to-construction': 'تطبيق الزاوية المحصورة في الإنشاء',
    'recognize-special-cases': 'تمييز المستطيل والمعين ضمن عائلة متوازيات الأضلاع',
    'infer-equal-perimeters-from-adjacent-sums': 'استنتاج تساوي المحيط من تساوي مجموع الضلعين',
    'diagnose-parallel-construction-error': 'كشف استبدال التوازي بشرط غير صحيح في الإنشاء',
    'correct-opposite-side-direction': 'تصحيح اتجاه الضلع المقابل بجعله موازياً للأول',
    'judge-perimeter-data-sufficiency': 'تقدير كفاية أطوال الأضلاع لحساب المحيط',
    'select-adjacent-sides-for-perimeter': 'اختيار زوج أضلاع متجاورة يحقق محيطاً معلوماً',
    'use-perimeter-as-twice-adjacent-sum': 'استخدام نصف المحيط كمجموع ضلعين متجاورين',
    'synthesize-invariant-parallelogram-properties': 'جمع خواص تبقى صحيحة عبر أشكال مختلفة',
    'separate-angle-and-length-effects': 'تمييز أثر الزاوية عن أثر أطوال الأضلاع',
    'distinguish-equal-opposite-pairs-from-rhombus': 'التمييز بين تساوي الزوجين المتقابلين وتساوي الأضلاع الأربعة',
    'select-sufficient-definition-evidence': 'اختيار دليل يثبت شرط التعريف كاملاً',
  },
  thinkingLabels: {
    'infer-perimeter-from-paired-sides': 'استنتاج علاقة محيطين من مجموعي ضلعين متجاورين',
    'reason-about-shape-invariants': 'تمييز الخصائص الثابتة عن زاوية الإنشاء',
    'evaluate-overgeneralized-side-property': 'تقويم تعميم يتجاوز خاصية الأضلاع المتقابلة',
    'choose-complete-parallel-evidence': 'اختيار الدليل الذي يثبت زوجي التوازي معاً',
  },
  commonErrorLabels: {
    'confuse-adjacent-and-opposite-sides': 'اعتبار ضلعين متجاورين ضلعين متقابلين',
    'replace-parallel-with-perpendicular': 'استبدال التوازي المطلوب بالتعامد في الإنشاء',
    'confuse-opposite-equality-with-all-equal': 'تعميم تساوي الزوجين المتقابلين على الأضلاع الأربعة',
  },
})

export default definition
