import { defineLessonTest, lessonQuestion, math, rich, text, textOnly, type LessonQuestionDraft } from '../../lessonTestBuilder'
import type { QuestionDefinition } from '../../types'

const testId = 'lesson-rounding-natural-numbers-test'
const lessonId = 'rounding-natural-numbers'
const qid = (number: number) => `${testId}-q${String(number).padStart(2, '0')}`
const q = (number: number, draft: LessonQuestionDraft) =>
  lessonQuestion(testId, lessonId, qid(number), draft)
const option = (id: string, ...runs: Parameters<typeof rich>) => ({ id, label: rich(...runs) })
const optionText = (id: string, value: string) => ({ id, label: textOnly(value) })

const questions: QuestionDefinition[] = [
  q(1, {
    type: 'true-false', difficulty: 'basic',
    prompt: rich(text('عند تقريب عدد إلى أقرب مئة، ننظر إلى رقم العشرات لاتخاذ قرار التقريب.')),
    concepts: ['rounding-rule', 'rounding-place-value'], skills: ['identify-next-digit-to-check'], sourceConcepts: ['rounding-rule'],
    answer: true,
    solution: { idea: rich(text('نحدد المنزلة المطلوبة ثم نفحص الرقم الواقع مباشرة إلى يمينها.')), steps: [rich(text('في التقريب إلى أقرب مئة تكون المنزلة المطلوبة هي المئات.')), rich(text('الرقم إلى يمينها هو رقم العشرات.'))], finalAnswer: rich(text('صحيح.')) },
    originalityNote: 'يفحص اختيار المنزلة التي تُفحص عند التقريب للمئة بصيغة قاعدة عامة، لا يعيد تدريب تقريب العدد 580.',
  }),
  q(2, {
    type: 'numeric', difficulty: 'basic',
    prompt: rich(text('قرّبت ريم '), math('4,236'), text(' إلى أقرب مئة. كم مئة كاملة يحتوي الناتج المقرب؟')),
    concepts: ['rounding-rule', 'rounding-hundreds'], skills: ['round-to-nearest-hundred', 'interpret-rounded-result-in-hundreds'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands'],
    answer: { expected: '42', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نحدد الناتج المقرب أولاً، ثم نعبّر عنه بعدد مجموعات المئة.')), steps: [rich(text('رقم العشرات في '), math('4,236'), text(' هو '), math('3'), text('، لذلك يصبح الناتج '), math('4,200'), text('.')), rich(math('4,200=42×100'), text('؛ أي اثنتان وأربعون مئة كاملة.'))], finalAnswer: rich(text('اثنتان وأربعون مئة.')) },
    originalityNote: 'يحول نتيجة التقريب إلى عدد مئات كاملة بدلاً من طلب ناتج تقريب مباشر؛ يربط التقريب بقيمة المنزلة ولا ينسخ قالب تطبيق العدد المفرد.',
  }),
  q(3, {
    type: 'single-choice', difficulty: 'basic',
    prompt: rich(text('عند تقريب العدد '), math('2,364,000'), text(' إلى أقرب مئة ألف، أي رقم فيه يحسم الاختيار بين '), math('2,300,000'), text(' و'), math('2,400,000'), text('؟')),
    concepts: ['rounding-rule', 'rounding-place-value'], skills: ['locate-rounding-decision-digit'], sourceConcepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'],
    options: [option('q03-a', math('2')), option('q03-b', math('3')), option('q03-c', math('6')), option('q03-d', math('4'))],
    answer: 'q03-c',
    solution: { idea: rich(text('نحدد منزلة التقريب ثم نفحص الرقم المجاور لها مباشرة.')), steps: [rich(text('منزلة مئات الآلاف تحمل الرقم '), math('3'), text('.')), rich(text('الرقم على يمينها في منزلة عشرات الآلاف هو '), math('6'), text('، وهو الذي يحدد أي الحدّين أقرب.'))], finalAnswer: rich(text('الرقم الذي يحسم الاختيار هو '), math('6'), text('.')) },
    originalityNote: 'يحدد رقم القرار بين حدّي التقريب بدلاً من طلب ناتج تقريب مباشر؛ وهذا يبتعد عن قالب مثال تقريب مئة ألف في الكتاب.',
  }),
  q(4, {
    type: 'matching', difficulty: 'basic',
    prompt: rich(text('طابق منزلة التقريب مع الرقم الذي يجب فحصه مباشرة على يمينها.')),
    concepts: ['rounding-place-value'], skills: ['locate-rounding-decision-digit'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands', 'rounding-hundred-thousand-and-million'],
    left: [optionText('q04-l1', 'أقرب مئة'), optionText('q04-l2', 'أقرب ألف'), optionText('q04-l3', 'أقرب مئة ألف'), optionText('q04-l4', 'أقرب مليون')],
    right: [optionText('q04-r1', 'رقم العشرات'), optionText('q04-r2', 'رقم المئات'), optionText('q04-r3', 'رقم عشرات الآلاف'), optionText('q04-r4', 'رقم مئات الآلاف')],
    answer: [{ leftId: 'q04-l1', rightId: 'q04-r1' }, { leftId: 'q04-l2', rightId: 'q04-r2' }, { leftId: 'q04-l3', rightId: 'q04-r3' }, { leftId: 'q04-l4', rightId: 'q04-r4' }],
    solution: { idea: rich(text('في كل حالة ننتقل منزلة واحدة إلى يمين المنزلة المستهدفة.')), steps: [rich(text('بعد المئات تأتي العشرات، وبعد الآلاف تأتي المئات.')), rich(text('بعد مئات الآلاف تأتي عشرات الآلاف، وبعد الملايين تأتي مئات الآلاف.'))], finalAnswer: rich(text('مئة: عشرات؛ ألف: مئات؛ مئة ألف: عشرات آلاف؛ مليون: مئات آلاف.')) },
    originalityNote: 'مطابقة منهجية للمنازل الأربع التي يعرضها الدرس مع رقم القرار؛ لا تكرر أي عملية عددية أو مثال محلول.',
  }),
  q(5, {
    type: 'multi-select', difficulty: 'basic',
    prompt: rich(text('اختر كل العبارات الصحيحة عن قاعدة التقريب كما دُرست.')),
    concepts: ['rounding-rule'], skills: ['state-rounding-rule', 'apply-rounding-threshold'], sourceConcepts: ['rounding-rule'],
    options: [optionText('q05-a', 'إذا كان رقم القرار 5 أو أكبر نزيد المنزلة المطلوبة واحداً'), optionText('q05-b', 'إذا كان رقم القرار أصغر من 5 تبقى المنزلة المطلوبة كما هي'), optionText('q05-c', 'بعد التقريب نكتب أصفاراً في الخانات الواقعة يمين المنزلة'), optionText('q05-d', 'ننظر دائماً إلى رقم الآحاد مهما كانت المنزلة المطلوبة')],
    answer: ['q05-a', 'q05-b', 'q05-c'],
    solution: { idea: rich(text('تتكون القاعدة من رقم القرار، وتعديل المنزلة المطلوبة، ثم تصفير الخانات اللاحقة.')), steps: [rich(text('الرقم '), math('5'), text(' هو حد الزيادة، وكل رقم أكبر منه يزيد المنزلة أيضاً.')), rich(text('الأرقام من '), math('0'), text(' إلى '), math('4'), text(' تبقيها كما هي.')), rich(text('لا نستخدم الآحاد إلا إذا كانت هي الرقم الذي يلي المنزلة المقربة مباشرة.'))], finalAnswer: rich(text('الأولى والثانية والثالثة صحيحة؛ الرابعة خاطئة.')) },
    originalityNote: 'يقيس أجزاء القاعدة ويفصلها عن اختيار الرقم الصحيح المجاور؛ ليس سؤالاً على نتيجة عدد بعينه من محتوى الدرس.',
  }),
  q(6, {
    type: 'error-analysis', difficulty: 'basic',
    prompt: rich(text('قرّب طالب '), math('31,649'), text(' إلى أقرب ألف، فكتب '), math('31,000'), text(' لأنه نظر إلى رقم العشرات. اختر التشخيص والتصحيح.')),
    concepts: ['rounding-rule', 'rounding-hundreds-and-thousands'], skills: ['diagnose-wrong-decision-digit', 'correct-rounding-to-thousand'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands'],
    coverage: { commonErrors: ['inspect-wrong-place'] },
    studentWork: rich(math('31,649 \u2248 31,000')),
    diagnoses: [optionText('q06-d1', 'فحص منزلة غير مجاورة للمنزلة المطلوبة'), optionText('q06-d2', 'كتب أصفاراً في الخانات التي تلي الألف')],
    corrections: [option('q06-c1', math('32,000')), option('q06-c2', math('31,000'))],
    answer: { diagnosisId: 'q06-d1', correctionId: 'q06-c1' },
    solution: { idea: rich(text('للتقريب إلى ألف نفحص المئات لا العشرات.')), steps: [rich(text('رقم المئات هو '), math('6'), text('، وهو أكبر من أو يساوي '), math('5'), text('.')), rich(text('نزيد خانة الآلاف واحداً ثم نصفر المئات والعشرات والآحاد.'))], finalAnswer: rich(math('31,649≈32,000')), commonError: rich(text('القفز إلى رقم أبعد من المنزلة المستهدفة بدلاً من فحص الرقم المجاور مباشرة.')) },
    originalityNote: 'يحدد خطأ اختيار رقم القرار في تقريب للألف باستخدام عدد مختلف؛ يركز على الإجراء الخاطئ لا على تكرار مثال الكتاب.',
  }),
  q(7, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('في مجموعة البطاقات '), math('46,492'), text(' و'), math('46,499'), text(' و'), math('46,501'), text(' و'), math('45,800'), text('، كم بطاقة ستعرض '), math('46,000'), text(' بعد التقريب إلى أقرب ألف؟')),
    concepts: ['rounding-rule', 'rounding-hundreds-and-thousands'], skills: ['count-values-rounding-to-target', 'compare-rounded-results'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands'],
    answer: { expected: '3', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نقرب كل بطاقة على حدة ثم نعد البطاقات التي تساوي نتيجتها الهدف.')), steps: [rich(math('46,492≈46,000'), text(' و'), math('46,499≈46,000'), text('.')), rich(math('46,501≈47,000'), text('، بينما '), math('45,800≈46,000'), text('.'))], finalAnswer: rich(text('ثلاث بطاقات.')) },
    originalityNote: 'يجمع تصنيف أربع قيم حول حد الألف ثم يعد النتائج المتساوية؛ بنية مختلفة عن طلب تقريب عدد مفرد كما في أمثلة الكتاب.',
  }),
  q(8, {
    type: 'ordering', difficulty: 'advanced',
    prompt: rich(text('رتّب الأعداد بحسب ناتج تقريب كل منها إلى أقرب ألف، من الناتج الأصغر إلى الأكبر، وعند التعادل رتّب العدد الأصلي الأصغر أولاً.')),
    concepts: ['rounding-hundreds-and-thousands', 'compare-rounded-results'], skills: ['round-and-order-results'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands'],
    items: [option('q08-a', math('12,249')), option('q08-b', math('12,760')), option('q08-c', math('12,499')), option('q08-d', math('12,501'))],
    answer: ['q08-a', 'q08-c', 'q08-d', 'q08-b'],
    solution: { idea: rich(text('نقرّب كل عدد أولاً ثم نرتب البطاقات بحسب النتيجة، مع إمكان التعادل.')), steps: [rich(math('12,249≈12,000'), text(' و'), math('12,499≈12,000'), text('.')), rich(math('12,501≈13,000'), text(' و'), math('12,760≈13,000'), text('.')), rich(text('كل ناتج من المجموعة الأولى أصغر من كل ناتج في الثانية.'))], finalAnswer: rich(text('12,249 ثم 12,499 ثم 12,501 ثم 12,760.')) },
    originalityNote: 'يجمع قاعدة التقريب مع ترتيب أربع بطاقات وناتجين متعادلين؛ لا يعيد سؤال تقريب منفرد أو يستبدل أرقام تمرين معروف.',
  }),
  q(9, {
    type: 'true-false', difficulty: 'medium',
    prompt: rich(text('عند تقريب '), math('2,349'), text(' إلى أقرب مئة، نحتفظ بالمئات لأن رقم العشرات '), math('4'), text('، حتى لو كان رقم الآحاد '), math('9'), text('.')),
    concepts: ['rounding-rule', 'rounding-hundreds'], skills: ['use-adjacent-digit-only'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands'],
    answer: true,
    solution: { idea: rich(text('القرار يعتمد على الرقم المجاور مباشرة، لا على أي رقم أبعد إلى اليمين.')), steps: [rich(text('رقم العشرات هو '), math('4'), text('، وهو أقل من '), math('5'), text('.')), rich(text('لذلك لا يغيّر رقم الآحاد '), math('9'), text(' قرار التقريب إلى أقرب مئة.'))], finalAnswer: rich(math('2,349≈2,300')) },
    originalityNote: 'يفصل أثر الرقم المجاور عن رقم أبعد في العدد، وهو فحص لقاعدة القرار لا إعادة لعدد ممارسة من الصفحات.',
  }),
  q(10, {
    type: 'matching', difficulty: 'medium',
    prompt: rich(text('طابق كل تقريب مع نتيجته الصحيحة.')),
    concepts: ['rounding-hundreds', 'rounding-hundreds-and-thousands', 'rounding-hundred-thousand-and-million'], skills: ['round-to-target-place'], sourceConcepts: ['rounding-hundreds-and-thousands', 'rounding-hundred-thousand-and-million'],
    left: [option('q10-l1', math('7,384'), text(' إلى أقرب مئة')), option('q10-l2', math('25,510'), text(' إلى أقرب ألف')), option('q10-l3', math('1,649,000'), text(' إلى أقرب مليون'))],
    right: [option('q10-r1', math('26,000')), option('q10-r2', math('7,400')), option('q10-r3', math('2,000,000'))],
    answer: [{ leftId: 'q10-l1', rightId: 'q10-r2' }, { leftId: 'q10-l2', rightId: 'q10-r1' }, { leftId: 'q10-l3', rightId: 'q10-r3' }],
    solution: { idea: rich(text('لكل مسألة منزلة مستهدفة ورقم قرار مختلف.')), steps: [rich(text('في '), math('7,384'), text(' ننظر إلى العشرات '), math('8'), text(' فنحصل على '), math('7,400'), text('.')), rich(text('في '), math('25,510'), text(' ننظر إلى المئات '), math('5'), text(' فنحصل على '), math('26,000'), text('.')), rich(text('في '), math('1,649,000'), text(' ننظر إلى مئات الآلاف '), math('6'), text(' فنحصل على '), math('2,000,000'), text('.'))], finalAnswer: rich(text('المئة: 7,400؛ الألف: 26,000؛ المليون: 2,000,000.')) },
    originalityNote: 'مطابقة بين ثلاث منازل مستهدفة مع أرقام قرار مختلفة؛ تمت صياغة البيانات خصيصاً ولا تنسخ أمثلة التمرين المدرسي.',
  }),
  q(11, {
    type: 'multi-select', difficulty: 'advanced',
    prompt: rich(text('في العدد '), math('73,2□8'), text('، قرّبت ندى العدد إلى أقرب مئة فكان الناتج '), math('73,300'), text('. أيّ رقم من البدائل يمكن أن يكون في المربع؟ اختر كل ما ينطبق.')),
    concepts: ['rounding-rule', 'rounding-hundreds'], skills: ['infer-missing-rounding-digit', 'apply-rounding-threshold'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands'],
    options: [option('q11-a', math('4')), option('q11-b', math('5')), option('q11-c', math('7')), option('q11-d', math('9'))],
    answer: ['q11-b', 'q11-c', 'q11-d'],
    solution: { idea: rich(text('نستدل عكسياً من الناتج المقرب على رقم القرار الممكن.')), steps: [rich(text('في '), math('73,2□8'), text('، منزلة المئات '), math('2'), text('؛ والقرار يعتمد على رقم العشرات مكان المربع.')), rich(text('ليصبح التقريب '), math('73,300'), text(' يجب رفع المئات، لذلك يكون الرقم في المربع '), math('5'), text(' أو أكبر.')), rich(text('من البدائل المعطاة، '), math('5'), text(' و'), math('7'), text(' و'), math('9'), text(' تحقق الشرط؛ أما '), math('4'), text(' فلا.'))], finalAnswer: rich(text('القيم الممكنة هي '), math('5, 7, 9'), text(' (الخيارات B وC وD).')) },
    originalityNote: 'يستدل عكسياً من ناتج التقريب على أرقام مجهولة ممكنة؛ يختلف في بنية التفكير عن حساب منازل متعددة للعدد نفسه.',
  }),
  q(12, {
    type: 'error-analysis', difficulty: 'medium',
    prompt: rich(text('قرّب متعلم '), math('6,437,895'), text(' إلى أقرب مئة ألف فكتب '), math('6,000,000'), text(' لأنه نظر إلى رقم الملايين. اختر التشخيص والتصحيح.')),
    concepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'], skills: ['diagnose-wrong-rounding-place', 'correct-hundred-thousand-rounding'], sourceConcepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'],
    coverage: { commonErrors: ['inspect-target-digit-instead-of-next'] },
    studentWork: rich(math('6,437,895≈6,000,000')),
    diagnoses: [optionText('q12-d1', 'نظر إلى منزلة الملايين بدلاً من الرقم يمين مئات الآلاف'), optionText('q12-d2', 'استعمل الرقم الصحيح لكن نسي الأصفار')],
    corrections: [option('q12-c1', math('6,400,000')), option('q12-c2', math('6,000,000'))],
    answer: { diagnosisId: 'q12-d1', correctionId: 'q12-c1' },
    solution: { idea: rich(text('عند التقريب إلى مئة ألف، يكون رقم عشرات الآلاف هو رقم القرار.')), steps: [rich(text('رقم مئات الآلاف هو '), math('4'), text('، والرقم المجاور إلى يمينه '), math('3'), text('.')), rich(text('لأن '), math('3<5'), text(' تبقى المئات '), math('4'), text(' ثم تصفر المنازل الأدنى.'))], finalAnswer: rich(math('6,400,000')), commonError: rich(text('فحص المنزلة التي نقرّب إليها أو منزلة بعيدة بدلاً من الرقم الواقع مباشرة إلى يمينها.')) },
    originalityNote: 'يفصل بين منزلة الهدف ورقم القرار في تقريب للمئة ألف، باستخدام خطأ مختلف عن مسائل النظر إلى عشرات أو وحدات.',
  }),
  q(13, {
    type: 'single-choice', difficulty: 'medium',
    prompt: rich(text('أي تعليل يفسر تقريب '), math('7,520,000'), text(' إلى أقرب مليون على أنه '), math('8,000,000'), text('؟')),
    concepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'], skills: ['justify-rounding-decision'], sourceConcepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'],
    options: [optionText('q13-a', 'رقم مئات الآلاف 5، فنزيد الملايين واحداً ونصفر الخانات التالية'), optionText('q13-b', 'رقم عشرات الآلاف 2، لذلك نزيد الملايين واحداً'), optionText('q13-c', 'رقم الملايين 7 أكبر من 5، لذلك نبقيه كما هو'), optionText('q13-d', 'نحذف كل الخانات بعد الملايين من دون فحص أي رقم')],
    answer: 'q13-a',
    solution: { idea: rich(text('قرار التقريب للمليون يعتمد على الرقم المجاور مباشرة لخانة الملايين.')), steps: [rich(text('الرقم المجاور هو مئات الآلاف، وقيمته '), math('5'), text('.')), rich(text('بما أنه يبلغ حد الخمسة نزيد الملايين من '), math('7'), text(' إلى '), math('8'), text('، ثم نجعل المنازل الأصغر أصفاراً.'))], finalAnswer: rich(text('التعليل الصحيح هو A؛ والناتج '), math('8,000,000'), text('.')) },
    originalityNote: 'يطلب تفسير قرار الرفع لا تنفيذ أمر تقريب مباشر، ويكشف الخلط بين رقم القرار ورقم المنزلة المطلوبة.',
  }),
  q(14, {
    type: 'numeric', difficulty: 'medium',
    prompt: rich(text('بعد تقريب '), math('1,549,999'), text(' إلى أقرب مليون، كم صفراً يُكتب إلى يمين رقم الملايين في الناتج؟')),
    concepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'], skills: ['round-to-nearest-million', 'apply-five-threshold', 'count-zeroes-after-rounding'], sourceConcepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'],
    answer: { expected: '6', format: 'integer', unitPolicy: { kind: 'none' } },
    solution: { idea: rich(text('نطبق رقم القرار أولاً، ثم نحفظ المنازل الواقعة إلى يمين المليون بأصفار.')), steps: [rich(text('رقم مئات الآلاف هو '), math('5'), text('، لذلك تصبح الملايين '), math('2'), text('.')), rich(text('الناتج القياسي هو '), math('2,000,000'), text(' وفيه ست خانات صفرية إلى يمين رقم الملايين.'))], finalAnswer: rich(text('ستة أصفار.')) },
    originalityNote: 'يجمع قرار حد الخمسة مع تتبع خانات الناتج المصفّرة؛ لا يكتفي بإعادة كتابة تقريب مليون مباشر على عدد جديد.',
  }),
  q(15, {
    type: 'matching', difficulty: 'medium',
    prompt: rich(text('طابق كل قرار تقريب مع تفسير رقم القرار والنتيجة.')),
    concepts: ['rounding-rule', 'rounding-place-value'], skills: ['explain-rounding-decision', 'connect-digit-to-result'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands', 'rounding-hundred-thousand-and-million'],
    left: [option('q15-l1', math('4,671'), text(' إلى أقرب مئة')), option('q15-l2', math('83,499'), text(' إلى أقرب ألف')), option('q15-l3', math('2,649,000'), text(' إلى أقرب مليون'))],
    right: [optionText('q15-r1', 'العشرات 7، فنزيد المئات: 4,700'), optionText('q15-r2', 'المئات 4، فتبقى الآلاف: 83,000'), optionText('q15-r3', 'مئات الآلاف 6، فتصبح الملايين: 3,000,000')],
    answer: [{ leftId: 'q15-l1', rightId: 'q15-r1' }, { leftId: 'q15-l2', rightId: 'q15-r2' }, { leftId: 'q15-l3', rightId: 'q15-r3' }],
    solution: { idea: rich(text('كل نتيجة تفسر بالرقم المجاور مباشرة للمنزلة المستهدفة.')), steps: [rich(text('للمئة نفحص العشرات '), math('7'), text(' فنرفع إلى '), math('4,700'), text('.')), rich(text('للألف نفحص المئات '), math('4'), text(' فتبقى الآلاف في '), math('83,000'), text('.')), rich(text('للمليون نفحص مئات الآلاف '), math('6'), text(' فترتفع إلى '), math('3,000,000'), text('.'))], finalAnswer: rich(text('كل بند يطابق التفسير الذي يذكر رقمه المجاور ونتيجته.')) },
    originalityNote: 'مطابقة تشرح القرار لا النتيجة فقط عبر ثلاث منازل مختلفة؛ الأعداد والتفسيرات مؤلفة لهذا الاختبار.',
  }),
  q(16, {
    type: 'error-analysis', difficulty: 'advanced',
    prompt: rich(text('في التقريب إلى أقرب مئة ألف، قال طالب عن '), math('3,482,615'), text(': «أنظر إلى رقم مئات الآلاف نفسه؛ لأنه 4 فالنتيجة '), math('3,000,000'), text('». اختر التشخيص والتصحيح.')),
    concepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'], skills: ['diagnose-target-digit-confusion', 'apply-correct-rounding-digit'], sourceConcepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'],
    coverage: { commonErrors: ['inspect-rounding-place-not-neighbor'] },
    studentWork: rich(math('3,482,615≈3,000,000')),
    diagnoses: [optionText('q16-d1', 'فحص منزلة التقريب نفسها بدلاً من عشرات الآلاف'), optionText('q16-d2', 'فحص رقم الآحاد وهو الرقم المجاور للمئة ألف')],
    corrections: [option('q16-c1', math('3,500,000')), option('q16-c2', math('3,000,000'))],
    answer: { diagnosisId: 'q16-d1', correctionId: 'q16-c1' },
    solution: { idea: rich(text('لا يقرر الرقم في المنزلة المطلوبة وحده إن كانت ستزيد؛ نقرأ الرقم الذي على يمينه.')), steps: [rich(text('الرقم في عشرات الآلاف هو '), math('8'), text('.')), rich(text('لأن '), math('8≥5'), text(' نزيد مئات الآلاف من '), math('4'), text(' إلى '), math('5'), text(' ونصفر ما بعدها.'))], finalAnswer: rich(math('3,500,000')), commonError: rich(text('اتخاذ الرقم المستهدف نفسه قراراً للتقريب بدلاً من فحص المنزلة التالية.')) },
    originalityNote: 'يعالج خلطاً بين رقم المنزلة المقربة ورقم القرار في عدد جديد؛ يختلف عن الخطأ السابق الذي قفز إلى الملايين.',
  }),
  q(17, {
    type: 'multi-select', difficulty: 'advanced',
    prompt: rich(text('العدد '), math('8,764,321'), text('؛ اختر كل نتيجة تقريب صحيحة.')),
    concepts: ['rounding-hundreds-and-thousands', 'rounding-hundred-thousand-and-million'], skills: ['round-to-multiple-places', 'check-rounded-results'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands', 'rounding-hundred-thousand-and-million'],
    options: [option('q17-a', text('إلى أقرب مئة: '), math('8,764,300')), option('q17-b', text('إلى أقرب ألف: '), math('8,765,000')), option('q17-c', text('إلى أقرب مئة ألف: '), math('8,800,000')), option('q17-d', text('إلى أقرب مليون: '), math('8,000,000'))],
    answer: ['q17-a', 'q17-c'],
    solution: { idea: rich(text('نحسب رقم القرار لكل منزلة على حدة.')), steps: [rich(text('للمئة العشرات '), math('2'), text('، فالناتج '), math('8,764,300'), text('.')), rich(text('للألف المئات '), math('3'), text('، فالناتج '), math('8,764,000'), text('، لذا B خاطئة.')), rich(text('لمئة ألف عشرات الآلاف '), math('6'), text('، فالناتج '), math('8,800,000'), text('.')), rich(text('للمليون مئات الآلاف '), math('7'), text('، فيرتفع إلى '), math('9,000,000'), text('.'))], finalAnswer: rich(text('الصحيحان هما نتيجة أقرب مئة ونتيجة أقرب مئة ألف؛ نتيجتا الألف والمليون تحتاجان إلى التصحيح.')) },
    originalityNote: 'يمتحن مراجعة أربع نتائج مقترحة عبر أربع درجات دقة لعدد جديد؛ البدائل تختبر أخطاء متعددة لا مجرد تقريب نسخة من سؤال سابق.',
  }),
  q(18, {
    type: 'single-choice', difficulty: 'thinking',
    prompt: rich(text('قرّبت نور '), math('6,749,250'), text(' إلى أقرب مليون فحصلت على '), math('7,000,000'), text('. ثم قرّبه سامر إلى أقرب مئة ألف. أي تفسير يبين لماذا قد لا يكفي تقريب نور للإجابة عن طلب سامر؟')),
    concepts: ['rounding-place-value', 'rounding-hundred-thousand-and-million'], skills: ['distinguish-rounding-targets', 'recalculate-at-requested-place'], sourceConcepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'],
    coverage: { thinking: ['choose-requested-rounding-place'] },
    options: [optionText('q18-a', 'يلزم العودة إلى العدد الأصلي وفحص عشرات الآلاف؛ الناتج لأقرب مئة ألف هو 6,700,000'), optionText('q18-b', 'يمكن تقريب 7,000,000 مرة أخرى إلى أقرب مئة ألف فيبقى 7,000,000'), optionText('q18-c', 'كل تقريب إلى منزلة أكبر يعطي جواباً صالحاً لكل المنازل'), optionText('q18-d', 'لا يمكن تقريب العدد نفسه إلى منزلتين مختلفتين')],
    answer: 'q18-a',
    solution: { idea: rich(text('تختلف منزلة القرار باختلاف المنزلة المطلوبة، لذلك نحسب مباشرة من العدد الأصلي.')), steps: [rich(text('لأقرب مئة ألف نفحص عشرات الآلاف في '), math('6,749,250'), text('، وهي '), math('4'), text('.')), rich(text('تبقى خانة مئات الآلاف '), math('7'), text(' كما هي وتصبح الخانات الأدنى أصفاراً.')), rich(text('إذن الناتج المطلوب '), math('6,700,000'), text('، وليس تقريب النتيجة السابقة مرة أخرى.'))], finalAnswer: rich(text('الاختيار A.')) },
    originalityNote: 'يقيّم اختيار المنزلة المطلوبة عند وجود تقريب سابق إلى دقة مختلفة، ويمنع تحويل النتيجة المقربة إلى بديل عن العدد الأصلي.',
  }),
  q(19, {
    type: 'multi-select', difficulty: 'thinking',
    prompt: rich(text('لدى معلم البطاقات '), math('5,441,200'), text(' و'), math('5,449,800'), text(' و'), math('5,451,100'), text('. أي البطاقات تعطي النتيجة نفسها عند التقريب إلى أقرب مئة ألف؟ اختر كل ما ينطبق.')),
    concepts: ['rounding-hundred-thousand-and-million', 'compare-rounded-results'], skills: ['compare-rounded-outcomes', 'apply-nearest-place-to-list'], sourceConcepts: ['rounding-rule', 'rounding-hundred-thousand-and-million'],
    coverage: { thinking: ['compare-results-near-threshold'] },
    options: [option('q19-a', math('5,441,200')), option('q19-b', math('5,449,800')), option('q19-c', math('5,451,100'))],
    answer: ['q19-a', 'q19-b'],
    solution: { idea: rich(text('نقارن رقم عشرات الآلاف مع حد الخمسة في كل بطاقة.')), steps: [rich(text('في الأولى والثانية رقم عشرات الآلاف '), math('4'), text('، فتقربان إلى '), math('5,400,000'), text('.')), rich(text('في الثالثة هذا الرقم '), math('5'), text('، فترتفع إلى '), math('5,500,000'), text('.'))], finalAnswer: rich(text('البطاقتان الأولى والثانية تعطيان النتيجة نفسها.')) },
    originalityNote: 'يقارن نتائج ثلاث بطاقات حول حد القرار خمسة لتحديد التعادل، لا يكرر تقريب عدة خانات في العدد نفسه.',
  }),
  q(20, {
    type: 'error-analysis', difficulty: 'thinking',
    prompt: rich(text('قالت طالبة: «لأقرب ألف في العدد '), math('52,749'), text('، أزيد الآلاف لأن رقم العشرات هو '), math('4'), text('». اختر التشخيص والتصحيح المناسبين.')),
    concepts: ['rounding-rule', 'rounding-hundreds-and-thousands'], skills: ['evaluate-rounding-explanation', 'identify-immediate-right-digit'], sourceConcepts: ['rounding-rule', 'rounding-hundreds-and-thousands'],
    coverage: { thinking: ['evaluate-rounding-reasoning'], commonErrors: ['use-distant-digit-for-rounding'] },
    studentWork: rich(math('52,749≈53,000'), text('؛ القرار من العشرات '), math('4')),
    diagnoses: [optionText('q20-d1', 'النتيجة مصادفة صحيحة لكن التبرير استخدم العشرات بدلاً من المئات'), optionText('q20-d2', 'التقريب إلى ألف لا يحتاج إلى فحص أي رقم')],
    corrections: [optionText('q20-c1', 'المئات 7؛ لذا نرفع الآلاف ونكتب 53,000'), optionText('q20-c2', 'العشرات 4؛ لذا نبقي الآلاف ونكتب 52,000')],
    answer: { diagnosisId: 'q20-d1', correctionId: 'q20-c1' },
    solution: { idea: rich(text('لا يكفي الوصول إلى ناتج صحيح؛ يجب أن يكون رقم القرار هو المنزلة المجاورة مباشرة.')), steps: [rich(text('لأقرب ألف نفحص المئات '), math('7'), text(' لا العشرات '), math('4'), text('.')), rich(text('لأن '), math('7≥5'), text(' تزيد الآلاف إلى '), math('53,000'), text('.'))], finalAnswer: rich(text('التشخيص: رقم القرار غير صحيح؛ والتصحيح: '), math('52,749≈53,000'), text(' لأن المئات '), math('7'), text('.')), commonError: rich(text('تبرير ناتج التقريب برقم بعيد مع أن الرقم المجاور هو الذي يحسم القرار.')) },
    originalityNote: 'يميّز بين صحة النتيجة وصحة مسوّغها في مسألة حدودية؛ لا يكتفي بحساب آلي ولا يقتبس مسألة تقريب معروفة.',
  }),
]

const definition = defineLessonTest({
  id: testId,
  lessonId,
  title: 'اختبار تقريب الأعداد الطبيعية',
  description: rich(text('يقيس هذا الاختبار اختيار منزلة التقريب، وفحص الرقم المجاور، وتصفير الخانات اللاحقة، ومقارنة نتائج التقريب.')),
  instructions: rich(text('ابدأ دائماً من المنزلة المطلوبة ثم افحص الرقم الذي إلى يمينها مباشرة. الأعداد في هذه الأسئلة أمثلة اختبارية جديدة وليست نقلاً لأرقام تطبيقات الكتاب.')),
  questions,
  sourceConcepts: [
    { id: 'rounding-rule', label: 'قاعدة النظر إلى الرقم على يمين المنزلة المطلوبة والتصفير', pages: [15, 16, 17] },
    { id: 'rounding-hundreds-and-thousands', label: 'التقريب إلى أقرب مئة أو ألف وفق رقم القرار', pages: [15, 16, 18] },
    { id: 'rounding-hundred-thousand-and-million', label: 'التقريب إلى أقرب مئة ألف أو مليون', pages: [16, 17, 18] },
  ],
  conceptLabels: {
    'rounding-rule': 'قاعدة التقريب إلى المنزلة المطلوبة',
    'rounding-place-value': 'تحديد المنزلة المطلوبة والرقم المجاور',
    'rounding-hundreds': 'التقريب إلى أقرب مئة',
    'rounding-hundreds-and-thousands': 'التقريب إلى أقرب مئة أو ألف',
    'rounding-hundred-thousand-and-million': 'التقريب إلى أقرب مئة ألف أو مليون',
    'compare-rounded-results': 'مقارنة نتائج أعداد بعد تقريبها',
  },
  skillLabels: {
    'identify-next-digit-to-check': 'تحديد الرقم المجاور لمنزلة التقريب',
    'round-to-nearest-hundred': 'تقريب عدد إلى أقرب مئة',
    'interpret-rounded-result-in-hundreds': 'تفسير ناتج التقريب بعدد مجموعات المئة',
    'locate-rounding-decision-digit': 'تحديد رقم القرار بحسب المنزلة المستهدفة',
    'state-rounding-rule': 'شرح قاعدة التقريب والتصفير',
    'apply-rounding-threshold': 'تطبيق حد الخمسة في التقريب',
    'diagnose-wrong-decision-digit': 'تشخيص فحص منزلة غير مناسبة',
    'correct-rounding-to-thousand': 'تصحيح تقريب إلى أقرب ألف',
    'round-to-nearest-thousand': 'تقريب عدد إلى أقرب ألف',
    'count-values-rounding-to-target': 'عد القيم التي تنتج هدف التقريب نفسه',
    'compare-rounded-results': 'مقارنة نواتج التقريب بين قيم متعددة',
    'round-and-order-results': 'تقريب عدة أعداد ثم ترتيب النواتج',
    'use-adjacent-digit-only': 'استخدام الرقم المجاور دون التأثر بخانات أبعد',
    'round-to-target-place': 'تقريب العدد إلى المنزلة المحددة',
    'infer-missing-rounding-digit': 'استنتاج رقم مجهول من نتيجة التقريب',
    'diagnose-wrong-rounding-place': 'كشف استعمال منزلة هدف خاطئة',
    'correct-hundred-thousand-rounding': 'تصحيح التقريب إلى مئة ألف',
    'round-to-nearest-million': 'تقريب عدد إلى أقرب مليون',
    'justify-rounding-decision': 'تبرير قرار التقريب بالرقم المجاور',
    'apply-five-threshold': 'تطبيق حد الخمسة عند تقريب الأعداد إلى الملايين',
    'count-zeroes-after-rounding': 'عد الخانات التي تصبح أصفاراً بعد التقريب',
    'explain-rounding-decision': 'تفسير قرار الرفع أو الإبقاء',
    'connect-digit-to-result': 'ربط رقم القرار بالنتيجة النهائية',
    'diagnose-target-digit-confusion': 'كشف الخلط بين المنزلة المطلوبة ورقم القرار',
    'apply-correct-rounding-digit': 'تطبيق الرقم المجاور الصحيح',
    'round-to-multiple-places': 'إيجاد نواتج تقريب متعددة لعدد واحد',
    'check-rounded-results': 'التحقق من صحة نتائج التقريب',
    'distinguish-rounding-targets': 'تمييز ما يختلف عند تغيير المنزلة المطلوبة',
    'recalculate-at-requested-place': 'إعادة التقريب من العدد الأصلي إلى المنزلة المطلوبة',
    'compare-rounded-outcomes': 'مقارنة نتائج تقريب عدة أعداد',
    'apply-nearest-place-to-list': 'تطبيق منزلة التقريب نفسها على قائمة',
    'evaluate-rounding-explanation': 'تقويم صحة تبرير التقريب لا النتيجة وحدها',
    'identify-immediate-right-digit': 'تحديد الرقم الذي يلي منزلة التقريب مباشرة',
  },
  thinkingLabels: {
    'choose-requested-rounding-place': 'اختيار المنزلة المطلوبة عند اختلاف الدقة',
    'compare-results-near-threshold': 'مقارنة نتائج أعداد تقع حول حد التقريب',
    'evaluate-rounding-reasoning': 'تقويم رقم القرار ومنطق الوصول إلى النتيجة',
  },
  commonErrorLabels: {
    'inspect-wrong-place': 'فحص منزلة بعيدة بدلاً من الرقم المجاور',
    'inspect-target-digit-instead-of-next': 'استخدام رقم المنزلة المستهدفة بدلاً من رقم القرار',
    'inspect-rounding-place-not-neighbor': 'اتخاذ منزلة التقريب نفسها معياراً للرفع',
    'use-distant-digit-for-rounding': 'تسويغ القرار برقم بعيد عن المنزلة المطلوبة',
  },
})

export default definition
